min_glib_version = "2.84"
msvc_compatible = true
default_level = "error"

[rules.g_error_leak]
extra_propagation_functions = [
  "gdk_content_deserializer_return_error",
  "gdk_content_serializer_return_error",
  # gtk/gtkbuilderprecompile.c
  "propagate_error",
  # gtk/gtkfilechooserwidget.c
  "error_creating_folder_dialog",
  "error_building_filename_dialog",
  "error_changing_folder_dialog",
  "error_deleting_file",
  "error_dialog",
  "error_selecting_dragged_file_dialog",
  "error_trashing_file",
]

[rules.g_source_id_not_stored]
check_once_functions = false

[rules.gi_missing_since]
level = "error"

[rules.gi_not_bindings_friendly]
level = "error"
ignore = [
  "gdk/deprecated/**",
  "gtk/deprecated/**",
]

[rules.include_order]
level = "ignore"
