min_glib_version = "2.84"
msvc_compatible = true
default_level = "error"

[rules.g_error_leak]
extra_propagation_functions = [
  "gdk_content_deserializer_return_error",
  "gdk_content_serializer_return_error",
  # gtk/gtkbuilderprecompile.c
  "propagate_error",
  # gtk/gtkfilechooserwidget.c
  "error_creating_folder_dialog",
  "error_building_filename_dialog",
  "error_changing_folder_dialog",
  "error_deleting_file",
  "error_dialog",
  "error_selecting_dragged_file_dialog",
  "error_trashing_file",
]

[rules.g_source_id_not_stored]
check_once_functions = false

[rules.gi_missing_since]
level = "error"

[rules.gi_not_bindings_friendly]
level = "error"
ignore = [
  "gdk/deprecated/**",
  "gtk/deprecated/**",
]

[rules.include_order]
level = "ignore"

[rules.matching_declare_define]
level = "ignore"

[rules.missing_autoptr_cleanup]
ignore = [
  # We don't use autoptrs ourselves, so private
  # headers and source files don't need it.
  "**/*.c",
  "**/*private.h",
  # weird naming convention for private headers in the backend
  "gdk/broadway/*-broadway.h",
  "gdk/wayland/*-wayland.h",
  "gdk/win32/*-win32.h",
  "gdk/win32/gdkdevice-virtual.h",
  "gdk/win32/gdkdevice-winpointer.h",
  "gdk/win32/gdkdevice-wintab.h",
  "gdk/x11/*-x11.h",
  # directories that don't install anything
  "gtk/inspector/**",
  "demos/**",
  "examples/**",
  "tests/**",
  "testsuite/**",
]

[rules.missing_implementation]
ignore = [
  # gobject-linter can't deal with Objective-C
  "gdk/macos/**",
  # Autogenerated using macros
  "gtk/gtkcssstyleprivate.h",
  "gtk/svg/gtksvgenumprivate.h",
]

[rules.no_g_auto_macros]
ignore = ["demos/icon-editor/**"]
