#ifndef _ENUMS_
#define _ENUMS_

#define GSK_GPU_SHADER_CLIP_NONE 0u
#define GSK_GPU_SHADER_CLIP_RECT 1u
#define GSK_GPU_SHADER_CLIP_ROUNDED 2u

#define GSK_GPU_PATTERN_DONE 0u
#define GSK_GPU_PATTERN_COLOR 1u
#define GSK_GPU_PATTERN_OPACITY 2u
#define GSK_GPU_PATTERN_TEXTURE 3u
#define GSK_GPU_PATTERN_COLOR_MATRIX 4u
#define GSK_GPU_PATTERN_GLYPHS 5u
#define GSK_GPU_PATTERN_LINEAR_GRADIENT 6u
#define GSK_GPU_PATTERN_REPEATING_LINEAR_GRADIENT 7u
#define GSK_GPU_PATTERN_RADIAL_GRADIENT 8u
#define GSK_GPU_PATTERN_REPEATING_RADIAL_GRADIENT 9u
#define GSK_GPU_PATTERN_CONIC_GRADIENT 10u

#endif
