#ifndef _ENUMS_
#define _ENUMS_

#define GSK_GPU_PATTERN_STACK_SIZE 16

#define GSK_GPU_SHADER_CLIP_NONE 0u
#define GSK_GPU_SHADER_CLIP_RECT 1u
#define GSK_GPU_SHADER_CLIP_ROUNDED 2u

#define GSK_GPU_PATTERN_DONE 0u
#define GSK_GPU_PATTERN_COLOR 1u
#define GSK_GPU_PATTERN_OPACITY 2u
#define GSK_GPU_PATTERN_TEXTURE 3u
#define GSK_GPU_PATTERN_COLOR_MATRIX 4u
#define GSK_GPU_PATTERN_GLYPHS 5u
#define GSK_GPU_PATTERN_LINEAR_GRADIENT 6u
#define GSK_GPU_PATTERN_REPEATING_LINEAR_GRADIENT 7u
#define GSK_GPU_PATTERN_RADIAL_GRADIENT 8u
#define GSK_GPU_PATTERN_REPEATING_RADIAL_GRADIENT 9u
#define GSK_GPU_PATTERN_CONIC_GRADIENT 10u
#define GSK_GPU_PATTERN_CLIP 11u
#define GSK_GPU_PATTERN_ROUNDED_CLIP 12u
#define GSK_GPU_PATTERN_REPEAT_PUSH 13u
#define GSK_GPU_PATTERN_POSITION_POP 14u
#define GSK_GPU_PATTERN_PUSH_COLOR 15u
#define GSK_GPU_PATTERN_POP_CROSS_FADE 16u
#define GSK_GPU_PATTERN_POP_MASK_ALPHA 17u
#define GSK_GPU_PATTERN_POP_MASK_INVERTED_ALPHA 18u
#define GSK_GPU_PATTERN_POP_MASK_LUMINANCE 19u
#define GSK_GPU_PATTERN_POP_MASK_INVERTED_LUMINANCE 20u

#define TOP 0u
#define RIGHT 1u
#define BOTTOM 2u
#define LEFT 3u

#define TOP_LEFT 0u
#define TOP_RIGHT 1u
#define BOTTOM_RIGHT 2u
#define BOTTOM_LEFT 3u

#define SLICE_TOP_LEFT 0u
#define SLICE_TOP 1u
#define SLICE_TOP_RIGHT 2u
#define SLICE_RIGHT 3u
#define SLICE_BOTTOM_RIGHT 4u
#define SLICE_BOTTOM 5u
#define SLICE_BOTTOM_LEFT 6u
#define SLICE_LEFT 7u

#endif
