## Makefile for building the gtk test apps with Microsoft C
## Use: nmake -f makefile.msc

## There is no install target, you have to decide where and 
## how to install for yourself.

TOP = ..\..
!INCLUDE $(TOP)/glib/build/win32/make.msc

################################################################

# Possibly override versions from build/win32/module.defs
GTK_VER = 2.0
GDK_PIXBUF_VER = 2.0

GDK_LIBS = ../gdk/gdk-win32-$(GTK_VER).lib
GTK_LIBS = ../gtk/gtk-win32-$(GTK_VER).lib
GDK_PIXBUF_LIBS = ../gdk-pixbuf/gdk_pixbuf-$(GDK_PIXBUF_VER).lib

INCLUDES = -I . -I .. -I ../gdk -I ../gdk-pixbuf -I ../gtk
DEPCFLAGS = $(PANGO_CFLAGS) $(GLIB_CFLAGS) $(LIBICONV_CFLAGS) $(INTL_CFLAGS) $(ATK_CFLAGS) $(CAIRO_CFLAGS)
LDFLAGS = /link /machine:ix86 $(LINKDEBUG)
DEFINES = -DG_LOG_DOMAIN=\"GtkTest\" -DGTK_VERSION=\"$(GTK_VER)\"

TOUCH = copy makefile.msc+nul

!IFNDEF TESTAPP

all :	\
	..\config.h	\
	prop-editor.obj \
	testsocket_common.obj \
	all-test-apps

..\config.h : ..\config.h.win32
	copy ..\config.h.win32 ..\config.h


#
# Test programs:
#
TESTAPPS = \
	autotestfilechooser floatingtest \
	testaccel testactions \
	testcairo testcalendar testcellrenderertext testcombo testcombochange \
	testdnd \
	testellipsise testentrycompletion \
	testfilechooser testfilechooserbutton \
	testgtk \
	testicontheme testiconview testimage testinput \
	testmenus testmenubars testmerge testmultidisplay testmultiscreen \
	testnotebookdnd \
	testrecentchooser testrgb \
	testselection testspinbutton \
	testtext testtextbuffer testtoolbar \
	testtreecolumns testtreeedit testtreeflow testtreefocus \
	testtreesort testtreeview treestoretest \
	testsocket testsocket_child teststatusicon \
	testthreads testxinerama \
	simple 

# syntax error : illegal character '-' in macro
#stresstest-toolbar


all-test-apps: 
	@for %d in ($(TESTAPPS)) do @nmake -nologo -f makefile.msc one-test-app THIS=%d

one-test-app:
	@nmake -nologo -f makefile.msc $(THIS).exe TESTAPP=$(THIS) EXTRA_$(THIS)=1

!ELSE

!IFDEF EXTRA_testcairo
EXTRA_LIBS = $(CAIRO_LIBS)
!ENDIF

!IFDEF EXTRA_testentrycompletion
EXTRA_OBJETCS = prop-editor.obj
!ENDIF

!IFDEF EXTRA_testfilechooserbutton
EXTRA_OBJETCS = prop-editor.obj
!ENDIF

!IFDEF EXTRA_testgtk
EXTRA_LIBS = $(CAIRO_LIBS)
EXTRA_OBJETCS = prop-editor.obj
!ENDIF

!IFDEF EXTRA_testiconview
EXTRA_OBJETCS = prop-editor.obj
!ENDIF

!IFDEF EXTRA_testsocket
EXTRA_OBJETCS = testsocket_common.obj
!ENDIF

!IFDEF EXTRA_testsocket_child
EXTRA_OBJETCS = testsocket_common.obj
!ENDIF

!IFDEF EXTRA_testrecentchooser
EXTRA_OBJETCS = prop-editor.obj
!ENDIF

!IFDEF EXTRA_testtreeview
EXTRA_OBJETCS = prop-editor.obj
!ENDIF

!IFDEF EXTRA_testtext
EXTRA_OBJETCS = prop-editor.obj
!ENDIF

!IFDEF EXTRA_testtoolbar
EXTRA_OBJETCS = prop-editor.obj
!ENDIF

!IFDEF EXTRA_testfilechooser
EXTRA_OBJETCS = prop-editor.obj
EXTRA_LIBS = gdi32.lib user32.lib shell32.lib
!ENDIF

$(TESTAPP).exe : ../gtk/gtk-win32-$(GTK_VER).lib $(TESTAPP).obj
	$(CC) $(CFLAGS) $(TESTAPP).obj $(EXTRA_OBJETCS) $(GTK_LIBS) $(GDK_LIBS) $(GDK_PIXBUF_LIBS) $(PANGO_LIBS) $(GLIB_LIBS) $(EXTRA_LIBS) $(LDFLAGS)

$(TESTAPP).obj : $(TESTAPP).c
	$(CC) $(CFLAGS) -c -DG_LOG_DOMAIN=\"$(TESTAPP)\" $(TESTAPP).c

!ENDIF
