#pragma once

G_BEGIN_DECLS

typedef enum
{
  ALIGN_MIN,
  ALIGN_MID,
  ALIGN_MAX,
} Align;

typedef enum
{
  MEET,
  SLICE,
} MeetOrSlice;

typedef enum
{
  GTK_SVG_RUN_MODE_STOPPED,
  GTK_SVG_RUN_MODE_DISCRETE,
  GTK_SVG_RUN_MODE_CONTINUOUS,
} GtkSvgRunMode;

typedef enum
{
  GTK_SVG_USES_STROKES             = 1 << 0,
  GTK_SVG_USES_SYMBOLIC_FOREGROUND = 1 << 1,
  GTK_SVG_USES_SYMBOLIC_ERROR      = 1 << 2,
  GTK_SVG_USES_SYMBOLIC_WARNING    = 1 << 3,
  GTK_SVG_USES_SYMBOLIC_SUCCESS    = 1 << 4,
  GTK_SVG_USES_SYMBOLIC_ACCENT     = 1 << 5,
} GtkSvgUses;

typedef enum
{
  SVG_UNIT_NUMBER,
  SVG_UNIT_PERCENTAGE,
  SVG_UNIT_PX,
  FIRST_LENGTH_UNIT = SVG_UNIT_PX,
  SVG_UNIT_PT,
  SVG_UNIT_IN,
  SVG_UNIT_CM,
  SVG_UNIT_MM,
  SVG_UNIT_VW,
  SVG_UNIT_VH,
  SVG_UNIT_VMIN,
  SVG_UNIT_VMAX,
  SVG_UNIT_EM,
  SVG_UNIT_EX,
  LAST_LENGTH_UNIT = SVG_UNIT_EX,
  SVG_UNIT_DEG,
  FIRST_ANGLE_UNIT = SVG_UNIT_DEG,
  SVG_UNIT_RAD,
  SVG_UNIT_GRAD,
  SVG_UNIT_TURN,
  LAST_ANGLE_UNIT = SVG_UNIT_TURN,
} SvgUnit;

typedef enum
{
  PAINT_NONE,
  PAINT_CONTEXT_FILL,
  PAINT_CONTEXT_STROKE,
  PAINT_CURRENT_COLOR,
  PAINT_COLOR,
  PAINT_SYMBOLIC,
  PAINT_SERVER,
  PAINT_SERVER_WITH_FALLBACK,
  PAINT_SERVER_WITH_CURRENT_COLOR,
} PaintKind;

typedef enum
{
  PAINT_ORDER_FILL_STROKE_MARKERS,
  PAINT_ORDER_FILL_MARKERS_STROKE,
  PAINT_ORDER_STROKE_FILL_MARKERS,
  PAINT_ORDER_STROKE_MARKERS_FILL,
  PAINT_ORDER_MARKERS_FILL_STROKE,
  PAINT_ORDER_MARKERS_STROKE_FILL,
} PaintOrder;

typedef enum
{
  CLIP_NONE,
  CLIP_PATH,
  CLIP_URL,
} ClipKind;

typedef enum
{
  TRANSFORM_NONE,
  TRANSFORM_TRANSLATE,
  TRANSFORM_SCALE,
  TRANSFORM_ROTATE,
  TRANSFORM_SKEW_X,
  TRANSFORM_SKEW_Y,
  TRANSFORM_MATRIX,
} TransformType;

enum
{
  NUMBER     = 1 << 0,
  PERCENTAGE = 1 << 1,
  LENGTH     = 1 << 2,
  ANGLE      = 1 << 3,
};

typedef enum
{
  COORD_UNITS_USER_SPACE_ON_USE,
  COORD_UNITS_OBJECT_BOUNDING_BOX,
} CoordUnits;

typedef enum
{
  VISIBILITY_HIDDEN,
  VISIBILITY_VISIBLE,
} Visibility;

typedef enum
{
  DISPLAY_NONE,
  DISPLAY_INLINE,
} SvgDisplay;

typedef enum
{
  OVERFLOW_VISIBLE,
  OVERFLOW_HIDDEN,
  OVERFLOW_AUTO,
} SvgOverflow;

typedef enum {
  ISOLATION_AUTO,
  ISOLATION_ISOLATE,
} Isolation;

typedef enum {
  TEXT_ANCHOR_START,
  TEXT_ANCHOR_MIDDLE,
  TEXT_ANCHOR_END
} TextAnchor;

typedef enum
{
  MARKER_UNITS_STROKE_WIDTH,
  MARKER_UNITS_USER_SPACE_ON_USE,
} MarkerUnits;

typedef enum {
  UNICODE_BIDI_NORMAL,
  UNICODE_BIDI_EMBED,
  UNICODE_BIDI_OVERRIDE
} UnicodeBidi;

typedef enum {
  WRITING_MODE_HORIZONTAL_TB,
  WRITING_MODE_VERTICAL_RL,
  WRITING_MODE_VERTICAL_LR,

  /* SVG 1.1 legacy properties */
  WRITING_MODE_LEGACY_LR,
  WRITING_MODE_LEGACY_LR_TB,
  WRITING_MODE_LEGACY_RL,
  WRITING_MODE_LEGACY_RL_TB,
  WRITING_MODE_LEGACY_TB,
  WRITING_MODE_LEGACY_TB_RL,
} WritingMode;

typedef enum
{
  EDGE_MODE_DUPLICATE,
  EDGE_MODE_WRAP,
  EDGE_MODE_NONE,
} EdgeMode;


typedef enum
{
  BLEND_COMPOSITE,
  BLEND_NO_COMPOSITE,
} BlendComposite;

typedef enum
{
  COLOR_MATRIX_TYPE_MATRIX,
  COLOR_MATRIX_TYPE_SATURATE,
  COLOR_MATRIX_TYPE_HUE_ROTATE,
  COLOR_MATRIX_TYPE_LUMINANCE_TO_ALPHA,
} ColorMatrixType;

typedef enum
{
  COMPOSITE_OPERATOR_OVER,
  COMPOSITE_OPERATOR_IN,
  COMPOSITE_OPERATOR_OUT,
  COMPOSITE_OPERATOR_ATOP,
  COMPOSITE_OPERATOR_XOR,
  COMPOSITE_OPERATOR_LIGHTER,
  COMPOSITE_OPERATOR_ARITHMETIC,
} CompositeOperator;

typedef enum
{
  COMPONENT_TRANSFER_IDENTITY,
  COMPONENT_TRANSFER_TABLE,
  COMPONENT_TRANSFER_DISCRETE,
  COMPONENT_TRANSFER_LINEAR,
  COMPONENT_TRANSFER_GAMMA,
} ComponentTransferType;

typedef enum
{
  VECTOR_EFFECT_NONE,
  VECTOR_EFFECT_NON_SCALING_STROKE,
} VectorEffect;

typedef enum
{
  FONT_SIZE_SMALLER,
  FONT_SIZE_LARGER,
  FONT_SIZE_XX_SMALL,
  FONT_SIZE_X_SMALL,
  FONT_SIZE_SMALL,
  FONT_SIZE_MEDIUM,
  FONT_SIZE_LARGE,
  FONT_SIZE_X_LARGE,
  FONT_SIZE_XX_LARGE,
} FontSize;

typedef enum {
  FONT_WEIGHT_NORMAL,
  FONT_WEIGHT_BOLD,
  FONT_WEIGHT_BOLDER,
  FONT_WEIGHT_LIGHTER,
} FontWeight;

typedef enum
{
  COLOR_INTERPOLATION_AUTO,
  COLOR_INTERPOLATION_SRGB,
  COLOR_INTERPOLATION_LINEAR,
} ColorInterpolation;

typedef enum
{
  TRANSFORM_BOX_CONTENT_BOX,
  TRANSFORM_BOX_BORDER_BOX,
  TRANSFORM_BOX_FILL_BOX,
  TRANSFORM_BOX_STROKE_BOX,
  TRANSFORM_BOX_VIEW_BOX,
} TransformBox;

typedef enum
{
  SHAPE_RENDERING_AUTO,
  SHAPE_RENDERING_OPTIMIZE_SPEED,
  SHAPE_RENDERING_CRISP_EDGES,
  SHAPE_RENDERING_GEOMETRIC_PRECISION,
} ShapeRendering;

typedef enum
{
  TEXT_RENDERING_AUTO,
  TEXT_RENDERING_OPTIMIZE_SPEED,
  TEXT_RENDERING_OPTIMIZE_LEGIBILITY,
  TEXT_RENDERING_GEOMETRIC_PRECISION,
} TextRendering;


typedef enum
{
  IMAGE_RENDERING_AUTO,
  IMAGE_RENDERING_OPTIMIZE_QUALITY,
  IMAGE_RENDERING_OPTIMIZE_SPEED,
} ImageRendering;

typedef enum
{
  FILTER_NONE,
  FILTER_BLUR,
  FILTER_BRIGHTNESS,
  FILTER_CONTRAST,
  FILTER_GRAYSCALE,
  FILTER_HUE_ROTATE,
  FILTER_INVERT,
  FILTER_OPACITY,
  FILTER_SATURATE,
  FILTER_SEPIA,
  FILTER_REF,
  FILTER_DROPSHADOW,
} FilterKind;

typedef enum
{
  DASH_ARRAY_NONE,
  DASH_ARRAY_DASHES,
} DashArrayKind;

G_END_DECLS
