deprecated_h_sources = 			\
	deprecated/gtkgradient.h	\
	deprecated/gtksymboliccolor.h

deprecated_private_h_sources =			\
	deprecated/gtkgradientprivate.h		\
	deprecated/gtksymboliccolorprivate.h

deprecated_c_sources = 			\
	deprecated/gtkgradient.c	\
	deprecated/gtksymboliccolor.c
