deprecated_h_sources = 			\
	deprecated/gtkactivatable.h	\
	deprecated/gtkaction.h		\
	deprecated/gtkactiongroup.h	\
	deprecated/gtkgradient.h	\
	deprecated/gtkrecentaction.h	\
	deprecated/gtksymboliccolor.h	\
	deprecated/gtktoggleaction.h	\
	deprecated/gtkuimanager.h

deprecated_private_h_sources =			\
	deprecated/gtkgradientprivate.h		\
	deprecated/gtksymboliccolorprivate.h

deprecated_c_sources = 			\
	deprecated/gtkactivatable.c	\
	deprecated/gtkaction.c		\
	deprecated/gtkactiongroup.c	\
	deprecated/gtkgradient.c	\
	deprecated/gtkrecentaction.c	\
	deprecated/gtksymboliccolor.c	\
	deprecated/gtktoggleaction.c	\
	deprecated/gtkuimanager.c
