#include <glib.h>

/* from gdk */
void _gdk_windowing_after_process_all_updates (void) { g_assert_not_reached (); }
void _gdk_windowing_window_get_input_shape (void) { g_assert_not_reached (); }
void gdk_keymap_get_for_display (void) { g_assert_not_reached (); }
void gdk_device_ungrab (void) { g_assert_not_reached (); }
void gdk_display_get_name (void) { g_assert_not_reached (); }
void _gdk_windowing_launch_failed (void) { g_assert_not_reached (); }
void gdk_screen_get_height_mm (void) { g_assert_not_reached (); }
void gdk_window_foreign_new_for_display (void) { g_assert_not_reached (); }
void _gdk_windowing_substitute_screen_number (void) { g_assert_not_reached (); }
void gdk_screen_get_n_monitors (void) { g_assert_not_reached (); }
void gdk_screen_get_width_mm (void) { g_assert_not_reached (); }
void gdk_cursor_new_for_display (void) { g_assert_not_reached (); }
void _gdk_windowing_get_device_state (void) { g_assert_not_reached (); }
void gdk_string_to_compound_text_for_display (void) { g_assert_not_reached (); }
void gdk_text_property_to_text_list_for_display (void) { g_assert_not_reached (); }
void gdk_drag_find_window_for_screen (void) { g_assert_not_reached (); }
void gdk_display_supports_composite (void) { g_assert_not_reached (); }
void _gdk_windowing_window_destroy_foreign (void) { g_assert_not_reached (); }
void _gdk_windowing_window_get_next_serial (void) { g_assert_not_reached (); }
void _gdk_events_queue (void) { g_assert_not_reached (); }
void gdk_utf8_to_compound_text_for_display (void) { g_assert_not_reached (); }
void gdk_display_beep (void) { g_assert_not_reached (); }
void _gdk_windowing_window_at_device_position (void) { g_assert_not_reached (); }
void gdk_drag_get_protocol_for_display (void) { g_assert_not_reached (); }
void gdk_input_set_extension_events (void) { g_assert_not_reached (); }
void gdk_selection_send_notify_for_display (void) { g_assert_not_reached (); }
void gdk_display_sync (void) { g_assert_not_reached (); }
void _gdk_windowing_window_process_updates_recurse (void) { g_assert_not_reached (); }
void _gdk_cursor_destroy (void) { g_assert_not_reached (); }
void gdk_screen_get_monitor_geometry (void) { g_assert_not_reached (); }
void gdk_display_flush (void) { g_assert_not_reached (); }
void gdk_screen_list_visuals (void) { g_assert_not_reached (); }
void _gdk_windowing_get_startup_notify_id (void) { g_assert_not_reached (); }
void _gdk_windowing_before_process_all_updates (void) { g_assert_not_reached (); }
void gdk_screen_get_width (void) { g_assert_not_reached (); }
void _gdk_windowing_event_data_free (void) { g_assert_not_reached (); }
void gdk_selection_owner_set_for_display (void) { g_assert_not_reached (); }
void _gdk_input_check_extension_events (void) { g_assert_not_reached (); }
void _gdk_windowing_event_data_copy (void) { g_assert_not_reached (); }
void _gdk_windowing_window_set_composited (void) { g_assert_not_reached (); }
void gdk_screen_make_display_name (void) { g_assert_not_reached (); }
void _gdk_windowing_device_grab (void) { g_assert_not_reached (); }
void *_gdk_windowing_args = NULL;
void _gdk_windowing_window_beep (void) { g_assert_not_reached (); }
void _gdk_windowing_display_set_sm_client_id (void) { g_assert_not_reached (); }
void gdk_screen_get_height (void) { g_assert_not_reached (); }
void gdk_screen_broadcast_client_message (void) { g_assert_not_reached (); }
void gdk_selection_owner_get_for_display (void) { g_assert_not_reached (); }
void gdk_screen_get_rgba_visual (void) { g_assert_not_reached (); }
void _gdk_windowing_window_get_shape (void) { g_assert_not_reached (); }
void gdk_event_send_client_message_for_display (void) { g_assert_not_reached (); }
void gdk_text_property_to_utf8_list_for_display (void) { g_assert_not_reached (); }

/* from gtk */
void gdk_display_supports_selection_notification (void) { g_assert_not_reached (); }
void gdk_keymap_get_entries_for_keycode (void) { g_assert_not_reached (); }
void gdk_spawn_on_screen (void) { g_assert_not_reached (); }
void gdk_keyval_name (void) { g_assert_not_reached (); }
void gdk_drop_reply (void) { g_assert_not_reached (); }
void gdk_window_lookup_for_display (void) { g_assert_not_reached (); }
void gdk_keymap_get_entries_for_keyval (void) { g_assert_not_reached (); }
void gdk_display_get_n_screens (void) { g_assert_not_reached (); }
void gdk_display_request_selection_notification (void) { g_assert_not_reached (); }
void gdk_keymap_get_caps_lock_state (void) { g_assert_not_reached (); }
void gdk_window_begin_move_drag (void) { g_assert_not_reached (); }
void gdk_drag_status (void) { g_assert_not_reached (); }
void gdk_window_set_icon_list (void) { g_assert_not_reached (); }
void gdk_window_set_keep_above (void) { g_assert_not_reached (); }
void gdk_window_set_type_hint (void) { g_assert_not_reached (); }
void gdk_keymap_get_num_lock_state (void) { g_assert_not_reached (); }
void gdk_display_get_maximal_cursor_size (void) { g_assert_not_reached (); }
void gdk_drag_context_get_device (void) { g_assert_not_reached (); }
void gdk_notify_startup_complete (void) { g_assert_not_reached (); }
void gdk_window_set_title (void) { g_assert_not_reached (); }
void gdk_keymap_get_direction (void) { g_assert_not_reached (); }
void gdk_flush (void) { g_assert_not_reached (); }
void gdk_selection_property_get (void) { g_assert_not_reached (); }
void gdk_drag_context_set_device (void) { g_assert_not_reached (); }
void gdk_window_set_skip_taskbar_hint (void) { g_assert_not_reached (); }
void gdk_window_unfullscreen (void) { g_assert_not_reached (); }
void gdk_window_set_focus_on_map (void) { g_assert_not_reached (); }
void gdk_window_enable_synchronized_configure (void) { g_assert_not_reached (); }
void gdk_window_begin_resize_drag (void) { g_assert_not_reached (); }
void gdk_property_change (void) { g_assert_not_reached (); }
void gdk_window_set_decorations (void) { g_assert_not_reached (); }
void gdk_window_set_role (void) { g_assert_not_reached (); }
void gdk_cursor_get_display (void) { g_assert_not_reached (); }
void gdk_window_set_transient_for (void) { g_assert_not_reached (); }
void gdk_window_get_frame_extents (void) { g_assert_not_reached (); }
void gdk_test_simulate_button (void) { g_assert_not_reached (); }
void gdk_keyval_from_name (void) { g_assert_not_reached (); }
void gdk_window_set_modal_hint (void) { g_assert_not_reached (); }
void gdk_error_trap_pop_ignored (void) { g_assert_not_reached (); }
void gdk_error_trap_pop (void) { g_assert_not_reached (); }
void gdk_display_get_screen (void) { g_assert_not_reached (); }
void gdk_display_store_clipboard (void) { g_assert_not_reached (); }
void gdk_cursor_get_image (void) { g_assert_not_reached (); }
void gdk_drag_motion (void) { g_assert_not_reached (); }
void gdk_window_set_geometry_hints (void) { g_assert_not_reached (); }
void gdk_atom_intern_static_string (void) { g_assert_not_reached (); }
void gdk_error_trap_push (void) { g_assert_not_reached (); }
void gdk_window_iconify (void) { g_assert_not_reached (); }
void gdk_screen_is_composited (void) { g_assert_not_reached (); }
void gdk_display_supports_cursor_color (void) { g_assert_not_reached (); }
void gdk_window_unstick (void) { g_assert_not_reached (); }
void gdk_window_set_opacity (void) { g_assert_not_reached (); }
void gdk_window_fullscreen (void) { g_assert_not_reached (); }
void gdk_window_set_startup_id (void) { g_assert_not_reached (); }
void gdk_selection_convert (void) { g_assert_not_reached (); }
void gdk_window_set_keep_below (void) { g_assert_not_reached (); }
void gdk_window_register_dnd (void) { g_assert_not_reached (); }
void gdk_window_deiconify (void) { g_assert_not_reached (); }
void gdk_property_delete (void) { g_assert_not_reached (); }
void gdk_window_set_accept_focus (void) { g_assert_not_reached (); }
void gdk_window_set_urgency_hint (void) { g_assert_not_reached (); }
void gdk_free_compound_text (void) { g_assert_not_reached (); }
void gdk_window_maximize (void) { g_assert_not_reached (); }
void gdk_drag_begin (void) { g_assert_not_reached (); }
void gdk_drag_get_selection (void) { g_assert_not_reached (); }
void gdk_window_set_functions (void) { g_assert_not_reached (); }
void gdk_drag_drop (void) { g_assert_not_reached (); }
void gdk_cursor_new_from_pixbuf (void) { g_assert_not_reached (); }
void gdk_test_simulate_key (void) { g_assert_not_reached (); }
void gdk_utf8_to_string_target (void) { g_assert_not_reached (); }
void gdk_display_supports_clipboard_persistence (void) { g_assert_not_reached (); }
void gdk_keymap_map_virtual_modifiers (void) { g_assert_not_reached (); }
void gdk_window_stick (void) { g_assert_not_reached (); }
void gdk_display_warp_device (void) { g_assert_not_reached (); }
void gdk_drag_abort (void) { g_assert_not_reached (); }
void gdk_window_unmaximize (void) { g_assert_not_reached (); }
void gdk_cursor_new_from_name (void) { g_assert_not_reached (); }
void gdk_display_get_default_cursor_size (void) { g_assert_not_reached (); }
void gdk_set_locale (void) { g_assert_not_reached (); }
void gdk_window_set_skip_pager_hint (void) { g_assert_not_reached (); }
void gdk_keymap_add_virtual_modifiers (void) { g_assert_not_reached (); }
void gdk_window_configure_finished (void) { g_assert_not_reached (); }
void gdk_atom_name (void) { g_assert_not_reached (); }
void gdk_property_get (void) { g_assert_not_reached (); }
void gdk_window_focus (void) { g_assert_not_reached (); }
void gdk_keymap_translate_keyboard_state (void) { g_assert_not_reached (); }
void gdk_drop_finish (void) { g_assert_not_reached (); }
void gdk_atom_intern (void) { g_assert_not_reached (); }
void gdk_display_supports_cursor_alpha (void) { g_assert_not_reached (); }
void gdk_notify_startup_complete_with_id (void) { g_assert_not_reached (); }

/* other stuff */
void gdk_test_render_sync (void) { g_assert_not_reached (); }
void gdk_display_add_client_message_filter (void) { g_assert_not_reached (); }
void gdk_screen_get_primary_monitor (void) { g_assert_not_reached (); }
void gdk_window_get_root_origin (void) { g_assert_not_reached (); }
void gdk_window_set_icon_name (void) { g_assert_not_reached (); }
