#!/usr/bin/perl

# Stupid script to fix look of html files created with sgml2html...

foreach (@ARGV) {
    print "Fixing... $_\n";
    system("mv $_ $_.orig");
    system("sed -e 's/<BODY>/<BODY BGCOLOR=\"#FFFFFF\">/g' -e 's/<HR>/<HR NOSHADE>/g' $_.orig > $_");
    unlink("$_.orig");
}

