/* generated by makeenums.awk from "./gtk.defs" */

static GtkEnumValue enum_values_GtkAccelFlags[] = {
  { GTK_ACCEL_VISIBLE, "GTK_ACCEL_VISIBLE", "visible" },
  { GTK_ACCEL_SIGNAL_VISIBLE, "GTK_ACCEL_SIGNAL_VISIBLE", "signal-visible" },
  { GTK_ACCEL_LOCKED, "GTK_ACCEL_LOCKED", "locked" },
  { GTK_ACCEL_MASK, "GTK_ACCEL_MASK", "mask" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkArrowType[] = {
  { GTK_ARROW_UP, "GTK_ARROW_UP", "up" },
  { GTK_ARROW_DOWN, "GTK_ARROW_DOWN", "down" },
  { GTK_ARROW_LEFT, "GTK_ARROW_LEFT", "left" },
  { GTK_ARROW_RIGHT, "GTK_ARROW_RIGHT", "right" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkAttachOptions[] = {
  { GTK_EXPAND, "GTK_EXPAND", "expand" },
  { GTK_SHRINK, "GTK_SHRINK", "shrink" },
  { GTK_FILL, "GTK_FILL", "fill" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkButtonBoxStyle[] = {
  { GTK_BUTTONBOX_DEFAULT_STYLE, "GTK_BUTTONBOX_DEFAULT_STYLE", "default" },
  { GTK_BUTTONBOX_SPREAD, "GTK_BUTTONBOX_SPREAD", "spread" },
  { GTK_BUTTONBOX_EDGE, "GTK_BUTTONBOX_EDGE", "edge" },
  { GTK_BUTTONBOX_START, "GTK_BUTTONBOX_START", "start" },
  { GTK_BUTTONBOX_END, "GTK_BUTTONBOX_END", "end" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkDirectionType[] = {
  { GTK_DIR_TAB_FORWARD, "GTK_DIR_TAB_FORWARD", "tab-forward" },
  { GTK_DIR_TAB_BACKWARD, "GTK_DIR_TAB_BACKWARD", "tab-backward" },
  { GTK_DIR_UP, "GTK_DIR_UP", "up" },
  { GTK_DIR_DOWN, "GTK_DIR_DOWN", "down" },
  { GTK_DIR_LEFT, "GTK_DIR_LEFT", "left" },
  { GTK_DIR_RIGHT, "GTK_DIR_RIGHT", "right" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkJustification[] = {
  { GTK_JUSTIFY_LEFT, "GTK_JUSTIFY_LEFT", "left" },
  { GTK_JUSTIFY_RIGHT, "GTK_JUSTIFY_RIGHT", "right" },
  { GTK_JUSTIFY_CENTER, "GTK_JUSTIFY_CENTER", "center" },
  { GTK_JUSTIFY_FILL, "GTK_JUSTIFY_FILL", "fill" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkMatchType[] = {
  { GTK_MATCH_ALL, "GTK_MATCH_ALL", "all" },
  { GTK_MATCH_ALL_TAIL, "GTK_MATCH_ALL_TAIL", "all-tail" },
  { GTK_MATCH_HEAD, "GTK_MATCH_HEAD", "head" },
  { GTK_MATCH_TAIL, "GTK_MATCH_TAIL", "tail" },
  { GTK_MATCH_EXACT, "GTK_MATCH_EXACT", "exact" },
  { GTK_MATCH_LAST, "GTK_MATCH_LAST", "last" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkMenuFactoryType[] = {
  { GTK_MENU_FACTORY_MENU, "GTK_MENU_FACTORY_MENU", "menu" },
  { GTK_MENU_FACTORY_MENU_BAR, "GTK_MENU_FACTORY_MENU_BAR", "menu-bar" },
  { GTK_MENU_FACTORY_OPTION_MENU, "GTK_MENU_FACTORY_OPTION_MENU", "option-menu" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkMetricType[] = {
  { GTK_PIXELS, "GTK_PIXELS", "pixels" },
  { GTK_INCHES, "GTK_INCHES", "inches" },
  { GTK_CENTIMETERS, "GTK_CENTIMETERS", "centimeters" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkOrientation[] = {
  { GTK_ORIENTATION_HORIZONTAL, "GTK_ORIENTATION_HORIZONTAL", "horizontal" },
  { GTK_ORIENTATION_VERTICAL, "GTK_ORIENTATION_VERTICAL", "vertical" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkPackType[] = {
  { GTK_PACK_START, "GTK_PACK_START", "start" },
  { GTK_PACK_END, "GTK_PACK_END", "end" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkPathPriorityType[] = {
  { GTK_PATH_PRIO_LOWEST, "GTK_PATH_PRIO_LOWEST", "lowest" },
  { GTK_PATH_PRIO_GTK, "GTK_PATH_PRIO_GTK", "gtk" },
  { GTK_PATH_PRIO_APPLICATION, "GTK_PATH_PRIO_APPLICATION", "application" },
  { GTK_PATH_PRIO_RC, "GTK_PATH_PRIO_RC", "rc" },
  { GTK_PATH_PRIO_HIGHEST, "GTK_PATH_PRIO_HIGHEST", "highest" },
  { GTK_PATH_PRIO_MASK, "GTK_PATH_PRIO_MASK", "mask" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkPathType[] = {
  { GTK_PATH_WIDGET, "GTK_PATH_WIDGET", "widget" },
  { GTK_PATH_WIDGET_CLASS, "GTK_PATH_WIDGET_CLASS", "widget-class" },
  { GTK_PATH_CLASS, "GTK_PATH_CLASS", "class" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkPolicyType[] = {
  { GTK_POLICY_ALWAYS, "GTK_POLICY_ALWAYS", "always" },
  { GTK_POLICY_AUTOMATIC, "GTK_POLICY_AUTOMATIC", "automatic" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkPositionType[] = {
  { GTK_POS_LEFT, "GTK_POS_LEFT", "left" },
  { GTK_POS_RIGHT, "GTK_POS_RIGHT", "right" },
  { GTK_POS_TOP, "GTK_POS_TOP", "top" },
  { GTK_POS_BOTTOM, "GTK_POS_BOTTOM", "bottom" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkPreviewType[] = {
  { GTK_PREVIEW_COLOR, "GTK_PREVIEW_COLOR", "color" },
  { GTK_PREVIEW_GRAYSCALE, "GTK_PREVIEW_GRAYSCALE", "grayscale" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkReliefStyle[] = {
  { GTK_RELIEF_NORMAL, "GTK_RELIEF_NORMAL", "normal" },
  { GTK_RELIEF_NONE, "GTK_RELIEF_NONE", "none" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkScrollType[] = {
  { GTK_SCROLL_NONE, "GTK_SCROLL_NONE", "none" },
  { GTK_SCROLL_STEP_BACKWARD, "GTK_SCROLL_STEP_BACKWARD", "step-backward" },
  { GTK_SCROLL_STEP_FORWARD, "GTK_SCROLL_STEP_FORWARD", "step-forward" },
  { GTK_SCROLL_PAGE_BACKWARD, "GTK_SCROLL_PAGE_BACKWARD", "page-backward" },
  { GTK_SCROLL_PAGE_FORWARD, "GTK_SCROLL_PAGE_FORWARD", "page-forward" },
  { GTK_SCROLL_JUMP, "GTK_SCROLL_JUMP", "jump" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkSelectionMode[] = {
  { GTK_SELECTION_SINGLE, "GTK_SELECTION_SINGLE", "single" },
  { GTK_SELECTION_BROWSE, "GTK_SELECTION_BROWSE", "browse" },
  { GTK_SELECTION_MULTIPLE, "GTK_SELECTION_MULTIPLE", "multiple" },
  { GTK_SELECTION_EXTENDED, "GTK_SELECTION_EXTENDED", "extended" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkShadowType[] = {
  { GTK_SHADOW_NONE, "GTK_SHADOW_NONE", "none" },
  { GTK_SHADOW_IN, "GTK_SHADOW_IN", "in" },
  { GTK_SHADOW_OUT, "GTK_SHADOW_OUT", "out" },
  { GTK_SHADOW_ETCHED_IN, "GTK_SHADOW_ETCHED_IN", "etched-in" },
  { GTK_SHADOW_ETCHED_OUT, "GTK_SHADOW_ETCHED_OUT", "etched-out" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkSignalRunType[] = {
  { GTK_RUN_FIRST, "GTK_RUN_FIRST", "first" },
  { GTK_RUN_LAST, "GTK_RUN_LAST", "last" },
  { GTK_RUN_BOTH, "GTK_RUN_BOTH", "both" },
  { GTK_RUN_MASK, "GTK_RUN_MASK", "mask" },
  { GTK_RUN_NO_RECURSE, "GTK_RUN_NO_RECURSE", "no-recurse" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkStateType[] = {
  { GTK_STATE_NORMAL, "GTK_STATE_NORMAL", "normal" },
  { GTK_STATE_ACTIVE, "GTK_STATE_ACTIVE", "active" },
  { GTK_STATE_PRELIGHT, "GTK_STATE_PRELIGHT", "prelight" },
  { GTK_STATE_SELECTED, "GTK_STATE_SELECTED", "selected" },
  { GTK_STATE_INSENSITIVE, "GTK_STATE_INSENSITIVE", "insensitive" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkSubmenuDirection[] = {
  { GTK_DIRECTION_LEFT, "GTK_DIRECTION_LEFT", "left" },
  { GTK_DIRECTION_RIGHT, "GTK_DIRECTION_RIGHT", "right" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkSubmenuPlacement[] = {
  { GTK_TOP_BOTTOM, "GTK_TOP_BOTTOM", "top-bottom" },
  { GTK_LEFT_RIGHT, "GTK_LEFT_RIGHT", "left-right" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkToolbarStyle[] = {
  { GTK_TOOLBAR_ICONS, "GTK_TOOLBAR_ICONS", "icons" },
  { GTK_TOOLBAR_TEXT, "GTK_TOOLBAR_TEXT", "text" },
  { GTK_TOOLBAR_BOTH, "GTK_TOOLBAR_BOTH", "both" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkTroughType[] = {
  { GTK_TROUGH_NONE, "GTK_TROUGH_NONE", "none" },
  { GTK_TROUGH_START, "GTK_TROUGH_START", "start" },
  { GTK_TROUGH_END, "GTK_TROUGH_END", "end" },
  { GTK_TROUGH_JUMP, "GTK_TROUGH_JUMP", "jump" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkUpdateType[] = {
  { GTK_UPDATE_CONTINUOUS, "GTK_UPDATE_CONTINUOUS", "continuous" },
  { GTK_UPDATE_DISCONTINUOUS, "GTK_UPDATE_DISCONTINUOUS", "discontinuous" },
  { GTK_UPDATE_DELAYED, "GTK_UPDATE_DELAYED", "delayed" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkVisibility[] = {
  { GTK_VISIBILITY_NONE, "GTK_VISIBILITY_NONE", "none" },
  { GTK_UPDATE_DISCONTINUOUS, "GTK_UPDATE_DISCONTINUOUS", "discontinuous" },
  { GTK_UPDATE_DELAYED, "GTK_UPDATE_DELAYED", "delayed" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkWindowPosition[] = {
  { GTK_WIN_POS_NONE, "GTK_WIN_POS_NONE", "none" },
  { GTK_WIN_POS_CENTER, "GTK_WIN_POS_CENTER", "center" },
  { GTK_WIN_POS_MOUSE, "GTK_WIN_POS_MOUSE", "mouse" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkWindowType[] = {
  { GTK_WINDOW_TOPLEVEL, "GTK_WINDOW_TOPLEVEL", "toplevel" },
  { GTK_WINDOW_DIALOG, "GTK_WINDOW_DIALOG", "dialog" },
  { GTK_WINDOW_POPUP, "GTK_WINDOW_POPUP", "popup" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkObjectFlags[] = {
  { GTK_DESTROYED, "GTK_DESTROYED", "destroyed" },
  { GTK_FLOATING, "GTK_FLOATING", "floating" },
  { GTK_CONNECTED, "GTK_CONNECTED", "connected" },
  { GTK_OBJECT_FLAG_LAST, "GTK_OBJECT_FLAG_LAST", "object-flag-last" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkArgFlags[] = {
  { GTK_ARG_READABLE, "GTK_ARG_READABLE", "readable" },
  { GTK_ARG_WRITABLE, "GTK_ARG_WRITABLE", "writable" },
  { GTK_ARG_CONSTRUCT, "GTK_ARG_CONSTRUCT", "construct" },
  { GTK_ARG_MASK, "GTK_ARG_MASK", "mask" },
  { GTK_ARG_READWRITE, "GTK_ARG_READWRITE", "readwrite" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkWidgetFlags[] = {
  { GTK_TOPLEVEL, "GTK_TOPLEVEL", "toplevel" },
  { GTK_NO_WINDOW, "GTK_NO_WINDOW", "no-window" },
  { GTK_REALIZED, "GTK_REALIZED", "realized" },
  { GTK_MAPPED, "GTK_MAPPED", "mapped" },
  { GTK_VISIBLE, "GTK_VISIBLE", "visible" },
  { GTK_SENSITIVE, "GTK_SENSITIVE", "sensitive" },
  { GTK_PARENT_SENSITIVE, "GTK_PARENT_SENSITIVE", "parent-sensitive" },
  { GTK_CAN_FOCUS, "GTK_CAN_FOCUS", "can-focus" },
  { GTK_HAS_FOCUS, "GTK_HAS_FOCUS", "has-focus" },
  { GTK_CAN_DEFAULT, "GTK_CAN_DEFAULT", "can-default" },
  { GTK_HAS_DEFAULT, "GTK_HAS_DEFAULT", "has-default" },
  { GTK_HAS_GRAB, "GTK_HAS_GRAB", "has-grab" },
  { GTK_RC_STYLE, "GTK_RC_STYLE", "rc-style" },
  { GTK_BASIC, "GTK_BASIC", "basic" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkPrivateFlags[] = {
  { PRIVATE_GTK_USER_STYLE, "PRIVATE_GTK_USER_STYLE", "user-style" },
  { PRIVATE_GTK_REDRAW_PENDING, "PRIVATE_GTK_REDRAW_PENDING", "redraw-pending" },
  { PRIVATE_GTK_RESIZE_PENDING, "PRIVATE_GTK_RESIZE_PENDING", "resize-pending" },
  { PRIVATE_GTK_RESIZE_NEEDED, "PRIVATE_GTK_RESIZE_NEEDED", "resize-needed" },
  { PRIVATE_GTK_LEAVE_PENDING, "PRIVATE_GTK_LEAVE_PENDING", "leave-pending" },
  { PRIVATE_GTK_HAS_SHAPE_MASK, "PRIVATE_GTK_HAS_SHAPE_MASK", "has-shape-mask" },
  { PRIVATE_GTK_IN_REPARENT, "PRIVATE_GTK_IN_REPARENT", "in-reparent" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkCurveType[] = {
  { GTK_CURVE_TYPE_LINEAR, "GTK_CURVE_TYPE_LINEAR", "linear" },
  { GTK_CURVE_TYPE_SPLINE, "GTK_CURVE_TYPE_SPLINE", "spline" },
  { GTK_CURVE_TYPE_FREE, "GTK_CURVE_TYPE_FREE", "free" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GtkFundamentalType[] = {
  { GTK_TYPE_INVALID, "GTK_TYPE_INVALID", "invalid" },
  { GTK_TYPE_NONE, "GTK_TYPE_NONE", "none" },
  { GTK_TYPE_CHAR, "GTK_TYPE_CHAR", "char" },
  { GTK_TYPE_BOOL, "GTK_TYPE_BOOL", "bool" },
  { GTK_TYPE_INT, "GTK_TYPE_INT", "int" },
  { GTK_TYPE_UINT, "GTK_TYPE_UINT", "uint" },
  { GTK_TYPE_LONG, "GTK_TYPE_LONG", "long" },
  { GTK_TYPE_ULONG, "GTK_TYPE_ULONG", "ulong" },
  { GTK_TYPE_FLOAT, "GTK_TYPE_FLOAT", "float" },
  { GTK_TYPE_DOUBLE, "GTK_TYPE_DOUBLE", "double" },
  { GTK_TYPE_STRING, "GTK_TYPE_STRING", "string" },
  { GTK_TYPE_ENUM, "GTK_TYPE_ENUM", "enum" },
  { GTK_TYPE_FLAGS, "GTK_TYPE_FLAGS", "flags" },
  { GTK_TYPE_BOXED, "GTK_TYPE_BOXED", "boxed" },
  { GTK_TYPE_FOREIGN, "GTK_TYPE_FOREIGN", "foreign" },
  { GTK_TYPE_CALLBACK, "GTK_TYPE_CALLBACK", "callback" },
  { GTK_TYPE_ARGS, "GTK_TYPE_ARGS", "args" },
  { GTK_TYPE_POINTER, "GTK_TYPE_POINTER", "pointer" },
  { GTK_TYPE_SIGNAL, "GTK_TYPE_SIGNAL", "signal" },
  { GTK_TYPE_C_CALLBACK, "GTK_TYPE_C_CALLBACK", "c-callback" },
  { GTK_TYPE_OBJECT, "GTK_TYPE_OBJECT", "object" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkWindowType[] = {
  { GDK_WINDOW_ROOT, "GDK_WINDOW_ROOT", "root" },
  { GDK_WINDOW_TOPLEVEL, "GDK_WINDOW_TOPLEVEL", "toplevel" },
  { GDK_WINDOW_CHILD, "GDK_WINDOW_CHILD", "child" },
  { GDK_WINDOW_DIALOG, "GDK_WINDOW_DIALOG", "dialog" },
  { GDK_WINDOW_TEMP, "GDK_WINDOW_TEMP", "temp" },
  { GDK_WINDOW_PIXMAP, "GDK_WINDOW_PIXMAP", "pixmap" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkWindowClass[] = {
  { GDK_INPUT_OUTPUT, "GDK_INPUT_OUTPUT", "input-output" },
  { GDK_INPUT_ONLY, "GDK_INPUT_ONLY", "input-only" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkImageType[] = {
  { GDK_IMAGE_NORMAL, "GDK_IMAGE_NORMAL", "normal" },
  { GDK_IMAGE_SHARED, "GDK_IMAGE_SHARED", "shared" },
  { GDK_IMAGE_FASTEST, "GDK_IMAGE_FASTEST", "fastest" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkVisualType[] = {
  { GDK_VISUAL_STATIC_GRAY, "GDK_VISUAL_STATIC_GRAY", "static-gray" },
  { GDK_VISUAL_GRAYSCALE, "GDK_VISUAL_GRAYSCALE", "grayscale" },
  { GDK_VISUAL_STATIC_COLOR, "GDK_VISUAL_STATIC_COLOR", "static-color" },
  { GDK_VISUAL_PSEUDO_COLOR, "GDK_VISUAL_PSEUDO_COLOR", "pseudo-color" },
  { GDK_VISUAL_TRUE_COLOR, "GDK_VISUAL_TRUE_COLOR", "true-color" },
  { GDK_VISUAL_DIRECT_COLOR, "GDK_VISUAL_DIRECT_COLOR", "direct-color" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkWindowAttributesType[] = {
  { GDK_WA_TITLE, "GDK_WA_TITLE", "title" },
  { GDK_WA_X, "GDK_WA_X", "x" },
  { GDK_WA_Y, "GDK_WA_Y", "y" },
  { GDK_WA_CURSOR, "GDK_WA_CURSOR", "cursor" },
  { GDK_WA_COLORMAP, "GDK_WA_COLORMAP", "colormap" },
  { GDK_WA_VISUAL, "GDK_WA_VISUAL", "visual" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkWindowHints[] = {
  { GDK_HINT_POS, "GDK_HINT_POS", "pos" },
  { GDK_HINT_MIN_SIZE, "GDK_HINT_MIN_SIZE", "min-size" },
  { GDK_HINT_MAX_SIZE, "GDK_HINT_MAX_SIZE", "max-size" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkFunction[] = {
  { GDK_COPY, "GDK_COPY", "copy" },
  { GDK_INVERT, "GDK_INVERT", "invert" },
  { GDK_XOR, "GDK_XOR", "xor" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkFill[] = {
  { GDK_SOLID, "GDK_SOLID", "solid" },
  { GDK_TILED, "GDK_TILED", "tiled" },
  { GDK_STIPPLED, "GDK_STIPPLED", "stippled" },
  { GDK_OPAQUE_STIPPLED, "GDK_OPAQUE_STIPPLED", "opaque-stippled" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkLineStyle[] = {
  { GDK_LINE_SOLID, "GDK_LINE_SOLID", "solid" },
  { GDK_LINE_ON_OFF_DASH, "GDK_LINE_ON_OFF_DASH", "on-off-dash" },
  { GDK_LINE_DOUBLE_DASH, "GDK_LINE_DOUBLE_DASH", "double-dash" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkCapStyle[] = {
  { GDK_CAP_NOT_LAST, "GDK_CAP_NOT_LAST", "not-last" },
  { GDK_CAP_BUTT, "GDK_CAP_BUTT", "butt" },
  { GDK_CAP_ROUND, "GDK_CAP_ROUND", "round" },
  { GDK_CAP_PROJECTING, "GDK_CAP_PROJECTING", "projecting" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkJoinStyle[] = {
  { GDK_JOIN_MITER, "GDK_JOIN_MITER", "miter" },
  { GDK_JOIN_ROUND, "GDK_JOIN_ROUND", "round" },
  { GDK_JOIN_BEVEL, "GDK_JOIN_BEVEL", "bevel" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkCursorType[] = {
  { GDK_LAST_CURSOR, "GDK_LAST_CURSOR", "cursor" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkEventType[] = {
  { GDK_NOTHING, "GDK_NOTHING", "nothing" },
  { GDK_DELETE, "GDK_DELETE", "delete" },
  { GDK_DESTROY, "GDK_DESTROY", "destroy" },
  { GDK_EXPOSE, "GDK_EXPOSE", "expose" },
  { GDK_MOTION_NOTIFY, "GDK_MOTION_NOTIFY", "motion-notify" },
  { GDK_BUTTON_PRESS, "GDK_BUTTON_PRESS", "button-press" },
  { GDK_2BUTTON_PRESS, "GDK_2BUTTON_PRESS", "2button-press" },
  { GDK_3BUTTON_PRESS, "GDK_3BUTTON_PRESS", "3button-press" },
  { GDK_BUTTON_RELEASE, "GDK_BUTTON_RELEASE", "button-release" },
  { GDK_KEY_PRESS, "GDK_KEY_PRESS", "key-press" },
  { GDK_KEY_RELEASE, "GDK_KEY_RELEASE", "key-release" },
  { GDK_ENTER_NOTIFY, "GDK_ENTER_NOTIFY", "enter-notify" },
  { GDK_LEAVE_NOTIFY, "GDK_LEAVE_NOTIFY", "leave-notify" },
  { GDK_FOCUS_CHANGE, "GDK_FOCUS_CHANGE", "focus-change" },
  { GDK_CONFIGURE, "GDK_CONFIGURE", "configure" },
  { GDK_MAP, "GDK_MAP", "map" },
  { GDK_UNMAP, "GDK_UNMAP", "unmap" },
  { GDK_PROPERTY_NOTIFY, "GDK_PROPERTY_NOTIFY", "property-notify" },
  { GDK_SELECTION_CLEAR, "GDK_SELECTION_CLEAR", "selection-clear" },
  { GDK_SELECTION_REQUEST, "GDK_SELECTION_REQUEST", "selection-request" },
  { GDK_SELECTION_NOTIFY, "GDK_SELECTION_NOTIFY", "selection-notify" },
  { GDK_PROXIMITY_IN, "GDK_PROXIMITY_IN", "proximity-in" },
  { GDK_PROXIMITY_OUT, "GDK_PROXIMITY_OUT", "proximity-out" },
  { GDK_DRAG_BEGIN, "GDK_DRAG_BEGIN", "drag-begin" },
  { GDK_DRAG_REQUEST, "GDK_DRAG_REQUEST", "drag-request" },
  { GDK_DROP_ENTER, "GDK_DROP_ENTER", "drop-enter" },
  { GDK_DROP_LEAVE, "GDK_DROP_LEAVE", "drop-leave" },
  { GDK_DROP_DATA_AVAIL, "GDK_DROP_DATA_AVAIL", "drop-data-avail" },
  { GDK_CLIENT_EVENT, "GDK_CLIENT_EVENT", "client-event" },
  { GDK_VISIBILITY_NOTIFY, "GDK_VISIBILITY_NOTIFY", "visibility-notify" },
  { GDK_NO_EXPOSE, "GDK_NO_EXPOSE", "no-expose" },
  { GDK_OTHER_EVENT, "GDK_OTHER_EVENT", "other-event" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkEventMask[] = {
  { GDK_EXPOSURE_MASK, "GDK_EXPOSURE_MASK", "exposure-mask" },
  { GDK_POINTER_MOTION_MASK, "GDK_POINTER_MOTION_MASK", "pointer-motion-mask" },
  { GDK_POINTER_MOTION_HINT_MASK, "GDK_POINTER_MOTION_HINT_MASK", "pointer-motion-hint-mask" },
  { GDK_BUTTON_MOTION_MASK, "GDK_BUTTON_MOTION_MASK", "button-motion-mask" },
  { GDK_BUTTON1_MOTION_MASK, "GDK_BUTTON1_MOTION_MASK", "button1-motion-mask" },
  { GDK_BUTTON2_MOTION_MASK, "GDK_BUTTON2_MOTION_MASK", "button2-motion-mask" },
  { GDK_BUTTON3_MOTION_MASK, "GDK_BUTTON3_MOTION_MASK", "button3-motion-mask" },
  { GDK_BUTTON_PRESS_MASK, "GDK_BUTTON_PRESS_MASK", "button-press-mask" },
  { GDK_BUTTON_RELEASE_MASK, "GDK_BUTTON_RELEASE_MASK", "button-release-mask" },
  { GDK_KEY_PRESS_MASK, "GDK_KEY_PRESS_MASK", "key-press-mask" },
  { GDK_KEY_RELEASE_MASK, "GDK_KEY_RELEASE_MASK", "key-release-mask" },
  { GDK_ENTER_NOTIFY_MASK, "GDK_ENTER_NOTIFY_MASK", "enter-notify-mask" },
  { GDK_LEAVE_NOTIFY_MASK, "GDK_LEAVE_NOTIFY_MASK", "leave-notify-mask" },
  { GDK_FOCUS_CHANGE_MASK, "GDK_FOCUS_CHANGE_MASK", "focus-change-mask" },
  { GDK_STRUCTURE_MASK, "GDK_STRUCTURE_MASK", "structure-mask" },
  { GDK_PROPERTY_CHANGE_MASK, "GDK_PROPERTY_CHANGE_MASK", "property-change-mask" },
  { GDK_VISIBILITY_NOTIFY_MASK, "GDK_VISIBILITY_NOTIFY_MASK", "visibility-notify-mask" },
  { GDK_PROXIMITY_IN_MASK, "GDK_PROXIMITY_IN_MASK", "proximity-in-mask" },
  { GDK_PROXIMITY_OUT_MASK, "GDK_PROXIMITY_OUT_MASK", "proximity-out-mask" },
  { GDK_SUBSTRUCTURE_MASK, "GDK_SUBSTRUCTURE_MASK", "substructure-mask" },
  { GDK_ALL_EVENTS_MASK, "GDK_ALL_EVENTS_MASK", "all-events-mask" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkNotifyType[] = {
  { GDK_NOTIFY_ANCESTOR, "GDK_NOTIFY_ANCESTOR", "ancestor" },
  { GDK_NOTIFY_VIRTUAL, "GDK_NOTIFY_VIRTUAL", "virtual" },
  { GDK_NOTIFY_INFERIOR, "GDK_NOTIFY_INFERIOR", "inferior" },
  { GDK_NOTIFY_NONLINEAR, "GDK_NOTIFY_NONLINEAR", "nonlinear" },
  { GDK_NOTIFY_NONLINEAR_VIRTUAL, "GDK_NOTIFY_NONLINEAR_VIRTUAL", "nonlinear-virtual" },
  { GDK_NOTIFY_UNKNOWN, "GDK_NOTIFY_UNKNOWN", "unknown" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkCrossingMode[] = {
  { GDK_CROSSING_NORMAL, "GDK_CROSSING_NORMAL", "crossing-normal" },
  { GDK_CROSSING_GRAB, "GDK_CROSSING_GRAB", "crossing-grab" },
  { GDK_CROSSING_UNGRAB, "GDK_CROSSING_UNGRAB", "crossing-ungrab" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkModifierType[] = {
  { GDK_SHIFT_MASK, "GDK_SHIFT_MASK", "shift-mask" },
  { GDK_LOCK_MASK, "GDK_LOCK_MASK", "lock-mask" },
  { GDK_CONTROL_MASK, "GDK_CONTROL_MASK", "control-mask" },
  { GDK_MOD1_MASK, "GDK_MOD1_MASK", "mod1-mask" },
  { GDK_MOD2_MASK, "GDK_MOD2_MASK", "mod2-mask" },
  { GDK_MOD3_MASK, "GDK_MOD3_MASK", "mod3-mask" },
  { GDK_MOD4_MASK, "GDK_MOD4_MASK", "mod4-mask" },
  { GDK_MOD5_MASK, "GDK_MOD5_MASK", "mod5-mask" },
  { GDK_BUTTON1_MASK, "GDK_BUTTON1_MASK", "button1-mask" },
  { GDK_BUTTON2_MASK, "GDK_BUTTON2_MASK", "button2-mask" },
  { GDK_BUTTON3_MASK, "GDK_BUTTON3_MASK", "button3-mask" },
  { GDK_BUTTON4_MASK, "GDK_BUTTON4_MASK", "button4-mask" },
  { GDK_BUTTON5_MASK, "GDK_BUTTON5_MASK", "button5-mask" },
  { GDK_AFTER_MASK, "GDK_AFTER_MASK", "after-mask" },
  { GDK_MODIFIER_MASK, "GDK_MODIFIER_MASK", "modifier-mask" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkSubwindowMode[] = {
  { GDK_CLIP_BY_CHILDREN, "GDK_CLIP_BY_CHILDREN", "clip-by-children" },
  { GDK_INCLUDE_INFERIORS, "GDK_INCLUDE_INFERIORS", "include-inferiors" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkInputCondition[] = {
  { GDK_INPUT_READ, "GDK_INPUT_READ", "read" },
  { GDK_INPUT_WRITE, "GDK_INPUT_WRITE", "write" },
  { GDK_INPUT_EXCEPTION, "GDK_INPUT_EXCEPTION", "exception" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkStatus[] = {
  { GDK_OK, "GDK_OK", "ok" },
  { GDK_ERROR, "GDK_ERROR", "error" },
  { GDK_ERROR_PARAM, "GDK_ERROR_PARAM", "error-param" },
  { GDK_ERROR_FILE, "GDK_ERROR_FILE", "error-file" },
  { GDK_ERROR_MEM, "GDK_ERROR_MEM", "error-mem" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkByteOrder[] = {
  { GDK_LSB_FIRST, "GDK_LSB_FIRST", "lsb-first" },
  { GDK_MSB_FIRST, "GDK_MSB_FIRST", "msb-first" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkGCValuesMask[] = {
  { GDK_GC_FOREGROUND, "GDK_GC_FOREGROUND", "foreground" },
  { GDK_GC_BACKGROUND, "GDK_GC_BACKGROUND", "background" },
  { GDK_GC_FONT, "GDK_GC_FONT", "font" },
  { GDK_GC_FUNCTION, "GDK_GC_FUNCTION", "function" },
  { GDK_GC_FILL, "GDK_GC_FILL", "fill" },
  { GDK_GC_TILE, "GDK_GC_TILE", "tile" },
  { GDK_GC_STIPPLE, "GDK_GC_STIPPLE", "stipple" },
  { GDK_GC_CLIP_MASK, "GDK_GC_CLIP_MASK", "clip-mask" },
  { GDK_GC_SUBWINDOW, "GDK_GC_SUBWINDOW", "subwindow" },
  { GDK_GC_TS_X_ORIGIN, "GDK_GC_TS_X_ORIGIN", "ts-x-origin" },
  { GDK_GC_TS_Y_ORIGIN, "GDK_GC_TS_Y_ORIGIN", "ts-y-origin" },
  { GDK_GC_CLIP_X_ORIGIN, "GDK_GC_CLIP_X_ORIGIN", "clip-x-origin" },
  { GDK_GC_CLIP_Y_ORIGIN, "GDK_GC_CLIP_Y_ORIGIN", "clip-y-origin" },
  { GDK_GC_EXPOSURES, "GDK_GC_EXPOSURES", "exposures" },
  { GDK_GC_LINE_WIDTH, "GDK_GC_LINE_WIDTH", "line-width" },
  { GDK_GC_LINE_STYLE, "GDK_GC_LINE_STYLE", "line-style" },
  { GDK_GC_CAP_STYLE, "GDK_GC_CAP_STYLE", "cap-style" },
  { GDK_GC_JOIN_STYLE, "GDK_GC_JOIN_STYLE", "join-style" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkSelection[] = {
  { GDK_SELECTION_PRIMARY, "GDK_SELECTION_PRIMARY", "primary" },
  { GDK_SELECTION_SECONDARY, "GDK_SELECTION_SECONDARY", "secondary" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkPropertyState[] = {
  { GDK_PROPERTY_NEW_VALUE, "GDK_PROPERTY_NEW_VALUE", "new-value" },
  { GDK_PROPERTY_DELETE, "GDK_PROPERTY_DELETE", "delete" },
  { 0, NULL, NULL },
};
static GtkEnumValue enum_values_GdkPropMode[] = {
  { GDK_PROP_MODE_REPLACE, "GDK_PROP_MODE_REPLACE", "replace" },
  { GDK_PROP_MODE_PREPEND, "GDK_PROP_MODE_PREPEND", "prepend" },
  { GDK_PROP_MODE_APPEND, "GDK_PROP_MODE_APPEND", "append" },
  { 0, NULL, NULL },
};
