/* Generated by gen-paper-names */

#if 0
NC_("paper size", "asme_f")
NC_("paper size", "A0×2")
NC_("paper size", "A0")
NC_("paper size", "A0×3")
NC_("paper size", "A1")
NC_("paper size", "A10")
NC_("paper size", "A1×3")
NC_("paper size", "A1×4")
NC_("paper size", "A2")
NC_("paper size", "A2×3")
NC_("paper size", "A2×4")
NC_("paper size", "A2×5")
NC_("paper size", "A3")
NC_("paper size", "A3 Extra")
NC_("paper size", "A3×3")
NC_("paper size", "A3×4")
NC_("paper size", "A3×5")
NC_("paper size", "A3×6")
NC_("paper size", "A3×7")
NC_("paper size", "A4")
NC_("paper size", "A4 Extra")
NC_("paper size", "A4 Tab")
NC_("paper size", "A4×3")
NC_("paper size", "A4×4")
NC_("paper size", "A4×5")
NC_("paper size", "A4×6")
NC_("paper size", "A4×7")
NC_("paper size", "A4×8")
NC_("paper size", "A4×9")
NC_("paper size", "A5")
NC_("paper size", "A5 Extra")
NC_("paper size", "A6")
NC_("paper size", "A7")
NC_("paper size", "A8")
NC_("paper size", "A9")
NC_("paper size", "B0")
NC_("paper size", "B1")
NC_("paper size", "B10")
NC_("paper size", "B2")
NC_("paper size", "B3")
NC_("paper size", "B4")
NC_("paper size", "B5")
NC_("paper size", "B5 Extra")
NC_("paper size", "B6")
NC_("paper size", "B6/C4")
NC_("paper size", "B7")
NC_("paper size", "B8")
NC_("paper size", "B9")
NC_("paper size", "C0")
NC_("paper size", "C1")
NC_("paper size", "C10")
NC_("paper size", "C2")
NC_("paper size", "C3")
NC_("paper size", "C4")
NC_("paper size", "C5")
NC_("paper size", "C6")
NC_("paper size", "C6/C5")
NC_("paper size", "C7")
NC_("paper size", "C7/C6")
NC_("paper size", "C8")
NC_("paper size", "C9")
NC_("paper size", "DL Envelope")
NC_("paper size", "RA0")
NC_("paper size", "RA1")
NC_("paper size", "RA2")
NC_("paper size", "RA3")
NC_("paper size", "RA4")
NC_("paper size", "SRA0")
NC_("paper size", "SRA1")
NC_("paper size", "SRA2")
NC_("paper size", "SRA3")
NC_("paper size", "SRA4")
NC_("paper size", "JB0")
NC_("paper size", "JB1")
NC_("paper size", "JB10")
NC_("paper size", "JB2")
NC_("paper size", "JB3")
NC_("paper size", "JB4")
NC_("paper size", "JB5")
NC_("paper size", "JB6")
NC_("paper size", "JB7")
NC_("paper size", "JB8")
NC_("paper size", "JB9")
NC_("paper size", "jis exec")
NC_("paper size", "Choukei 2 Envelope")
NC_("paper size", "Choukei 3 Envelope")
NC_("paper size", "Choukei 4 Envelope")
NC_("paper size", "Choukei 40 Envelope")
NC_("paper size", "hagaki (postcard)")
NC_("paper size", "kahu Envelope")
NC_("paper size", "kaku2 Envelope")
NC_("paper size", "kaku3 Envelope")
NC_("paper size", "kaku4 Envelope")
NC_("paper size", "kaku5 Envelope")
NC_("paper size", "kaku7 Envelope")
NC_("paper size", "kaku8 Envelope")
NC_("paper size", "oufuku (reply postcard)")
NC_("paper size", "you4 Envelope")
NC_("paper size", "you6 Envelope")
NC_("paper size", "10×11")
NC_("paper size", "10×13")
NC_("paper size", "10×14")
NC_("paper size", "10×15")
NC_("paper size", "11×12")
NC_("paper size", "11×15")
NC_("paper size", "12×19")
NC_("paper size", "5×7")
NC_("paper size", "6×9 Envelope")
NC_("paper size", "7×9 Envelope")
NC_("paper size", "8×10 Envelope")
NC_("paper size", "9×11 Envelope")
NC_("paper size", "9×12 Envelope")
NC_("paper size", "a2 Envelope")
NC_("paper size", "Arch A")
NC_("paper size", "Arch B")
NC_("paper size", "Arch C")
NC_("paper size", "Arch D")
NC_("paper size", "Arch E")
NC_("paper size", "b-plus")
NC_("paper size", "c")
NC_("paper size", "c5 Envelope")
NC_("paper size", "d")
NC_("paper size", "e")
NC_("paper size", "edp")
NC_("paper size", "European edp")
NC_("paper size", "Executive")
NC_("paper size", "f")
NC_("paper size", "Fan-Fold European")
NC_("paper size", "Fan-Fold US")
NC_("paper size", "Fan-Fold German Legal")
NC_("paper size", "Government Legal")
NC_("paper size", "Government Letter")
NC_("paper size", "Index 3×5")
NC_("paper size", "Index 4×6 (postcard)")
NC_("paper size", "Index 4×6 ext")
NC_("paper size", "Index 5×8")
NC_("paper size", "Invoice")
NC_("paper size", "Tabloid")
NC_("paper size", "US Legal")
NC_("paper size", "US Legal Extra")
NC_("paper size", "US Letter")
NC_("paper size", "US Letter Extra")
NC_("paper size", "US Letter Plus")
NC_("paper size", "Monarch Envelope")
NC_("paper size", "#10 Envelope")
NC_("paper size", "#11 Envelope")
NC_("paper size", "#12 Envelope")
NC_("paper size", "#14 Envelope")
NC_("paper size", "#9 Envelope")
NC_("paper size", "Oficio")
NC_("paper size", "Personal Envelope")
NC_("paper size", "Quarto")
NC_("paper size", "Super A")
NC_("paper size", "Super B")
NC_("paper size", "Wide Format")
NC_("paper size", "Photo L")
NC_("paper size", "Dai-pa-kai")
NC_("paper size", "Folio")
NC_("paper size", "Folio sp")
NC_("paper size", "Invite Envelope")
NC_("paper size", "Italian Envelope")
NC_("paper size", "juuro-ku-kai")
NC_("paper size", "Large Photo")
NC_("paper size", "Medium Photo")
NC_("paper size", "pa-kai")
NC_("paper size", "Postfix Envelope")
NC_("paper size", "Small Photo")
NC_("paper size", "Wide Photo")
NC_("paper size", "prc1 Envelope")
NC_("paper size", "prc10 Envelope")
NC_("paper size", "prc 16k")
NC_("paper size", "prc2 Envelope")
NC_("paper size", "prc3 Envelope")
NC_("paper size", "prc 32k")
NC_("paper size", "prc4 Envelope")
NC_("paper size", "prc5 Envelope")
NC_("paper size", "prc6 Envelope")
NC_("paper size", "prc7 Envelope")
NC_("paper size", "prc8 Envelope")
NC_("paper size", "prc9 Envelope")
NC_("paper size", "ROC 16k")
NC_("paper size", "ROC 8k")
#endif

static const char paper_names[] =
  "asme_f\0"
  "iso_2a0\0"
  "A0×2\0"
  "iso_a0\0"
  "iso_a0x3\0"
  "A0×3\0"
  "iso_a1\0"
  "iso_a10\0"
  "A10\0"
  "iso_a1x3\0"
  "A1×3\0"
  "iso_a1x4\0"
  "A1×4\0"
  "iso_a2\0"
  "iso_a2x3\0"
  "A2×3\0"
  "iso_a2x4\0"
  "A2×4\0"
  "iso_a2x5\0"
  "A2×5\0"
  "iso_a3\0"
  "iso_a3-extra\0"
  "A3 Extra\0"
  "A3Extra\0"
  "iso_a3x3\0"
  "A3×3\0"
  "iso_a3x4\0"
  "A3×4\0"
  "iso_a3x5\0"
  "A3×5\0"
  "iso_a3x6\0"
  "A3×6\0"
  "iso_a3x7\0"
  "A3×7\0"
  "iso_a4\0"
  "iso_a4-extra\0"
  "A4 Extra\0"
  "A4Extra\0"
  "iso_a4-tab\0"
  "A4 Tab\0"
  "A4Tab\0"
  "iso_a4x3\0"
  "A4×3\0"
  "iso_a4x4\0"
  "A4×4\0"
  "iso_a4x5\0"
  "A4×5\0"
  "iso_a4x6\0"
  "A4×6\0"
  "iso_a4x7\0"
  "A4×7\0"
  "iso_a4x8\0"
  "A4×8\0"
  "iso_a4x9\0"
  "A4×9\0"
  "iso_a5\0"
  "A5\0"
  "iso_a5-extra\0"
  "A5 Extra\0"
  "A5Extra\0"
  "iso_a6\0"
  "A6\0"
  "iso_a7\0"
  "A7\0"
  "iso_a8\0"
  "A8\0"
  "iso_a9\0"
  "A9\0"
  "iso_b0\0"
  "ISOB0\0"
  "iso_b1\0"
  "ISOB1\0"
  "iso_b10\0"
  "ISOB10\0"
  "iso_b2\0"
  "ISOB2\0"
  "iso_b3\0"
  "ISOB3\0"
  "iso_b4\0"
  "ISOB4\0"
  "iso_b5\0"
  "ISOB5\0"
  "iso_b5-extra\0"
  "B5 Extra\0"
  "ISOB5Extra\0"
  "iso_b6\0"
  "ISOB6\0"
  "iso_b6c4\0"
  "B6/C4\0"
  "iso_b7\0"
  "ISOB7\0"
  "iso_b8\0"
  "ISOB8\0"
  "iso_b9\0"
  "ISOB9\0"
  "iso_c0\0"
  "EnvC0\0"
  "iso_c1\0"
  "EnvC1\0"
  "iso_c10\0"
  "EnvC10\0"
  "iso_c2\0"
  "EnvC2\0"
  "iso_c3\0"
  "EnvC3\0"
  "iso_c4\0"
  "EnvC4\0"
  "iso_c5\0"
  "EnvC5\0"
  "iso_c6\0"
  "EnvC6\0"
  "iso_c6c5\0"
  "C6/C5\0"
  "EnvC65\0"
  "iso_c7\0"
  "EnvC7\0"
  "iso_c7c6\0"
  "C7/C6\0"
  "iso_c8\0"
  "EnvC8\0"
  "iso_c9\0"
  "EnvC9\0"
  "iso_dl\0"
  "DL Envelope\0"
  "EnvDL\0"
  "iso_ra0\0"
  "iso_ra1\0"
  "iso_ra2\0"
  "iso_ra3\0"
  "iso_ra4\0"
  "iso_sra0\0"
  "SRA0\0"
  "iso_sra1\0"
  "SRA1\0"
  "iso_sra2\0"
  "SRA2\0"
  "iso_sra3\0"
  "SRA3\0"
  "iso_sra4\0"
  "SRA4\0"
  "jis_b0\0"
  "JB0\0"
  "jis_b1\0"
  "JB1\0"
  "jis_b10\0"
  "JB10\0"
  "jis_b2\0"
  "JB2\0"
  "jis_b3\0"
  "JB3\0"
  "jis_b4\0"
  "JB4\0"
  "jis_b5\0"
  "JB5\0"
  "jis_b6\0"
  "JB6\0"
  "jis_b7\0"
  "JB7\0"
  "jis_b8\0"
  "JB8\0"
  "jis_b9\0"
  "JB9\0"
  "jis_exec\0"
  "jis exec\0"
  "jpn_chou2\0"
  "Choukei 2 Envelope\0"
  "jpn_chou3\0"
  "Choukei 3 Envelope\0"
  "EnvChou3\0"
  "jpn_chou4\0"
  "Choukei 4 Envelope\0"
  "EnvChou4\0"
  "jpn_chou40\0"
  "Choukei 40 Envelope\0"
  "EnvChou40\0"
  "jpn_hagaki\0"
  "hagaki (postcard)\0"
  "jpn_kahu\0"
  "kahu Envelope\0"
  "jpn_kaku2\0"
  "kaku2 Envelope\0"
  "EnvKaku2\0"
  "jpn_kaku3\0"
  "kaku3 Envelope\0"
  "EnvKaku3\0"
  "jpn_kaku4\0"
  "kaku4 Envelope\0"
  "EnvKaku4\0"
  "jpn_kaku5\0"
  "kaku5 Envelope\0"
  "EnvKaku5\0"
  "jpn_kaku7\0"
  "kaku7 Envelope\0"
  "EnvKaku7\0"
  "jpn_kaku8\0"
  "kaku8 Envelope\0"
  "EnvKaku8\0"
  "jpn_oufuku\0"
  "oufuku (reply postcard)\0"
  "DoublePostcard\0"
  "jpn_you4\0"
  "you4 Envelope\0"
  "EnvYou4\0"
  "jpn_you6\0"
  "you6 Envelope\0"
  "EnvYou6\0"
  "na_10x11\0"
  "10×11\0"
  "na_10x13\0"
  "10×13\0"
  "na_10x14\0"
  "10×14\0"
  "na_10x15\0"
  "10×15\0"
  "na_11x12\0"
  "11×12\0"
  "12x11\0"
  "na_11x15\0"
  "11×15\0"
  "15x11\0"
  "na_12x19\0"
  "12×19\0"
  "na_5x7\0"
  "5×7\0"
  "na_6x9\0"
  "6×9 Envelope\0"
  "na_7x9\0"
  "7×9 Envelope\0"
  "na_8x10\0"
  "8×10 Envelope\0"
  "na_9x11\0"
  "9×11 Envelope\0"
  "na_9x12\0"
  "9×12 Envelope\0"
  "na_a2\0"
  "a2 Envelope\0"
  "EnvA2\0"
  "na_arch-a\0"
  "Arch A\0"
  "ARCHA\0"
  "na_arch-b\0"
  "Arch B\0"
  "ARCHB\0"
  "na_arch-c\0"
  "Arch C\0"
  "ARCHC\0"
  "na_arch-d\0"
  "Arch D\0"
  "ARCHD\0"
  "na_arch-e\0"
  "Arch E\0"
  "ARCHE\0"
  "na_b-plus\0"
  "SuperB\0"
  "na_c\0"
  "AnsiC\0"
  "na_c5\0"
  "6.5x9.5\0"
  "na_d\0"
  "AnsiD\0"
  "na_e\0"
  "AnsiE\0"
  "na_edp\0"
  "11x14\0"
  "na_eur-edp\0"
  "European edp\0"
  "na_executive\0"
  "Executive\0"
  "na_f\0"
  "AnsiF\0"
  "na_fanfold-eur\0"
  "Fan-Fold European\0"
  "FanFoldGerman\0"
  "na_fanfold-us\0"
  "Fan-Fold US\0"
  "FanFoldUS\0"
  "na_foolscap\0"
  "Fan-Fold German Legal\0"
  "FanFoldGermanLegal\0"
  "na_govt-legal\0"
  "Government Legal\0"
  "8x13\0"
  "na_govt-letter\0"
  "Government Letter\0"
  "na_index-3x5\0"
  "Index 3×5\0"
  "na_index-4x6\0"
  "Index 4×6 (postcard)\0"
  "na_index-4x6-ext\0"
  "Index 4×6 ext\0"
  "na_index-5x8\0"
  "Index 5×8\0"
  "na_invoice\0"
  "Invoice\0"
  "Statement\0"
  "na_ledger\0"
  "Tabloid\0"
  "Ledger\0"
  "na_legal\0"
  "US Legal\0"
  "na_legal-extra\0"
  "US Legal Extra\0"
  "LegalExtra\0"
  "na_letter\0"
  "US Letter\0"
  "na_letter-extra\0"
  "US Letter Extra\0"
  "LetterExtra\0"
  "na_letter-plus\0"
  "US Letter Plus\0"
  "LetterPlus\0"
  "na_monarch\0"
  "Monarch Envelope\0"
  "EnvMonarch\0"
  "na_number-10\0"
  "#10 Envelope\0"
  "Env10\0"
  "na_number-11\0"
  "#11 Envelope\0"
  "Env11\0"
  "na_number-12\0"
  "#12 Envelope\0"
  "Env12\0"
  "na_number-14\0"
  "#14 Envelope\0"
  "Env14\0"
  "na_number-9\0"
  "#9 Envelope\0"
  "Env9\0"
  "na_oficio\0"
  "Oficio\0"
  "na_personal\0"
  "Personal Envelope\0"
  "EnvPersonal\0"
  "na_quarto\0"
  "Quarto\0"
  "na_super-a\0"
  "Super A\0"
  "SuperA\0"
  "na_super-b\0"
  "Super B\0"
  "na_wide-format\0"
  "Wide Format\0"
  "oe_photo-l\0"
  "Photo L\0"
  "3.5x5\0"
  "om_dai-pa-kai\0"
  "Dai-pa-kai\0"
  "om_folio\0"
  "Folio\0"
  "om_folio-sp\0"
  "Folio sp\0"
  "FolioSP\0"
  "om_invite\0"
  "Invite Envelope\0"
  "EnvInvite\0"
  "om_italian\0"
  "Italian Envelope\0"
  "EnvItalian\0"
  "om_juuro-ku-kai\0"
  "om_large-photo\0"
  "Large Photo\0"
  "om_medium-photo\0"
  "Medium Photo\0"
  "om_pa-kai\0"
  "om_postfix\0"
  "Postfix Envelope\0"
  "om_small-photo\0"
  "Small Photo\0"
  "om_wide-photo\0"
  "Wide Photo\0"
  "prc_1\0"
  "prc1 Envelope\0"
  "EnvPRC1\0"
  "prc_10\0"
  "prc10 Envelope\0"
  "EnvPRC10\0"
  "prc_16k\0"
  "prc 16k\0"
  "PRC16K\0"
  "prc_2\0"
  "prc2 Envelope\0"
  "EnvPRC2\0"
  "prc_3\0"
  "prc3 Envelope\0"
  "EnvPRC3\0"
  "prc_32k\0"
  "prc 32k\0"
  "PRC32K\0"
  "prc_4\0"
  "prc4 Envelope\0"
  "EnvPRC4\0"
  "prc_5\0"
  "prc5 Envelope\0"
  "EnvPRC5\0"
  "prc_6\0"
  "prc6 Envelope\0"
  "EnvPRC6\0"
  "prc_7\0"
  "prc7 Envelope\0"
  "EnvPRC7\0"
  "prc_8\0"
  "prc8 Envelope\0"
  "EnvPRC8\0"
  "prc_9\0"
  "prc9 Envelope\0"
  "EnvPRC9\0"
  "roc_16k\0"
  "ROC 16k\0"
  "roc16k\0"
  "roc_8k\0"
  "ROC 8k\0"
  "roc8k\0"
  "Comm10\0";

typedef struct {
  int name;
  float width;
  float height;
  int display_name;
  int ppd_name;
} PaperInfo;

static const PaperInfo standard_names_offsets[] = {
  {    0, 711.2, 1016,    0,   -1 },
  {    7, 1189, 1682,   15,   -1 },
  {   21, 841, 1189,  953,  953 },
  {   28, 1189, 2523,   37,   -1 },
  {   43, 594, 841,  967,  967 },
  {   50, 26, 37,   58,   58 },
  {   62, 841, 1783,   71,   -1 },
  {   77, 841, 2378,   86,   -1 },
  {   92, 420, 594,  981,  981 },
  {   99, 594, 1261,  108,   -1 },
  {  114, 594, 1682,  123,   -1 },
  {  129, 594, 2102,  138,   -1 },
  {  144, 297, 420,  995,  995 },
  {  151, 322, 445,  164,  173 },
  {  181, 420, 891,  190,   -1 },
  {  196, 420, 1189,  205,   -1 },
  {  211, 420, 1486,  220,   -1 },
  {  226, 420, 1783,  235,   -1 },
  {  241, 420, 2080,  250,   -1 },
  {  256, 210, 297, 1009, 1009 },
  {  263, 235.5, 322.3,  276,  285 },
  {  293, 225, 297,  304,  311 },
  {  317, 297, 630,  326,   -1 },
  {  332, 297, 841,  341,   -1 },
  {  347, 297, 1051,  356,   -1 },
  {  362, 297, 1261,  371,   -1 },
  {  377, 297, 1471,  386,   -1 },
  {  392, 297, 1682,  401,   -1 },
  {  407, 297, 1892,  416,   -1 },
  {  422, 148, 210,  429,  429 },
  {  432, 174, 235,  445,  454 },
  {  462, 105, 148,  469,  469 },
  {  472, 74, 105,  479,  479 },
  {  482, 52, 74,  489,  489 },
  {  492, 37, 52,  499,  499 },
  {  502, 1000, 1414,  512,  509 },
  {  515, 707, 1000,  525,  522 },
  {  528, 31, 44,  539,  536 },
  {  543, 500, 707,  553,  550 },
  {  556, 353, 500,  566,  563 },
  {  569, 250, 353,  579,  576 },
  {  582, 176, 250,  592,  589 },
  {  595, 201, 276,  608,  617 },
  {  628, 125, 176,  638,  635 },
  {  641, 125, 324,  650,   -1 },
  {  656, 88, 125,  666,  663 },
  {  669, 62, 88,  679,  676 },
  {  682, 44, 62,  692,  689 },
  {  695, 917, 1297,  705,  702 },
  {  708, 648, 917,  718,  715 },
  {  721, 28, 40,  732,  729 },
  {  736, 458, 648,  746,  743 },
  {  749, 324, 458,  759,  756 },
  {  762, 229, 324,  653,  769 },
  {  775, 162, 229,  785,  782 },
  {  788, 114, 162,  798,  795 },
  {  801, 114, 229,  810,  816 },
  {  823, 81, 114,  833,  830 },
  {  836, 81, 162,  845,   -1 },
  {  851, 57, 81,  861,  858 },
  {  864, 40, 57,  874,  871 },
  {  877, 110, 220,  884,  896 },
  {  902, 860, 1220,  952,   -1 },
  {  910, 610, 860,  966,   -1 },
  {  918, 430, 610,  980,   -1 },
  {  926, 305, 430,  994,   -1 },
  {  934, 215, 305, 1008,   -1 },
  {  942, 900, 1280,  951,   -1 },
  {  956, 640, 900,  965,   -1 },
  {  970, 450, 640,  979,   -1 },
  {  984, 320, 450,  993,   -1 },
  {  998, 225, 320, 1007,   -1 },
  { 1012, 1030, 1456, 1019,  512 },
  { 1023, 728, 1030, 1030,  525 },
  { 1034, 32, 45, 1042,  539 },
  { 1047, 515, 728, 1054,  553 },
  { 1058, 364, 515, 1065,  566 },
  { 1069, 257, 364, 1076,  579 },
  { 1080, 182, 257, 1087,  592 },
  { 1091, 128, 182, 1098,  638 },
  { 1102, 91, 128, 1109,  666 },
  { 1113, 64, 91, 1120,  679 },
  { 1124, 45, 64, 1131,  692 },
  { 1135, 216, 330, 1144,   -1 },
  { 1153, 111.1, 146, 1163,   -1 },
  { 1182, 120, 235, 1192, 1211 },
  { 1220, 90, 205, 1230, 1249 },
  { 1258, 90, 225, 1269, 1289 },
  { 1299, 100, 148, 1310, 1596 },
  { 1328, 240, 322.1, 1337,   -1 },
  { 1351, 240, 332, 1361, 1376 },
  { 1385, 216, 277, 1395, 1410 },
  { 1419, 197, 267, 1429, 1444 },
  { 1453, 190, 240, 1463, 1478 },
  { 1487, 142, 205, 1497, 1512 },
  { 1521, 119, 197, 1531, 1546 },
  { 1555, 148, 200, 1566, 1590 },
  { 1605, 105, 235, 1614, 1628 },
  { 1636, 98, 190, 1645, 1659 },
  { 1667, 254, 279.4, 1676, 1670 },
  { 1683, 254, 330.2, 1692, 1686 },
  { 1699, 254, 355.6, 1708, 1702 },
  { 1715, 254, 381, 1724, 1718 },
  { 1731, 279.4, 304.8, 1740, 1747 },
  { 1753, 279.4, 381, 1762, 1769 },
  { 1775, 304.8, 482.6, 1784, 1778 },
  { 1791, 127, 177.8, 1798, 1794 },
  { 1803, 152.4, 228.6, 1810, 1806 },
  { 1824, 177.8, 228.6, 1831, 1827 },
  { 1845, 203.2, 254, 1853, 1848 },
  { 1868, 228.6, 279.4, 1876, 1871 },
  { 1891, 228.6, 304.8, 1899, 1894 },
  { 1914, 111.125, 146.05, 1920, 1932 },
  { 1938, 228.6, 304.8, 1948, 1955 },
  { 1961, 304.8, 457.2, 1971, 1978 },
  { 1984, 457.2, 609.6, 1994, 2001 },
  { 2007, 609.6, 914.4, 2017, 2024 },
  { 2030, 914.4, 1219.2, 2040, 2047 },
  { 2053, 304.8, 486.918, 2056, 2063 },
  { 2070, 431.8, 558.8, 1142, 2075 },
  { 2081, 165.1, 241.3, 3598, 2087 },
  { 2095, 558.8, 863.6, 1603, 2100 },
  { 2106, 863.6, 1117.6,  894, 2111 },
  { 2117, 279.4, 355.6, 2120, 2124 },
  { 2130, 304.8, 355.6, 2141,   -1 },
  { 2154, 184.15, 266.7, 2167, 2167 },
  { 2177, 1117.6, 1727.2,    5, 2182 },
  { 2188, 215.9, 304.8, 2203, 2221 },
  { 2235, 279.4, 377.825, 2249, 2261 },
  { 2271, 215.9, 330.2, 2283, 2305 },
  { 2324, 203.2, 330.2, 2338, 2355 },
  { 2360, 203.2, 254, 2375, 1848 },
  { 2393, 76.2, 127, 2406,  216 },
  { 2417, 101.6, 152.4, 2430,  367 },
  { 2452, 152.4, 203.2, 2469,   -1 },
  { 2484, 127, 203.2, 2497, 2493 },
  { 2508, 139.7, 215.9, 2519, 2527 },
  { 2537, 279.4, 431.8, 2547, 2555 },
  { 2562, 215.9, 355.6, 2571, 2299 },
  { 2580, 241.3, 381, 2595, 2610 },
  { 2621, 215.9, 279.4, 2631, 2386 },
  { 2641, 241.3, 304.8, 2657, 2673 },
  { 2685, 215.9, 322.326, 2700, 2715 },
  { 2726, 98.425, 190.5, 2737, 2754 },
  { 2765, 104.775, 241.3, 2778, 2791 },
  { 2797, 114.3, 263.525, 2810, 2823 },
  { 2829, 120.65, 279.4, 2842, 2855 },
  { 2861, 127, 292.1, 2874, 2887 },
  { 2893, 98.425, 225.425, 2905, 2917 },
  { 2922, 215.9, 340.36, 2932, 2932 },
  { 2939, 92.075, 165.1, 2951, 2969 },
  { 2981, 215.9, 275.082, 2991, 2991 },
  { 2998, 227.076, 355.6, 3009, 3017 },
  { 3024, 330.2, 482.6, 3035, 2063 },
  { 3043, 762, 1066.8, 3058,   -1 },
  { 3070, 88.9, 127, 3081, 3089 },
  { 3095, 275, 395, 3109,   -1 },
  { 3120, 210, 330, 3129, 3129 },
  { 3135, 215, 315, 3147, 3156 },
  { 3164, 220, 220, 3174, 3190 },
  { 3200, 110, 230, 3211, 3228 },
  { 3239, 198, 275, 3242,   -1 },
  { 3255, 200, 300, 3270, 3255 },
  { 3282, 130, 180, 3298,   -1 },
  { 3311, 267, 389, 3102,   -1 },
  { 3321, 114, 229, 3332,   -1 },
  { 3349, 100, 150, 3364, 3349 },
  { 3376, 100, 200, 3390, 3376 },
  { 3401, 102, 165, 3407, 3421 },
  { 3429, 324, 458, 3436, 3451 },
  { 3460, 146, 215, 3468, 3476 },
  { 3483, 102, 176, 3489, 3503 },
  { 3511, 125, 176, 3517, 3531 },
  { 3539, 97, 151, 3547, 3555 },
  { 3562, 110, 208, 3568, 3582 },
  { 3590, 110, 220, 3596, 3610 },
  { 3618, 120, 230, 3624, 3638 },
  { 3646, 160, 230, 3652, 3666 },
  { 3674, 120, 309, 3680, 3694 },
  { 3702, 229, 324, 3708, 3722 },
  { 3730, 196.85, 273.05, 3738, 3746 },
  { 3753, 273.05, 393.7, 3760, 3767 },
};

static const struct {
  int ppd_name;
  int standard_name;
} extra_ppd_names_offsets[] = {
  {  653,  762 },
  {  785,  775 },
  {  798,  788 },
  { 3773, 2765 },
  {  899,  877 },
  { 2757, 2726 },
};

