/* Generated by gen-paper-names */

#if 0
N_("asme_f")
N_("A0x2")
N_("A0")
N_("A0x3")
N_("A1")
N_("A10")
N_("A1x3")
N_("A1x4")
N_("A2")
N_("A2x3")
N_("A2x4")
N_("A2x5")
N_("A3")
N_("A3 Extra")
N_("A3x3")
N_("A3x4")
N_("A3x5")
N_("A3x6")
N_("A3x7")
N_("A4")
N_("A4 Extra")
N_("A4 Tab")
N_("A4x3")
N_("A4x4")
N_("A4x5")
N_("A4x6")
N_("A4x7")
N_("A4x8")
N_("A4x9")
N_("A5")
N_("A5 Extra")
N_("A6")
N_("A7")
N_("A8")
N_("A9")
N_("B0")
N_("B1")
N_("B10")
N_("B2")
N_("B3")
N_("B4")
N_("B5")
N_("B5 Extra")
N_("B6")
N_("B6/C4")
N_("B7")
N_("B8")
N_("B9")
N_("C0")
N_("C1")
N_("C10")
N_("C2")
N_("C3")
N_("C4")
N_("C5")
N_("C6")
N_("C6/C5")
N_("C7")
N_("C7/C6")
N_("C8")
N_("C9")
N_("DL Envelope")
N_("RA0")
N_("RA1")
N_("RA2")
N_("SRA0")
N_("SRA1")
N_("SRA2")
N_("JB0")
N_("JB1")
N_("JB10")
N_("JB2")
N_("JB3")
N_("JB4")
N_("JB5")
N_("JB6")
N_("JB7")
N_("JB8")
N_("JB9")
N_("jis exec")
N_("Choukei 2 Envelope")
N_("Choukei 3 Envelope")
N_("Choukei 4 Envelope")
N_("hagaki (postcard)")
N_("kahu Envelope")
N_("kaku2 Envelope")
N_("oufuku (reply postcard)")
N_("you4 Envelope")
N_("10x11")
N_("10x13")
N_("10x14")
N_("10x15")
N_("10x15")
N_("11x12")
N_("11x15")
N_("12x19")
N_("5x7")
N_("6x9 Envelope")
N_("7x9 Envelope")
N_("9x11 Envelope")
N_("a2 Envelope")
N_("Arch A")
N_("Arch B")
N_("Arch C")
N_("Arch D")
N_("Arch E")
N_("b-plus")
N_("c")
N_("c5 Envelope")
N_("d")
N_("e")
N_("edp")
N_("European edp")
N_("Executive")
N_("f")
N_("FanFold European")
N_("FanFold US")
N_("FanFold German Legal")
N_("Government Legal")
N_("Government Letter")
N_("Index 3x5")
N_("Index 4x6 (postcard)")
N_("Index 4x6 ext")
N_("Index 5x8")
N_("Invoice")
N_("Tabloid")
N_("US Legal")
N_("US Legal Extra")
N_("US Letter")
N_("US Letter Extra")
N_("US Letter Plus")
N_("Monarch Envelope")
N_("#10 Envelope")
N_("#11 Eenvelope")
N_("#12 Envelope")
N_("#14 Envelope")
N_("#9 Envelope")
N_("Personal Envelope")
N_("Quarto")
N_("Super A")
N_("Super B")
N_("Wide Format")
N_("Dai-pa-kai")
N_("Folio")
N_("Folio sp")
N_("Invite Envelope")
N_("Italian Envelope")
N_("juuro-ku-kai")
N_("pa-kai")
N_("Postfix Envelope")
N_("Small Photo")
N_("prc1 Envelope")
N_("prc10 Envelope")
N_("prc 16k")
N_("prc2 Envelope")
N_("prc3 Envelope")
N_("prc 32k")
N_("prc4 Envelope")
N_("prc5 Envelope")
N_("prc6 Envelope")
N_("prc7 Envelope")
N_("prc8 Envelope")
N_("ROC 16k")
N_("ROC 8k")
#endif

const char paper_names[] =
  "asme_f\0"
  "iso_2a0\0"
  "A0x2\0"
  "iso_a0\0"
  "iso_a0x3\0"
  "A0x3\0"
  "iso_a1\0"
  "iso_a10\0"
  "A10\0"
  "iso_a1x3\0"
  "A1x3\0"
  "iso_a1x4\0"
  "A1x4\0"
  "iso_a2\0"
  "iso_a2x3\0"
  "A2x3\0"
  "iso_a2x4\0"
  "A2x4\0"
  "iso_a2x5\0"
  "A2x5\0"
  "iso_a3\0"
  "A3\0"
  "iso_a3-extra\0"
  "A3 Extra\0"
  "A3Extra\0"
  "iso_a3x3\0"
  "A3x3\0"
  "iso_a3x4\0"
  "A3x4\0"
  "iso_a3x5\0"
  "A3x5\0"
  "iso_a3x6\0"
  "A3x6\0"
  "iso_a3x7\0"
  "A3x7\0"
  "iso_a4\0"
  "A4\0"
  "iso_a4-extra\0"
  "A4 Extra\0"
  "A4Extra\0"
  "iso_a4-tab\0"
  "A4 Tab\0"
  "iso_a4x3\0"
  "A4x3\0"
  "iso_a4x4\0"
  "A4x4\0"
  "iso_a4x5\0"
  "A4x5\0"
  "iso_a4x6\0"
  "A4x6\0"
  "iso_a4x7\0"
  "A4x7\0"
  "iso_a4x8\0"
  "A4x8\0"
  "iso_a4x9\0"
  "A4x9\0"
  "iso_a5\0"
  "A5\0"
  "iso_a5-extra\0"
  "A5 Extra\0"
  "A5Extra\0"
  "iso_a6\0"
  "A6\0"
  "iso_a7\0"
  "A7\0"
  "iso_a8\0"
  "A8\0"
  "iso_a9\0"
  "A9\0"
  "iso_b0\0"
  "ISOB0\0"
  "iso_b1\0"
  "ISOB1\0"
  "iso_b10\0"
  "ISOB10\0"
  "iso_b2\0"
  "ISOB2\0"
  "iso_b3\0"
  "ISOB3\0"
  "iso_b4\0"
  "ISOB4\0"
  "iso_b5\0"
  "ISOB5\0"
  "iso_b5-extra\0"
  "B5 Extra\0"
  "ISOB5Extra\0"
  "iso_b6\0"
  "ISOB6\0"
  "iso_b6c4\0"
  "B6/C4\0"
  "iso_b7\0"
  "ISOB7\0"
  "iso_b8\0"
  "ISOB8\0"
  "iso_b9\0"
  "ISOB9\0"
  "iso_c0\0"
  "EnvC0\0"
  "iso_c1\0"
  "EnvC1\0"
  "iso_c10\0"
  "EnvC10\0"
  "iso_c2\0"
  "EnvC2\0"
  "iso_c3\0"
  "EnvC3\0"
  "iso_c4\0"
  "EnvC4\0"
  "iso_c5\0"
  "EnvC5\0"
  "iso_c6\0"
  "EnvC6\0"
  "iso_c6c5\0"
  "C6/C5\0"
  "EnvC65\0"
  "iso_c7\0"
  "EnvC7\0"
  "iso_c7c6\0"
  "C7/C6\0"
  "iso_c8\0"
  "EnvC8\0"
  "iso_c9\0"
  "EnvC9\0"
  "iso_dl\0"
  "DL Envelope\0"
  "EnvDL\0"
  "iso_ra0\0"
  "iso_ra1\0"
  "iso_ra2\0"
  "iso_sra0\0"
  "SRA0\0"
  "iso_sra1\0"
  "SRA1\0"
  "iso_sra2\0"
  "SRA2\0"
  "jis_b0\0"
  "JB0\0"
  "jis_b1\0"
  "JB1\0"
  "jis_b10\0"
  "JB10\0"
  "jis_b2\0"
  "JB2\0"
  "jis_b3\0"
  "JB3\0"
  "jis_b4\0"
  "JB4\0"
  "jis_b5\0"
  "JB5\0"
  "jis_b6\0"
  "JB6\0"
  "jis_b7\0"
  "JB7\0"
  "jis_b8\0"
  "JB8\0"
  "jis_b9\0"
  "JB9\0"
  "jis_exec\0"
  "jis exec\0"
  "jpn_chou2\0"
  "Choukei 2 Envelope\0"
  "jpn_chou3\0"
  "Choukei 3 Envelope\0"
  "EnvChou3\0"
  "jpn_chou4\0"
  "Choukei 4 Envelope\0"
  "EnvChou4\0"
  "jpn_hagaki\0"
  "hagaki (postcard)\0"
  "jpn_kahu\0"
  "kahu Envelope\0"
  "jpn_kaku2\0"
  "kaku2 Envelope\0"
  "EnvKaku2\0"
  "jpn_oufuku\0"
  "oufuku (reply postcard)\0"
  "DoublePostcard\0"
  "jpn_you4\0"
  "you4 Envelope\0"
  "na_10x11\0"
  "na_10x13\0"
  "na_10x14\0"
  "na_10x15\0"
  "na_11x12\0"
  "12x11\0"
  "na_11x15\0"
  "15x11\0"
  "na_12x19\0"
  "na_5x7\0"
  "na_6x9\0"
  "6x9 Envelope\0"
  "na_7x9\0"
  "7x9 Envelope\0"
  "na_9x11\0"
  "9x11 Envelope\0"
  "na_a2\0"
  "a2 Envelope\0"
  "na_arch-a\0"
  "Arch A\0"
  "ARCHA\0"
  "na_arch-b\0"
  "Arch B\0"
  "ARCHB\0"
  "na_arch-c\0"
  "Arch C\0"
  "ARCHC\0"
  "na_arch-d\0"
  "Arch D\0"
  "ARCHD\0"
  "na_arch-e\0"
  "Arch E\0"
  "ARCHE\0"
  "na_b-plus\0"
  "na_c\0"
  "AnsiC\0"
  "na_c5\0"
  "na_d\0"
  "AnsiD\0"
  "na_e\0"
  "AnsiE\0"
  "na_edp\0"
  "na_eur-edp\0"
  "European edp\0"
  "na_executive\0"
  "Executive\0"
  "na_f\0"
  "na_fanfold-eur\0"
  "FanFold European\0"
  "FanFoldGerman\0"
  "na_fanfold-us\0"
  "FanFold US\0"
  "FanFoldUS\0"
  "na_foolscap\0"
  "FanFold German Legal\0"
  "FanFoldGermanLegal\0"
  "na_govt-legal\0"
  "Government Legal\0"
  "na_govt-letter\0"
  "Government Letter\0"
  "8x10\0"
  "na_index-3x5\0"
  "Index 3x5\0"
  "na_index-4x6\0"
  "Index 4x6 (postcard)\0"
  "na_index-4x6-ext\0"
  "Index 4x6 ext\0"
  "na_index-5x8\0"
  "Index 5x8\0"
  "na_invoice\0"
  "Invoice\0"
  "Statement\0"
  "na_ledger\0"
  "Tabloid\0"
  "Ledger\0"
  "na_legal\0"
  "US Legal\0"
  "na_legal-extra\0"
  "US Legal Extra\0"
  "LegalExtra\0"
  "na_letter\0"
  "US Letter\0"
  "na_letter-extra\0"
  "US Letter Extra\0"
  "LetterExtra\0"
  "na_letter-plus\0"
  "US Letter Plus\0"
  "LetterPlus\0"
  "na_monarch\0"
  "Monarch Envelope\0"
  "EnvMonarch\0"
  "na_number-10\0"
  "#10 Envelope\0"
  "Env10\0"
  "na_number-11\0"
  "#11 Eenvelope\0"
  "Env11\0"
  "na_number-12\0"
  "#12 Envelope\0"
  "Env12\0"
  "na_number-14\0"
  "#14 Envelope\0"
  "Env14\0"
  "na_number-9\0"
  "#9 Envelope\0"
  "Env9\0"
  "na_personal\0"
  "Personal Envelope\0"
  "EnvPersonal\0"
  "na_quarto\0"
  "Quarto\0"
  "na_super-a\0"
  "Super A\0"
  "SuperA\0"
  "na_super-b\0"
  "Super B\0"
  "SuperB\0"
  "na_wide-format\0"
  "Wide Format\0"
  "om_dai-pa-kai\0"
  "Dai-pa-kai\0"
  "om_folio\0"
  "Folio\0"
  "om_folio-sp\0"
  "Folio sp\0"
  "om_invite\0"
  "Invite Envelope\0"
  "EnvInvite\0"
  "om_italian\0"
  "Italian Envelope\0"
  "EnvItalian\0"
  "om_juuro-ku-kai\0"
  "om_pa-kai\0"
  "om_postfix\0"
  "Postfix Envelope\0"
  "om_small-photo\0"
  "Small Photo\0"
  "prc_1\0"
  "prc1 Envelope\0"
  "EnvPRC1\0"
  "prc_10\0"
  "prc10 Envelope\0"
  "EnvPRC10\0"
  "prc_16k\0"
  "prc 16k\0"
  "PRC16K\0"
  "prc_2\0"
  "prc2 Envelope\0"
  "EnvPRC2\0"
  "prc_3\0"
  "prc3 Envelope\0"
  "EnvPRC3\0"
  "prc_32k\0"
  "prc 32k\0"
  "PRC32K\0"
  "prc_4\0"
  "prc4 Envelope\0"
  "EnvPRC4\0"
  "prc_5\0"
  "prc5 Envelope\0"
  "EnvPRC5\0"
  "prc_6\0"
  "prc6 Envelope\0"
  "EnvPRC6\0"
  "prc_7\0"
  "prc7 Envelope\0"
  "EnvPRC7\0"
  "prc_8\0"
  "prc8 Envelope\0"
  "EnvPRC8\0"
  "roc_16k\0"
  "ROC 16k\0"
  "roc_8k\0"
  "ROC 8k\0"
  "Comm10\0";

typedef struct {
  int name;
  float width;
  float height;
  int display_name;
  int ppd_name;
} PaperInfo;

const PaperInfo standard_names_offsets[] = {
  {    0, 711.2, 1016,    0,   -1 },
  {    7, 1189, 1682,   15,   -1 },
  {   20, 841, 1189,    1,    1 },
  {   27, 1189, 2523,   36,   -1 },
  {   41, 594, 841,    1,    1 },
  {   48, 26, 37,   56,   56 },
  {   60, 841, 1783,   69,   -1 },
  {   74, 841, 2378,   83,   -1 },
  {   88, 420, 594,    1,    1 },
  {   95, 594, 1261,  104,   -1 },
  {  109, 594, 1682,  118,   -1 },
  {  123, 594, 2102,  132,   -1 },
  {  137, 297, 420,  144,  144 },
  {  147, 322, 445,  160,  169 },
  {  177, 420, 891,  186,   -1 },
  {  191, 420, 1189,  200,   -1 },
  {  205, 420, 1486,  214,   -1 },
  {  219, 420, 1783,  228,   -1 },
  {  233, 420, 2080,  242,   -1 },
  {  247, 210, 297,  254,  254 },
  {  257, 235.5, 322.3,  270,  279 },
  {  287, 225, 297,  298,   -1 },
  {  305, 297, 630,  314,   -1 },
  {  319, 297, 841,  328,   -1 },
  {  333, 297, 1051,  342,   -1 },
  {  347, 297, 1261,  356,   -1 },
  {  361, 297, 1471,  370,   -1 },
  {  375, 297, 1682,  384,   -1 },
  {  389, 297, 1892,  398,   -1 },
  {  403, 148, 210,  410,  410 },
  {  413, 174, 235,  426,  435 },
  {  443, 105, 148,  450,  450 },
  {  453, 74, 105,  460,  460 },
  {  463, 52, 74,  470,  470 },
  {  473, 37, 52,  480,  480 },
  {  483, 1000, 1414,  493,  490 },
  {  496, 707, 1000,  506,  503 },
  {  509, 31, 44,  520,  517 },
  {  524, 500, 707,  534,  531 },
  {  537, 353, 500,  547,  544 },
  {  550, 250, 353,  560,  557 },
  {  563, 176, 250,  573,  570 },
  {  576, 201, 276,  589,  598 },
  {  609, 125, 176,  619,  616 },
  {  622, 125, 324,  631,   -1 },
  {  637, 88, 125,  647,  644 },
  {  650, 62, 88,  660,  657 },
  {  663, 44, 62,  673,  670 },
  {  676, 917, 1297,  686,  683 },
  {  689, 648, 917,  699,  696 },
  {  702, 28, 40,  713,  710 },
  {  717, 458, 648,  727,  724 },
  {  730, 324, 458,  740,  737 },
  {  743, 229, 324,  634,  750 },
  {  756, 162, 229,  766,  763 },
  {  769, 114, 162,  779,  776 },
  {  782, 114, 229,  791,  797 },
  {  804, 81, 114,  814,  811 },
  {  817, 81, 162,  826,   -1 },
  {  832, 57, 81,  842,  839 },
  {  845, 40, 57,  855,  852 },
  {  858, 110, 220,  865,  877 },
  {  883, 860, 1220,  917,   -1 },
  {  891, 610, 860,  931,   -1 },
  {  899, 430, 610,  945,   -1 },
  {  907, 900, 1280,  916,   -1 },
  {  921, 640, 900,  930,   -1 },
  {  935, 450, 640,  944,   -1 },
  {  949, 1030, 1456,  956,  493 },
  {  960, 728, 1030,  967,  506 },
  {  971, 32, 45,  979,  520 },
  {  984, 515, 728,  991,  534 },
  {  995, 364, 515, 1002,  547 },
  { 1006, 257, 364, 1013,  560 },
  { 1017, 182, 257, 1024,  573 },
  { 1028, 128, 182, 1035,  619 },
  { 1039, 91, 128, 1046,  647 },
  { 1050, 64, 91, 1057,  660 },
  { 1061, 45, 64, 1068,  673 },
  { 1072, 216, 330, 1081,   -1 },
  { 1090, 111.1, 146, 1100,   -1 },
  { 1119, 120, 235, 1129, 1148 },
  { 1157, 90, 205, 1167, 1186 },
  { 1195, 100, 148, 1206, 1322 },
  { 1224, 240, 322.1, 1233,   -1 },
  { 1247, 240, 332, 1257, 1272 },
  { 1281, 148, 200, 1292, 1316 },
  { 1331, 105, 235, 1340,   -1 },
  { 1354, 254, 279.4, 1357, 1357 },
  { 1363, 254, 330.2, 1366, 1366 },
  { 1372, 254, 355.6, 1375, 1375 },
  { 1381, 254, 381, 1384,   -1 },
  { 1381, 254, 381, 1384,   -1 },
  { 1390, 279.4, 304.8, 1393, 1399 },
  { 1405, 279.4, 381, 1408, 1414 },
  { 1420, 304.8, 482.6, 1423,   -1 },
  { 1429, 127, 177.8, 1432,   -1 },
  { 1436, 152.4, 228.6, 1443,   -1 },
  { 1456, 177.8, 228.6, 1463, 1459 },
  { 1476, 228.6, 279.4, 1484, 1479 },
  { 1498, 111.125, 146.05, 1504,   -1 },
  { 1516, 228.6, 304.8, 1526, 1533 },
  { 1539, 304.8, 457.2, 1549, 1556 },
  { 1562, 457.2, 609.6, 1572, 1579 },
  { 1585, 609.6, 914.4, 1595, 1602 },
  { 1608, 914.4, 1219.2, 1618, 1625 },
  { 1631, 304.8, 486.918, 1634,   -1 },
  { 1641, 431.8, 558.8, 1079, 1646 },
  { 1652, 165.1, 241.3, 3019,   -1 },
  { 1658, 558.8, 863.6, 1329, 1663 },
  { 1669, 863.6, 1117.6,  875, 1674 },
  { 1680, 279.4, 355.6, 1683,   -1 },
  { 1687, 304.8, 355.6, 1698,   -1 },
  { 1711, 184.15, 266.7, 1724, 1724 },
  { 1734, 1117.6, 1727.2,    5,   -1 },
  { 1739, 215.9, 304.8, 1754, 1771 },
  { 1785, 279.4, 377.825, 1799, 1810 },
  { 1820, 215.9, 330.2, 1832, 1853 },
  { 1872, 203.2, 330.2, 1886,   -1 },
  { 1903, 203.2, 254, 1918, 1936 },
  { 1941, 76.2, 127, 1954,   -1 },
  { 1964, 101.6, 152.4, 1977,   -1 },
  { 1998, 152.4, 203.2, 2015,   -1 },
  { 2029, 127, 203.2, 2042,   -1 },
  { 2052, 139.7, 215.9, 2063, 2071 },
  { 2081, 279.4, 431.8, 2091, 2099 },
  { 2106, 215.9, 355.6, 2115, 1847 },
  { 2124, 241.3, 381, 2139, 2154 },
  { 2165, 215.9, 279.4, 2175, 1929 },
  { 2185, 241.3, 304.8, 2201, 2217 },
  { 2229, 215.9, 322.326, 2244, 2259 },
  { 2270, 98.425, 190.5, 2281, 2298 },
  { 2309, 104.775, 241.3, 2322, 2335 },
  { 2341, 114.3, 263.525, 2354, 2368 },
  { 2374, 120.65, 279.4, 2387, 2400 },
  { 2406, 127, 292.1, 2419, 2432 },
  { 2438, 98.425, 225.425, 2450, 2462 },
  { 2467, 92.075, 165.1, 2479, 2497 },
  { 2509, 215.9, 275.082, 2519, 2519 },
  { 2526, 227.076, 355.6, 2537, 2545 },
  { 2552, 330.2, 482.6, 2563, 2571 },
  { 2578, 762, 1066.8, 2593,   -1 },
  { 2605, 275, 395, 2619,   -1 },
  { 2630, 210, 330, 2639, 2639 },
  { 2645, 215, 315, 2657,   -1 },
  { 2666, 220, 220, 2676, 2692 },
  { 2702, 110, 230, 2713, 2730 },
  { 2741, 198, 275, 2744,   -1 },
  { 2757, 267, 389, 2612,   -1 },
  { 2767, 114, 229, 2778,   -1 },
  { 2795, 100, 150, 2810,   -1 },
  { 2822, 102, 165, 2828, 2842 },
  { 2850, 324, 458, 2857, 2872 },
  { 2881, 146, 215, 2889, 2897 },
  { 2904, 102, 176, 2910, 2924 },
  { 2932, 125, 176, 2938, 2952 },
  { 2960, 97, 151, 2968, 2976 },
  { 2983, 110, 208, 2989, 3003 },
  { 3011, 110, 220, 3017, 3031 },
  { 3039, 120, 320, 3045, 3059 },
  { 3067, 160, 230, 3073, 3087 },
  { 3095, 120, 309, 3101, 3115 },
  { 3123, 196.85, 273.05, 3131,   -1 },
  { 3139, 273.05, 393.7, 3146,   -1 },
};

const struct {
  int ppd_name;
  int standard_name;
} extra_ppd_names_offsets[] = {
  {  634,  743 },
  {  766,  756 },
  {  779,  769 },
  { 3153, 2309 },
  {  880,  858 },
  { 2301, 2270 },
};

