/* Generated by gen-paper-names */

#if 0
NC_("paper size", "asme_f")
NC_("paper size", "A0×2")
NC_("paper size", "A0")
NC_("paper size", "A0×3")
NC_("paper size", "A1")
NC_("paper size", "A10")
NC_("paper size", "A1×3")
NC_("paper size", "A1×4")
NC_("paper size", "A2")
NC_("paper size", "A2×3")
NC_("paper size", "A2×4")
NC_("paper size", "A2×5")
NC_("paper size", "A3")
NC_("paper size", "A3 Extra")
NC_("paper size", "A3×3")
NC_("paper size", "A3×4")
NC_("paper size", "A3×5")
NC_("paper size", "A3×6")
NC_("paper size", "A3×7")
NC_("paper size", "A4")
NC_("paper size", "A4 Extra")
NC_("paper size", "A4 Tab")
NC_("paper size", "A4×3")
NC_("paper size", "A4×4")
NC_("paper size", "A4×5")
NC_("paper size", "A4×6")
NC_("paper size", "A4×7")
NC_("paper size", "A4×8")
NC_("paper size", "A4×9")
NC_("paper size", "A5")
NC_("paper size", "A5 Extra")
NC_("paper size", "A6")
NC_("paper size", "A7")
NC_("paper size", "A8")
NC_("paper size", "A9")
NC_("paper size", "B0")
NC_("paper size", "B1")
NC_("paper size", "B10")
NC_("paper size", "B2")
NC_("paper size", "B3")
NC_("paper size", "B4")
NC_("paper size", "B5")
NC_("paper size", "B5 Extra")
NC_("paper size", "B6")
NC_("paper size", "B6/C4")
NC_("paper size", "B7")
NC_("paper size", "B8")
NC_("paper size", "B9")
NC_("paper size", "C0")
NC_("paper size", "C1")
NC_("paper size", "C10")
NC_("paper size", "C2")
NC_("paper size", "C3")
NC_("paper size", "C4")
NC_("paper size", "C5")
NC_("paper size", "C6")
NC_("paper size", "C6/C5")
NC_("paper size", "C7")
NC_("paper size", "C7/C6")
NC_("paper size", "C8")
NC_("paper size", "C9")
NC_("paper size", "DL Envelope")
NC_("paper size", "RA0")
NC_("paper size", "RA1")
NC_("paper size", "RA2")
NC_("paper size", "SRA0")
NC_("paper size", "SRA1")
NC_("paper size", "SRA2")
NC_("paper size", "JB0")
NC_("paper size", "JB1")
NC_("paper size", "JB10")
NC_("paper size", "JB2")
NC_("paper size", "JB3")
NC_("paper size", "JB4")
NC_("paper size", "JB5")
NC_("paper size", "JB6")
NC_("paper size", "JB7")
NC_("paper size", "JB8")
NC_("paper size", "JB9")
NC_("paper size", "jis exec")
NC_("paper size", "Choukei 2 Envelope")
NC_("paper size", "Choukei 3 Envelope")
NC_("paper size", "Choukei 4 Envelope")
NC_("paper size", "hagaki (postcard)")
NC_("paper size", "kahu Envelope")
NC_("paper size", "kaku2 Envelope")
NC_("paper size", "oufuku (reply postcard)")
NC_("paper size", "you4 Envelope")
NC_("paper size", "10×11")
NC_("paper size", "10×13")
NC_("paper size", "10×14")
NC_("paper size", "10×15")
NC_("paper size", "10×15")
NC_("paper size", "11×12")
NC_("paper size", "11×15")
NC_("paper size", "12×19")
NC_("paper size", "5×7")
NC_("paper size", "6×9 Envelope")
NC_("paper size", "7×9 Envelope")
NC_("paper size", "9×11 Envelope")
NC_("paper size", "a2 Envelope")
NC_("paper size", "Arch A")
NC_("paper size", "Arch B")
NC_("paper size", "Arch C")
NC_("paper size", "Arch D")
NC_("paper size", "Arch E")
NC_("paper size", "b-plus")
NC_("paper size", "c")
NC_("paper size", "c5 Envelope")
NC_("paper size", "d")
NC_("paper size", "e")
NC_("paper size", "edp")
NC_("paper size", "European edp")
NC_("paper size", "Executive")
NC_("paper size", "f")
NC_("paper size", "Fan-Fold European")
NC_("paper size", "Fan-Fold US")
NC_("paper size", "Fan-Fold German Legal")
NC_("paper size", "Government Legal")
NC_("paper size", "Government Letter")
NC_("paper size", "Index 3×5")
NC_("paper size", "Index 4×6 (postcard)")
NC_("paper size", "Index 4×6 ext")
NC_("paper size", "Index 5×8")
NC_("paper size", "Invoice")
NC_("paper size", "Tabloid")
NC_("paper size", "US Legal")
NC_("paper size", "US Legal Extra")
NC_("paper size", "US Letter")
NC_("paper size", "US Letter Extra")
NC_("paper size", "US Letter Plus")
NC_("paper size", "Monarch Envelope")
NC_("paper size", "#10 Envelope")
NC_("paper size", "#11 Envelope")
NC_("paper size", "#12 Envelope")
NC_("paper size", "#14 Envelope")
NC_("paper size", "#9 Envelope")
NC_("paper size", "Personal Envelope")
NC_("paper size", "Quarto")
NC_("paper size", "Super A")
NC_("paper size", "Super B")
NC_("paper size", "Wide Format")
NC_("paper size", "Dai-pa-kai")
NC_("paper size", "Folio")
NC_("paper size", "Folio sp")
NC_("paper size", "Invite Envelope")
NC_("paper size", "Italian Envelope")
NC_("paper size", "juuro-ku-kai")
NC_("paper size", "pa-kai")
NC_("paper size", "Postfix Envelope")
NC_("paper size", "Small Photo")
NC_("paper size", "prc1 Envelope")
NC_("paper size", "prc10 Envelope")
NC_("paper size", "prc 16k")
NC_("paper size", "prc2 Envelope")
NC_("paper size", "prc3 Envelope")
NC_("paper size", "prc 32k")
NC_("paper size", "prc4 Envelope")
NC_("paper size", "prc5 Envelope")
NC_("paper size", "prc6 Envelope")
NC_("paper size", "prc7 Envelope")
NC_("paper size", "prc8 Envelope")
NC_("paper size", "prc9 Envelope")
NC_("paper size", "ROC 16k")
NC_("paper size", "ROC 8k")
#endif

static const char paper_names[] =
  "asme_f\0"
  "iso_2a0\0"
  "A0×2\0"
  "iso_a0\0"
  "iso_a0x3\0"
  "A0×3\0"
  "iso_a1\0"
  "iso_a10\0"
  "A10\0"
  "iso_a1x3\0"
  "A1×3\0"
  "iso_a1x4\0"
  "A1×4\0"
  "iso_a2\0"
  "iso_a2x3\0"
  "A2×3\0"
  "iso_a2x4\0"
  "A2×4\0"
  "iso_a2x5\0"
  "A2×5\0"
  "iso_a3\0"
  "A3\0"
  "iso_a3-extra\0"
  "A3 Extra\0"
  "A3Extra\0"
  "iso_a3x3\0"
  "A3×3\0"
  "iso_a3x4\0"
  "A3×4\0"
  "iso_a3x5\0"
  "A3×5\0"
  "iso_a3x6\0"
  "A3×6\0"
  "iso_a3x7\0"
  "A3×7\0"
  "iso_a4\0"
  "A4\0"
  "iso_a4-extra\0"
  "A4 Extra\0"
  "A4Extra\0"
  "iso_a4-tab\0"
  "A4 Tab\0"
  "iso_a4x3\0"
  "A4×3\0"
  "iso_a4x4\0"
  "A4×4\0"
  "iso_a4x5\0"
  "A4×5\0"
  "iso_a4x6\0"
  "A4×6\0"
  "iso_a4x7\0"
  "A4×7\0"
  "iso_a4x8\0"
  "A4×8\0"
  "iso_a4x9\0"
  "A4×9\0"
  "iso_a5\0"
  "A5\0"
  "iso_a5-extra\0"
  "A5 Extra\0"
  "A5Extra\0"
  "iso_a6\0"
  "A6\0"
  "iso_a7\0"
  "A7\0"
  "iso_a8\0"
  "A8\0"
  "iso_a9\0"
  "A9\0"
  "iso_b0\0"
  "ISOB0\0"
  "iso_b1\0"
  "ISOB1\0"
  "iso_b10\0"
  "ISOB10\0"
  "iso_b2\0"
  "ISOB2\0"
  "iso_b3\0"
  "ISOB3\0"
  "iso_b4\0"
  "ISOB4\0"
  "iso_b5\0"
  "ISOB5\0"
  "iso_b5-extra\0"
  "B5 Extra\0"
  "ISOB5Extra\0"
  "iso_b6\0"
  "ISOB6\0"
  "iso_b6c4\0"
  "B6/C4\0"
  "iso_b7\0"
  "ISOB7\0"
  "iso_b8\0"
  "ISOB8\0"
  "iso_b9\0"
  "ISOB9\0"
  "iso_c0\0"
  "EnvC0\0"
  "iso_c1\0"
  "EnvC1\0"
  "iso_c10\0"
  "EnvC10\0"
  "iso_c2\0"
  "EnvC2\0"
  "iso_c3\0"
  "EnvC3\0"
  "iso_c4\0"
  "EnvC4\0"
  "iso_c5\0"
  "EnvC5\0"
  "iso_c6\0"
  "EnvC6\0"
  "iso_c6c5\0"
  "C6/C5\0"
  "EnvC65\0"
  "iso_c7\0"
  "EnvC7\0"
  "iso_c7c6\0"
  "C7/C6\0"
  "iso_c8\0"
  "EnvC8\0"
  "iso_c9\0"
  "EnvC9\0"
  "iso_dl\0"
  "DL Envelope\0"
  "EnvDL\0"
  "iso_ra0\0"
  "iso_ra1\0"
  "iso_ra2\0"
  "iso_sra0\0"
  "SRA0\0"
  "iso_sra1\0"
  "SRA1\0"
  "iso_sra2\0"
  "SRA2\0"
  "jis_b0\0"
  "JB0\0"
  "jis_b1\0"
  "JB1\0"
  "jis_b10\0"
  "JB10\0"
  "jis_b2\0"
  "JB2\0"
  "jis_b3\0"
  "JB3\0"
  "jis_b4\0"
  "JB4\0"
  "jis_b5\0"
  "JB5\0"
  "jis_b6\0"
  "JB6\0"
  "jis_b7\0"
  "JB7\0"
  "jis_b8\0"
  "JB8\0"
  "jis_b9\0"
  "JB9\0"
  "jis_exec\0"
  "jis exec\0"
  "jpn_chou2\0"
  "Choukei 2 Envelope\0"
  "jpn_chou3\0"
  "Choukei 3 Envelope\0"
  "EnvChou3\0"
  "jpn_chou4\0"
  "Choukei 4 Envelope\0"
  "EnvChou4\0"
  "jpn_hagaki\0"
  "hagaki (postcard)\0"
  "jpn_kahu\0"
  "kahu Envelope\0"
  "jpn_kaku2\0"
  "kaku2 Envelope\0"
  "EnvKaku2\0"
  "jpn_oufuku\0"
  "oufuku (reply postcard)\0"
  "DoublePostcard\0"
  "jpn_you4\0"
  "you4 Envelope\0"
  "na_10x11\0"
  "10×11\0"
  "na_10x13\0"
  "10×13\0"
  "na_10x14\0"
  "10×14\0"
  "na_10x15\0"
  "10×15\0"
  "na_11x12\0"
  "11×12\0"
  "12x11\0"
  "na_11x15\0"
  "11×15\0"
  "15x11\0"
  "na_12x19\0"
  "12×19\0"
  "na_5x7\0"
  "5×7\0"
  "na_6x9\0"
  "6×9 Envelope\0"
  "na_7x9\0"
  "7×9 Envelope\0"
  "na_9x11\0"
  "9×11 Envelope\0"
  "na_a2\0"
  "a2 Envelope\0"
  "na_arch-a\0"
  "Arch A\0"
  "ARCHA\0"
  "na_arch-b\0"
  "Arch B\0"
  "ARCHB\0"
  "na_arch-c\0"
  "Arch C\0"
  "ARCHC\0"
  "na_arch-d\0"
  "Arch D\0"
  "ARCHD\0"
  "na_arch-e\0"
  "Arch E\0"
  "ARCHE\0"
  "na_b-plus\0"
  "na_c\0"
  "AnsiC\0"
  "na_c5\0"
  "na_d\0"
  "AnsiD\0"
  "na_e\0"
  "AnsiE\0"
  "na_edp\0"
  "na_eur-edp\0"
  "European edp\0"
  "na_executive\0"
  "Executive\0"
  "na_f\0"
  "na_fanfold-eur\0"
  "Fan-Fold European\0"
  "FanFoldGerman\0"
  "na_fanfold-us\0"
  "Fan-Fold US\0"
  "FanFoldUS\0"
  "na_foolscap\0"
  "Fan-Fold German Legal\0"
  "FanFoldGermanLegal\0"
  "na_govt-legal\0"
  "Government Legal\0"
  "na_govt-letter\0"
  "Government Letter\0"
  "8x10\0"
  "na_index-3x5\0"
  "Index 3×5\0"
  "na_index-4x6\0"
  "Index 4×6 (postcard)\0"
  "na_index-4x6-ext\0"
  "Index 4×6 ext\0"
  "na_index-5x8\0"
  "Index 5×8\0"
  "na_invoice\0"
  "Invoice\0"
  "Statement\0"
  "na_ledger\0"
  "Tabloid\0"
  "Ledger\0"
  "na_legal\0"
  "US Legal\0"
  "na_legal-extra\0"
  "US Legal Extra\0"
  "LegalExtra\0"
  "na_letter\0"
  "US Letter\0"
  "na_letter-extra\0"
  "US Letter Extra\0"
  "LetterExtra\0"
  "na_letter-plus\0"
  "US Letter Plus\0"
  "LetterPlus\0"
  "na_monarch\0"
  "Monarch Envelope\0"
  "EnvMonarch\0"
  "na_number-10\0"
  "#10 Envelope\0"
  "Env10\0"
  "na_number-11\0"
  "#11 Envelope\0"
  "Env11\0"
  "na_number-12\0"
  "#12 Envelope\0"
  "Env12\0"
  "na_number-14\0"
  "#14 Envelope\0"
  "Env14\0"
  "na_number-9\0"
  "#9 Envelope\0"
  "Env9\0"
  "na_personal\0"
  "Personal Envelope\0"
  "EnvPersonal\0"
  "na_quarto\0"
  "Quarto\0"
  "na_super-a\0"
  "Super A\0"
  "SuperA\0"
  "na_super-b\0"
  "Super B\0"
  "SuperB\0"
  "na_wide-format\0"
  "Wide Format\0"
  "om_dai-pa-kai\0"
  "Dai-pa-kai\0"
  "om_folio\0"
  "Folio\0"
  "om_folio-sp\0"
  "Folio sp\0"
  "om_invite\0"
  "Invite Envelope\0"
  "EnvInvite\0"
  "om_italian\0"
  "Italian Envelope\0"
  "EnvItalian\0"
  "om_juuro-ku-kai\0"
  "om_pa-kai\0"
  "om_postfix\0"
  "Postfix Envelope\0"
  "om_small-photo\0"
  "Small Photo\0"
  "prc_1\0"
  "prc1 Envelope\0"
  "EnvPRC1\0"
  "prc_10\0"
  "prc10 Envelope\0"
  "EnvPRC10\0"
  "prc_16k\0"
  "prc 16k\0"
  "PRC16K\0"
  "prc_2\0"
  "prc2 Envelope\0"
  "EnvPRC2\0"
  "prc_3\0"
  "prc3 Envelope\0"
  "EnvPRC3\0"
  "prc_32k\0"
  "prc 32k\0"
  "PRC32K\0"
  "prc_4\0"
  "prc4 Envelope\0"
  "EnvPRC4\0"
  "prc_5\0"
  "prc5 Envelope\0"
  "EnvPRC5\0"
  "prc_6\0"
  "prc6 Envelope\0"
  "EnvPRC6\0"
  "prc_7\0"
  "prc7 Envelope\0"
  "EnvPRC7\0"
  "prc_8\0"
  "prc8 Envelope\0"
  "EnvPRC8\0"
  "prc_9\0"
  "prc9 Envelope\0"
  "EnvPRC9\0"
  "roc_16k\0"
  "ROC 16k\0"
  "roc_8k\0"
  "ROC 8k\0"
  "Comm10\0";

typedef struct {
  int name;
  float width;
  float height;
  int display_name;
  int ppd_name;
} PaperInfo;

static const PaperInfo standard_names_offsets[] = {
  {    0, 711.2, 1016,    0,   -1 },
  {    7, 1189, 1682,   15,   -1 },
  {   21, 841, 1189,  937,  937 },
  {   28, 1189, 2523,   37,   -1 },
  {   43, 594, 841,  951,  951 },
  {   50, 26, 37,   58,   58 },
  {   62, 841, 1783,   71,   -1 },
  {   77, 841, 2378,   86,   -1 },
  {   92, 420, 594,  965,  965 },
  {   99, 594, 1261,  108,   -1 },
  {  114, 594, 1682,  123,   -1 },
  {  129, 594, 2102,  138,   -1 },
  {  144, 297, 420,  151,  151 },
  {  154, 322, 445,  167,  176 },
  {  184, 420, 891,  193,   -1 },
  {  199, 420, 1189,  208,   -1 },
  {  214, 420, 1486,  223,   -1 },
  {  229, 420, 1783,  238,   -1 },
  {  244, 420, 2080,  253,   -1 },
  {  259, 210, 297,  266,  266 },
  {  269, 235.5, 322.3,  282,  291 },
  {  299, 225, 297,  310,   -1 },
  {  317, 297, 630,  326,   -1 },
  {  332, 297, 841,  341,   -1 },
  {  347, 297, 1051,  356,   -1 },
  {  362, 297, 1261,  371,   -1 },
  {  377, 297, 1471,  386,   -1 },
  {  392, 297, 1682,  401,   -1 },
  {  407, 297, 1892,  416,   -1 },
  {  422, 148, 210,  429,  429 },
  {  432, 174, 235,  445,  454 },
  {  462, 105, 148,  469,  469 },
  {  472, 74, 105,  479,  479 },
  {  482, 52, 74,  489,  489 },
  {  492, 37, 52,  499,  499 },
  {  502, 1000, 1414,  512,  509 },
  {  515, 707, 1000,  525,  522 },
  {  528, 31, 44,  539,  536 },
  {  543, 500, 707,  553,  550 },
  {  556, 353, 500,  566,  563 },
  {  569, 250, 353,  579,  576 },
  {  582, 176, 250,  592,  589 },
  {  595, 201, 276,  608,  617 },
  {  628, 125, 176,  638,  635 },
  {  641, 125, 324,  650,   -1 },
  {  656, 88, 125,  666,  663 },
  {  669, 62, 88,  679,  676 },
  {  682, 44, 62,  692,  689 },
  {  695, 917, 1297,  705,  702 },
  {  708, 648, 917,  718,  715 },
  {  721, 28, 40,  732,  729 },
  {  736, 458, 648,  746,  743 },
  {  749, 324, 458,  759,  756 },
  {  762, 229, 324,  653,  769 },
  {  775, 162, 229,  785,  782 },
  {  788, 114, 162,  798,  795 },
  {  801, 114, 229,  810,  816 },
  {  823, 81, 114,  833,  830 },
  {  836, 81, 162,  845,   -1 },
  {  851, 57, 81,  861,  858 },
  {  864, 40, 57,  874,  871 },
  {  877, 110, 220,  884,  896 },
  {  902, 860, 1220,  936,   -1 },
  {  910, 610, 860,  950,   -1 },
  {  918, 430, 610,  964,   -1 },
  {  926, 900, 1280,  935,   -1 },
  {  940, 640, 900,  949,   -1 },
  {  954, 450, 640,  963,   -1 },
  {  968, 1030, 1456,  975,  512 },
  {  979, 728, 1030,  986,  525 },
  {  990, 32, 45,  998,  539 },
  { 1003, 515, 728, 1010,  553 },
  { 1014, 364, 515, 1021,  566 },
  { 1025, 257, 364, 1032,  579 },
  { 1036, 182, 257, 1043,  592 },
  { 1047, 128, 182, 1054,  638 },
  { 1058, 91, 128, 1065,  666 },
  { 1069, 64, 91, 1076,  679 },
  { 1080, 45, 64, 1087,  692 },
  { 1091, 216, 330, 1100,   -1 },
  { 1109, 111.1, 146, 1119,   -1 },
  { 1138, 120, 235, 1148, 1167 },
  { 1176, 90, 205, 1186, 1205 },
  { 1214, 100, 148, 1225, 1341 },
  { 1243, 240, 322.1, 1252,   -1 },
  { 1266, 240, 332, 1276, 1291 },
  { 1300, 148, 200, 1311, 1335 },
  { 1350, 105, 235, 1359,   -1 },
  { 1373, 254, 279.4, 1382, 1376 },
  { 1389, 254, 330.2, 1398, 1392 },
  { 1405, 254, 355.6, 1414, 1408 },
  { 1421, 254, 381, 1430,   -1 },
  { 1421, 254, 381, 1430,   -1 },
  { 1437, 279.4, 304.8, 1446, 1453 },
  { 1459, 279.4, 381, 1468, 1475 },
  { 1481, 304.8, 482.6, 1490,   -1 },
  { 1497, 127, 177.8, 1504,   -1 },
  { 1509, 152.4, 228.6, 1516,   -1 },
  { 1530, 177.8, 228.6, 1537, 1533 },
  { 1551, 228.6, 279.4, 1559, 1554 },
  { 1574, 111.125, 146.05, 1580,   -1 },
  { 1592, 228.6, 304.8, 1602, 1609 },
  { 1615, 304.8, 457.2, 1625, 1632 },
  { 1638, 457.2, 609.6, 1648, 1655 },
  { 1661, 609.6, 914.4, 1671, 1678 },
  { 1684, 914.4, 1219.2, 1694, 1701 },
  { 1707, 304.8, 486.918, 1710,   -1 },
  { 1717, 431.8, 558.8, 1098, 1722 },
  { 1728, 165.1, 241.3, 3101,   -1 },
  { 1734, 558.8, 863.6, 1348, 1739 },
  { 1745, 863.6, 1117.6,  894, 1750 },
  { 1756, 279.4, 355.6, 1759,   -1 },
  { 1763, 304.8, 355.6, 1774,   -1 },
  { 1787, 184.15, 266.7, 1800, 1800 },
  { 1810, 1117.6, 1727.2,    5,   -1 },
  { 1815, 215.9, 304.8, 1830, 1848 },
  { 1862, 279.4, 377.825, 1876, 1888 },
  { 1898, 215.9, 330.2, 1910, 1932 },
  { 1951, 203.2, 330.2, 1965,   -1 },
  { 1982, 203.2, 254, 1997, 2015 },
  { 2020, 76.2, 127, 2033,   -1 },
  { 2044, 101.6, 152.4, 2057,   -1 },
  { 2079, 152.4, 203.2, 2096,   -1 },
  { 2111, 127, 203.2, 2124,   -1 },
  { 2135, 139.7, 215.9, 2146, 2154 },
  { 2164, 279.4, 431.8, 2174, 2182 },
  { 2189, 215.9, 355.6, 2198, 1926 },
  { 2207, 241.3, 381, 2222, 2237 },
  { 2248, 215.9, 279.4, 2258, 2008 },
  { 2268, 241.3, 304.8, 2284, 2300 },
  { 2312, 215.9, 322.326, 2327, 2342 },
  { 2353, 98.425, 190.5, 2364, 2381 },
  { 2392, 104.775, 241.3, 2405, 2418 },
  { 2424, 114.3, 263.525, 2437, 2450 },
  { 2456, 120.65, 279.4, 2469, 2482 },
  { 2488, 127, 292.1, 2501, 2514 },
  { 2520, 98.425, 225.425, 2532, 2544 },
  { 2549, 92.075, 165.1, 2561, 2579 },
  { 2591, 215.9, 275.082, 2601, 2601 },
  { 2608, 227.076, 355.6, 2619, 2627 },
  { 2634, 330.2, 482.6, 2645, 2653 },
  { 2660, 762, 1066.8, 2675,   -1 },
  { 2687, 275, 395, 2701,   -1 },
  { 2712, 210, 330, 2721, 2721 },
  { 2727, 215, 315, 2739,   -1 },
  { 2748, 220, 220, 2758, 2774 },
  { 2784, 110, 230, 2795, 2812 },
  { 2823, 198, 275, 2826,   -1 },
  { 2839, 267, 389, 2694,   -1 },
  { 2849, 114, 229, 2860,   -1 },
  { 2877, 100, 150, 2892,   -1 },
  { 2904, 102, 165, 2910, 2924 },
  { 2932, 324, 458, 2939, 2954 },
  { 2963, 146, 215, 2971, 2979 },
  { 2986, 102, 176, 2992, 3006 },
  { 3014, 125, 176, 3020, 3034 },
  { 3042, 97, 151, 3050, 3058 },
  { 3065, 110, 208, 3071, 3085 },
  { 3093, 110, 220, 3099, 3113 },
  { 3121, 120, 230, 3127, 3141 },
  { 3149, 160, 230, 3155, 3169 },
  { 3177, 120, 309, 3183, 3197 },
  { 3205, 229, 324, 3211, 3225 },
  { 3233, 196.85, 273.05, 3241,   -1 },
  { 3249, 273.05, 393.7, 3256,   -1 },
};

static const struct {
  int ppd_name;
  int standard_name;
} extra_ppd_names_offsets[] = {
  {  653,  762 },
  {  785,  775 },
  {  798,  788 },
  { 3263, 2392 },
  {  899,  877 },
  { 2384, 2353 },
};

