'\" t
.\"     Title: gdk-pixbuf-csource
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.74.2 <http://docbook.sf.net/>
.\"      Date: 03/02/2009
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "GDK\-PIXBUF\-CSOURCE" "1" "03/02/2009" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gdk-pixbuf-csource \- C code generation utility for GdkPixbuf images
.SH "SYNOPSIS"
.HP \w'\fBgdk\-pixbuf\-csource\fR\ 'u
\fBgdk\-pixbuf\-csource\fR [options] [image]
.HP \w'\fBgdk\-pixbuf\-csource\fR\ 'u
\fBgdk\-pixbuf\-csource\fR [options] \-\-build\-list [[name]\ [image]...]
.SH "DESCRIPTION"
.PP

\fBgdk\-pixbuf\-csource\fR
is a small utility that generates C code containing images, useful for compiling images directly into programs\&.
.SH "INVOCATION"
.PP

\fBgdk\-pixbuf\-csource\fR
either takes as input one image file name to generate code for, or, using the
\fB\-\-build\-list\fR
option, a list of (\fIname\fR,
\fIimage\fR) pairs to generate code for a list of images into named variables\&.
.SS "Options"
.PP
\fB\-\-stream\fR
.RS 4
Generate pixbuf data stream (a single string containing a serialized
GdkPixdata
structure in network byte order)\&.
.RE
.PP
\fB\-\-struct\fR
.RS 4
Generate GdkPixdata structure (needs the
GdkPixdata
structure definition from
gdk\-pixdata\&.h)\&.
.RE
.PP
\fB\-\-macros\fR
.RS 4
Generate *_ROWSTRIDE, *_WIDTH, *_HEIGHT, *_BYTES_PER_PIXEL and *_RLE_PIXEL_DATA or *_PIXEL_DATA macro definitions for the image\&.
.RE
.PP
\fB\-\-rle\fR
.RS 4
Enables run\-length encoding for the generated pixel data (default)\&.
.RE
.PP
\fB\-\-raw\fR
.RS 4
Disables run\-length encoding for the generated pixel data\&.
.RE
.PP
\fB\-\-extern\fR
.RS 4
Generate extern symbols\&.
.RE
.PP
\fB\-\-static\fR
.RS 4
Generate static symbols (default)\&.
.RE
.PP
\fB\-\-decoder\fR
.RS 4
Provide a *_RUN_LENGTH_DECODE(image_buf, rle_data, size, bpp) macro definition to decode run\-length encoded image data\&.
.RE
.PP
\fB\-\-name=identifier\fR
.RS 4
Specifies the identifier name (prefix) for the generated variables or macros (useful only if
\fB\-\-build\-list\fR
was not specified)\&.
.RE
.PP
\fB\-\-build\-list\fR
.RS 4
Enables (\fIname\fR,
\fIimage\fR) pair parsing mode\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print brief help and exit\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Print version and exit\&.
.RE
.PP
\fB\-\-g\-fatal\-warnings\fR
.RS 4
Make warnings fatal (causes the program to abort)\&.
.RE
.SH "SEE ALSO"
.PP
The
GdkPixbuf
documentation, shipped with the Gtk+ distribution, available from
\m[blue]\fBwww\&.gtk\&.org\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "BUGS"
.PP
The runlength encoder gets out of sync with the pixel boundaries, since it includes the rowstride padding in the encoded stream\&. Furthermore, it generates pixbufs with suboptimal rowstride in some cases\&.
.SH "AUTHOR"
.PP

\fBgdk\-pixbuf\-csource\fR
was written by Tim Janik
timj@gtk\&.org\&.
.PP
This manual page was provided by Tim Janik
timj@gtk\&.org\&.
.SH "NOTES"
.IP " 1." 4
www.gtk.org
.RS 4
\%http://www.gtk.org
.RE
