'\" t
.\"     Title: gdk-pixbuf-query-loaders
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.2 <http://docbook.sf.net/>
.\"      Date: 03/13/2009
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "GDK\-PIXBUF\-QUERY\-" "1" "03/13/2009" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gdk-pixbuf-query-loaders \- GdkPixbuf loader registration utility
.SH "SYNOPSIS"
.HP \w'\fBgdk\-pixbuf\-query\-loaders\fR\ 'u
\fBgdk\-pixbuf\-query\-loaders\fR [module...]
.SH "DESCRIPTION"
.PP

\fBgdk\-pixbuf\-query\-loaders\fR
collects information about loadable modules for
gdk\-pixbuf
and writes it to
stdout\&.
.PP
If called without arguments, it looks for modules in the
gdk\-pixbuf
loader directory\&.
.PP
If called with arguments, it looks for the specified modules\&. The arguments may be absolute or relative paths\&.
.SH "ENVIRONMENT"
.PP
The environment variable
\fBGDK_PIXBUF_MODULEDIR\fR
can be used to specify a different loader directory\&. The default
gdk\-pixbuf
loader directory is
\fIlibdir\fR/gtk\-2\&.0/\fIversion\fR/loaders\&.
.SH "BUGS"
.PP
None known yet\&.
