#if 0

NC_("emoji name", "grinning face")
NC_("emoji name", "beaming face with smiling eyes")
NC_("emoji name", "face with tears of joy")
NC_("emoji name", "rolling on the floor laughing")
NC_("emoji name", "grinning face with big eyes")
NC_("emoji name", "grinning face with smiling eyes")
NC_("emoji name", "grinning face with sweat")
NC_("emoji name", "grinning squinting face")
NC_("emoji name", "winking face")
NC_("emoji name", "smiling face with smiling eyes")
NC_("emoji name", "face savoring food")
NC_("emoji name", "smiling face with sunglasses")
NC_("emoji name", "smiling face with heart-eyes")
NC_("emoji name", "face blowing a kiss")
NC_("emoji name", "kissing face")
NC_("emoji name", "kissing face with smiling eyes")
NC_("emoji name", "kissing face with closed eyes")
NC_("emoji name", "smiling face")
NC_("emoji name", "slightly smiling face")
NC_("emoji name", "hugging face")
NC_("emoji name", "⊛ star-struck")
NC_("emoji name", "thinking face")
NC_("emoji name", "⊛ face with raised eyebrow")
NC_("emoji name", "neutral face")
NC_("emoji name", "expressionless face")
NC_("emoji name", "face without mouth")
NC_("emoji name", "face with rolling eyes")
NC_("emoji name", "smirking face")
NC_("emoji name", "persevering face")
NC_("emoji name", "sad but relieved face")
NC_("emoji name", "face with open mouth")
NC_("emoji name", "zipper-mouth face")
NC_("emoji name", "hushed face")
NC_("emoji name", "sleepy face")
NC_("emoji name", "tired face")
NC_("emoji name", "sleeping face")
NC_("emoji name", "relieved face")
NC_("emoji name", "face with tongue")
NC_("emoji name", "winking face with tongue")
NC_("emoji name", "squinting face with tongue")
NC_("emoji name", "drooling face")
NC_("emoji name", "unamused face")
NC_("emoji name", "downcast face with sweat")
NC_("emoji name", "pensive face")
NC_("emoji name", "confused face")
NC_("emoji name", "upside-down face")
NC_("emoji name", "money-mouth face")
NC_("emoji name", "astonished face")
NC_("emoji name", "frowning face")
NC_("emoji name", "slightly frowning face")
NC_("emoji name", "confounded face")
NC_("emoji name", "disappointed face")
NC_("emoji name", "worried face")
NC_("emoji name", "face with steam from nose")
NC_("emoji name", "crying face")
NC_("emoji name", "loudly crying face")
NC_("emoji name", "frowning face with open mouth")
NC_("emoji name", "anguished face")
NC_("emoji name", "fearful face")
NC_("emoji name", "weary face")
NC_("emoji name", "⊛ exploding head")
NC_("emoji name", "grimacing face")
NC_("emoji name", "anxious face with sweat")
NC_("emoji name", "face screaming in fear")
NC_("emoji name", "flushed face")
NC_("emoji name", "⊛ crazy face")
NC_("emoji name", "dizzy face")
NC_("emoji name", "pouting face")
NC_("emoji name", "angry face")
NC_("emoji name", "⊛ face with symbols on mouth")
NC_("emoji name", "face with medical mask")
NC_("emoji name", "face with thermometer")
NC_("emoji name", "face with head-bandage")
NC_("emoji name", "nauseated face")
NC_("emoji name", "⊛ face vomiting")
NC_("emoji name", "sneezing face")
NC_("emoji name", "smiling face with halo")
NC_("emoji name", "cowboy hat face")
NC_("emoji name", "clown face")
NC_("emoji name", "lying face")
NC_("emoji name", "⊛ shushing face")
NC_("emoji name", "⊛ face with hand over mouth")
NC_("emoji name", "⊛ face with monocle")
NC_("emoji name", "nerd face")
NC_("emoji name", "smiling face with horns")
NC_("emoji name", "angry face with horns")
NC_("emoji name", "ogre")
NC_("emoji name", "goblin")
NC_("emoji name", "skull")
NC_("emoji name", "skull and crossbones")
NC_("emoji name", "ghost")
NC_("emoji name", "alien")
NC_("emoji name", "alien monster")
NC_("emoji name", "robot face")
NC_("emoji name", "pile of poo")
NC_("emoji name", "grinning cat face")
NC_("emoji name", "grinning cat face with smiling eyes")
NC_("emoji name", "cat face with tears of joy")
NC_("emoji name", "smiling cat face with heart-eyes")
NC_("emoji name", "cat face with wry smile")
NC_("emoji name", "kissing cat face")
NC_("emoji name", "weary cat face")
NC_("emoji name", "crying cat face")
NC_("emoji name", "pouting cat face")
NC_("emoji name", "see-no-evil monkey")
NC_("emoji name", "hear-no-evil monkey")
NC_("emoji name", "speak-no-evil monkey")
NC_("emoji name", "baby")
NC_("emoji name", "boy")
NC_("emoji name", "girl")
NC_("emoji name", "man")
NC_("emoji name", "woman")
NC_("emoji name", "old man")
NC_("emoji name", "old woman")
NC_("emoji name", "man health worker")
NC_("emoji name", "woman health worker")
NC_("emoji name", "man student")
NC_("emoji name", "woman student")
NC_("emoji name", "man teacher")
NC_("emoji name", "woman teacher")
NC_("emoji name", "man judge")
NC_("emoji name", "woman judge")
NC_("emoji name", "man farmer")
NC_("emoji name", "woman farmer")
NC_("emoji name", "man cook")
NC_("emoji name", "woman cook")
NC_("emoji name", "man mechanic")
NC_("emoji name", "woman mechanic")
NC_("emoji name", "man factory worker")
NC_("emoji name", "woman factory worker")
NC_("emoji name", "man office worker")
NC_("emoji name", "woman office worker")
NC_("emoji name", "man scientist")
NC_("emoji name", "woman scientist")
NC_("emoji name", "man technologist")
NC_("emoji name", "woman technologist")
NC_("emoji name", "man singer")
NC_("emoji name", "woman singer")
NC_("emoji name", "man artist")
NC_("emoji name", "woman artist")
NC_("emoji name", "man pilot")
NC_("emoji name", "woman pilot")
NC_("emoji name", "man astronaut")
NC_("emoji name", "woman astronaut")
NC_("emoji name", "man firefighter")
NC_("emoji name", "woman firefighter")
NC_("emoji name", "police officer")
NC_("emoji name", "man police officer")
NC_("emoji name", "woman police officer")
NC_("emoji name", "detective")
NC_("emoji name", "man detective")
NC_("emoji name", "woman detective")
NC_("emoji name", "guard")
NC_("emoji name", "man guard")
NC_("emoji name", "woman guard")
NC_("emoji name", "construction worker")
NC_("emoji name", "man construction worker")
NC_("emoji name", "woman construction worker")
NC_("emoji name", "prince")
NC_("emoji name", "princess")
NC_("emoji name", "person wearing turban")
NC_("emoji name", "man wearing turban")
NC_("emoji name", "woman wearing turban")
NC_("emoji name", "man with Chinese cap")
NC_("emoji name", "blond-haired person")
NC_("emoji name", "blond-haired man")
NC_("emoji name", "blond-haired woman")
NC_("emoji name", "man in tuxedo")
NC_("emoji name", "bride with veil")
NC_("emoji name", "pregnant woman")
NC_("emoji name", "baby angel")
NC_("emoji name", "Santa Claus")
NC_("emoji name", "Mrs. Claus")
NC_("emoji name", "person frowning")
NC_("emoji name", "man frowning")
NC_("emoji name", "woman frowning")
NC_("emoji name", "person pouting")
NC_("emoji name", "man pouting")
NC_("emoji name", "woman pouting")
NC_("emoji name", "person gesturing NO")
NC_("emoji name", "man gesturing NO")
NC_("emoji name", "woman gesturing NO")
NC_("emoji name", "person gesturing OK")
NC_("emoji name", "man gesturing OK")
NC_("emoji name", "woman gesturing OK")
NC_("emoji name", "person tipping hand")
NC_("emoji name", "man tipping hand")
NC_("emoji name", "woman tipping hand")
NC_("emoji name", "person raising hand")
NC_("emoji name", "man raising hand")
NC_("emoji name", "woman raising hand")
NC_("emoji name", "person bowing")
NC_("emoji name", "man bowing")
NC_("emoji name", "woman bowing")
NC_("emoji name", "person facepalming")
NC_("emoji name", "man facepalming")
NC_("emoji name", "woman facepalming")
NC_("emoji name", "person shrugging")
NC_("emoji name", "man shrugging")
NC_("emoji name", "woman shrugging")
NC_("emoji name", "person getting massage")
NC_("emoji name", "man getting massage")
NC_("emoji name", "woman getting massage")
NC_("emoji name", "person getting haircut")
NC_("emoji name", "man getting haircut")
NC_("emoji name", "woman getting haircut")
NC_("emoji name", "person walking")
NC_("emoji name", "man walking")
NC_("emoji name", "woman walking")
NC_("emoji name", "person running")
NC_("emoji name", "man running")
NC_("emoji name", "woman running")
NC_("emoji name", "woman dancing")
NC_("emoji name", "man dancing")
NC_("emoji name", "people with bunny ears")
NC_("emoji name", "men with bunny ears")
NC_("emoji name", "women with bunny ears")
NC_("emoji name", "person taking bath")
NC_("emoji name", "speaking head")
NC_("emoji name", "bust in silhouette")
NC_("emoji name", "busts in silhouette")
NC_("emoji name", "person fencing")
NC_("emoji name", "skier")
NC_("emoji name", "person surfing")
NC_("emoji name", "man surfing")
NC_("emoji name", "woman surfing")
NC_("emoji name", "person rowing boat")
NC_("emoji name", "man rowing boat")
NC_("emoji name", "woman rowing boat")
NC_("emoji name", "person swimming")
NC_("emoji name", "man swimming")
NC_("emoji name", "woman swimming")
NC_("emoji name", "person bouncing ball")
NC_("emoji name", "man bouncing ball")
NC_("emoji name", "woman bouncing ball")
NC_("emoji name", "person lifting weights")
NC_("emoji name", "man lifting weights")
NC_("emoji name", "woman lifting weights")
NC_("emoji name", "person biking")
NC_("emoji name", "man biking")
NC_("emoji name", "woman biking")
NC_("emoji name", "person mountain biking")
NC_("emoji name", "man mountain biking")
NC_("emoji name", "woman mountain biking")
NC_("emoji name", "racing car")
NC_("emoji name", "motorcycle")
NC_("emoji name", "person cartwheeling")
NC_("emoji name", "man cartwheeling")
NC_("emoji name", "woman cartwheeling")
NC_("emoji name", "people wrestling")
NC_("emoji name", "men wrestling")
NC_("emoji name", "women wrestling")
NC_("emoji name", "person playing water polo")
NC_("emoji name", "man playing water polo")
NC_("emoji name", "woman playing water polo")
NC_("emoji name", "person playing handball")
NC_("emoji name", "man playing handball")
NC_("emoji name", "woman playing handball")
NC_("emoji name", "person juggling")
NC_("emoji name", "man juggling")
NC_("emoji name", "woman juggling")
NC_("emoji name", "man and woman holding hands")
NC_("emoji name", "two men holding hands")
NC_("emoji name", "two women holding hands")
NC_("emoji name", "kiss")
NC_("emoji name", "kiss: woman, man")
NC_("emoji name", "kiss: man, man")
NC_("emoji name", "kiss: woman, woman")
NC_("emoji name", "couple with heart")
NC_("emoji name", "couple with heart: woman, man")
NC_("emoji name", "couple with heart: man, man")
NC_("emoji name", "couple with heart: woman, woman")
NC_("emoji name", "family")
NC_("emoji name", "family: man, woman, boy")
NC_("emoji name", "family: man, woman, girl")
NC_("emoji name", "family: man, woman, girl, boy")
NC_("emoji name", "family: man, woman, boy, boy")
NC_("emoji name", "family: man, woman, girl, girl")
NC_("emoji name", "family: man, man, boy")
NC_("emoji name", "family: man, man, girl")
NC_("emoji name", "family: man, man, girl, boy")
NC_("emoji name", "family: man, man, boy, boy")
NC_("emoji name", "family: man, man, girl, girl")
NC_("emoji name", "family: woman, woman, boy")
NC_("emoji name", "family: woman, woman, girl")
NC_("emoji name", "family: woman, woman, girl, boy")
NC_("emoji name", "family: woman, woman, boy, boy")
NC_("emoji name", "family: woman, woman, girl, girl")
NC_("emoji name", "family: man, boy")
NC_("emoji name", "family: man, boy, boy")
NC_("emoji name", "family: man, girl")
NC_("emoji name", "family: man, girl, boy")
NC_("emoji name", "family: man, girl, girl")
NC_("emoji name", "family: woman, boy")
NC_("emoji name", "family: woman, boy, boy")
NC_("emoji name", "family: woman, girl")
NC_("emoji name", "family: woman, girl, boy")
NC_("emoji name", "family: woman, girl, girl")
NC_("emoji name", "selfie")
NC_("emoji name", "flexed biceps")
NC_("emoji name", "backhand index pointing left")
NC_("emoji name", "backhand index pointing right")
NC_("emoji name", "index pointing up")
NC_("emoji name", "backhand index pointing up")
NC_("emoji name", "middle finger")
NC_("emoji name", "backhand index pointing down")
NC_("emoji name", "victory hand")
NC_("emoji name", "crossed fingers")
NC_("emoji name", "vulcan salute")
NC_("emoji name", "sign of the horns")
NC_("emoji name", "call me hand")
NC_("emoji name", "hand with fingers splayed")
NC_("emoji name", "raised hand")
NC_("emoji name", "OK hand")
NC_("emoji name", "thumbs up")
NC_("emoji name", "thumbs down")
NC_("emoji name", "raised fist")
NC_("emoji name", "oncoming fist")
NC_("emoji name", "left-facing fist")
NC_("emoji name", "right-facing fist")
NC_("emoji name", "raised back of hand")
NC_("emoji name", "waving hand")
NC_("emoji name", "writing hand")
NC_("emoji name", "clapping hands")
NC_("emoji name", "open hands")
NC_("emoji name", "raising hands")
NC_("emoji name", "folded hands")
NC_("emoji name", "handshake")
NC_("emoji name", "nail polish")
NC_("emoji name", "ear")
NC_("emoji name", "nose")
NC_("emoji name", "footprints")
NC_("emoji name", "eyes")
NC_("emoji name", "eye")
NC_("emoji name", "eye in speech bubble")
NC_("emoji name", "⊛ brain")
NC_("emoji name", "tongue")
NC_("emoji name", "mouth")
NC_("emoji name", "kiss mark")
NC_("emoji name", "heart with arrow")
NC_("emoji name", "red heart")
NC_("emoji name", "beating heart")
NC_("emoji name", "broken heart")
NC_("emoji name", "two hearts")
NC_("emoji name", "sparkling heart")
NC_("emoji name", "growing heart")
NC_("emoji name", "blue heart")
NC_("emoji name", "green heart")
NC_("emoji name", "yellow heart")
NC_("emoji name", "⊛ orange heart")
NC_("emoji name", "purple heart")
NC_("emoji name", "black heart")
NC_("emoji name", "heart with ribbon")
NC_("emoji name", "revolving hearts")
NC_("emoji name", "heart decoration")
NC_("emoji name", "heavy heart exclamation")
NC_("emoji name", "love letter")
NC_("emoji name", "zzz")
NC_("emoji name", "anger symbol")
NC_("emoji name", "bomb")
NC_("emoji name", "collision")
NC_("emoji name", "sweat droplets")
NC_("emoji name", "dashing away")
NC_("emoji name", "dizzy")
NC_("emoji name", "speech balloon")
NC_("emoji name", "left speech bubble")
NC_("emoji name", "right anger bubble")
NC_("emoji name", "thought balloon")
NC_("emoji name", "hole")
NC_("emoji name", "glasses")
NC_("emoji name", "sunglasses")
NC_("emoji name", "necktie")
NC_("emoji name", "t-shirt")
NC_("emoji name", "jeans")
NC_("emoji name", "⊛ scarf")
NC_("emoji name", "⊛ gloves")
NC_("emoji name", "⊛ coat")
NC_("emoji name", "⊛ socks")
NC_("emoji name", "dress")
NC_("emoji name", "kimono")
NC_("emoji name", "bikini")
NC_("emoji name", "woman’s clothes")
NC_("emoji name", "purse")
NC_("emoji name", "handbag")
NC_("emoji name", "clutch bag")
NC_("emoji name", "shopping bags")
NC_("emoji name", "school backpack")
NC_("emoji name", "man’s shoe")
NC_("emoji name", "running shoe")
NC_("emoji name", "high-heeled shoe")
NC_("emoji name", "woman’s sandal")
NC_("emoji name", "woman’s boot")
NC_("emoji name", "crown")
NC_("emoji name", "woman’s hat")
NC_("emoji name", "top hat")
NC_("emoji name", "graduation cap")
NC_("emoji name", "⊛ billed cap")
NC_("emoji name", "rescue worker’s helmet")
NC_("emoji name", "prayer beads")
NC_("emoji name", "lipstick")
NC_("emoji name", "ring")
NC_("emoji name", "gem stone")
NC_("emoji name", "monkey face")
NC_("emoji name", "monkey")
NC_("emoji name", "gorilla")
NC_("emoji name", "dog face")
NC_("emoji name", "dog")
NC_("emoji name", "poodle")
NC_("emoji name", "wolf face")
NC_("emoji name", "fox face")
NC_("emoji name", "cat face")
NC_("emoji name", "cat")
NC_("emoji name", "lion face")
NC_("emoji name", "tiger face")
NC_("emoji name", "tiger")
NC_("emoji name", "leopard")
NC_("emoji name", "horse face")
NC_("emoji name", "horse")
NC_("emoji name", "unicorn face")
NC_("emoji name", "⊛ zebra")
NC_("emoji name", "deer")
NC_("emoji name", "cow face")
NC_("emoji name", "ox")
NC_("emoji name", "water buffalo")
NC_("emoji name", "cow")
NC_("emoji name", "pig face")
NC_("emoji name", "pig")
NC_("emoji name", "boar")
NC_("emoji name", "pig nose")
NC_("emoji name", "ram")
NC_("emoji name", "ewe")
NC_("emoji name", "goat")
NC_("emoji name", "camel")
NC_("emoji name", "two-hump camel")
NC_("emoji name", "⊛ giraffe")
NC_("emoji name", "elephant")
NC_("emoji name", "rhinoceros")
NC_("emoji name", "mouse face")
NC_("emoji name", "mouse")
NC_("emoji name", "rat")
NC_("emoji name", "hamster face")
NC_("emoji name", "rabbit face")
NC_("emoji name", "rabbit")
NC_("emoji name", "chipmunk")
NC_("emoji name", "⊛ hedgehog")
NC_("emoji name", "bat")
NC_("emoji name", "bear face")
NC_("emoji name", "koala")
NC_("emoji name", "panda face")
NC_("emoji name", "paw prints")
NC_("emoji name", "turkey")
NC_("emoji name", "chicken")
NC_("emoji name", "rooster")
NC_("emoji name", "hatching chick")
NC_("emoji name", "baby chick")
NC_("emoji name", "front-facing baby chick")
NC_("emoji name", "bird")
NC_("emoji name", "penguin")
NC_("emoji name", "dove")
NC_("emoji name", "eagle")
NC_("emoji name", "duck")
NC_("emoji name", "owl")
NC_("emoji name", "frog face")
NC_("emoji name", "crocodile")
NC_("emoji name", "turtle")
NC_("emoji name", "lizard")
NC_("emoji name", "snake")
NC_("emoji name", "dragon face")
NC_("emoji name", "dragon")
NC_("emoji name", "⊛ sauropod")
NC_("emoji name", "⊛ T-Rex")
NC_("emoji name", "spouting whale")
NC_("emoji name", "whale")
NC_("emoji name", "dolphin")
NC_("emoji name", "fish")
NC_("emoji name", "tropical fish")
NC_("emoji name", "blowfish")
NC_("emoji name", "shark")
NC_("emoji name", "octopus")
NC_("emoji name", "spiral shell")
NC_("emoji name", "crab")
NC_("emoji name", "shrimp")
NC_("emoji name", "squid")
NC_("emoji name", "snail")
NC_("emoji name", "butterfly")
NC_("emoji name", "bug")
NC_("emoji name", "ant")
NC_("emoji name", "honeybee")
NC_("emoji name", "lady beetle")
NC_("emoji name", "⊛ cricket")
NC_("emoji name", "spider")
NC_("emoji name", "spider web")
NC_("emoji name", "scorpion")
NC_("emoji name", "bouquet")
NC_("emoji name", "cherry blossom")
NC_("emoji name", "white flower")
NC_("emoji name", "rosette")
NC_("emoji name", "rose")
NC_("emoji name", "wilted flower")
NC_("emoji name", "hibiscus")
NC_("emoji name", "sunflower")
NC_("emoji name", "blossom")
NC_("emoji name", "tulip")
NC_("emoji name", "seedling")
NC_("emoji name", "evergreen tree")
NC_("emoji name", "deciduous tree")
NC_("emoji name", "palm tree")
NC_("emoji name", "cactus")
NC_("emoji name", "sheaf of rice")
NC_("emoji name", "herb")
NC_("emoji name", "shamrock")
NC_("emoji name", "four leaf clover")
NC_("emoji name", "maple leaf")
NC_("emoji name", "fallen leaf")
NC_("emoji name", "leaf fluttering in wind")
NC_("emoji name", "grapes")
NC_("emoji name", "melon")
NC_("emoji name", "watermelon")
NC_("emoji name", "tangerine")
NC_("emoji name", "lemon")
NC_("emoji name", "banana")
NC_("emoji name", "pineapple")
NC_("emoji name", "red apple")
NC_("emoji name", "green apple")
NC_("emoji name", "pear")
NC_("emoji name", "peach")
NC_("emoji name", "cherries")
NC_("emoji name", "strawberry")
NC_("emoji name", "kiwi fruit")
NC_("emoji name", "tomato")
NC_("emoji name", "⊛ coconut")
NC_("emoji name", "avocado")
NC_("emoji name", "eggplant")
NC_("emoji name", "potato")
NC_("emoji name", "carrot")
NC_("emoji name", "ear of corn")
NC_("emoji name", "hot pepper")
NC_("emoji name", "cucumber")
NC_("emoji name", "⊛ broccoli")
NC_("emoji name", "mushroom")
NC_("emoji name", "peanuts")
NC_("emoji name", "chestnut")
NC_("emoji name", "bread")
NC_("emoji name", "croissant")
NC_("emoji name", "baguette bread")
NC_("emoji name", "⊛ pretzel")
NC_("emoji name", "pancakes")
NC_("emoji name", "cheese wedge")
NC_("emoji name", "meat on bone")
NC_("emoji name", "poultry leg")
NC_("emoji name", "⊛ cut of meat")
NC_("emoji name", "bacon")
NC_("emoji name", "hamburger")
NC_("emoji name", "french fries")
NC_("emoji name", "pizza")
NC_("emoji name", "hot dog")
NC_("emoji name", "⊛ sandwich")
NC_("emoji name", "taco")
NC_("emoji name", "burrito")
NC_("emoji name", "stuffed flatbread")
NC_("emoji name", "egg")
NC_("emoji name", "cooking")
NC_("emoji name", "shallow pan of food")
NC_("emoji name", "pot of food")
NC_("emoji name", "⊛ bowl with spoon")
NC_("emoji name", "green salad")
NC_("emoji name", "popcorn")
NC_("emoji name", "⊛ canned food")
NC_("emoji name", "bento box")
NC_("emoji name", "rice cracker")
NC_("emoji name", "rice ball")
NC_("emoji name", "cooked rice")
NC_("emoji name", "curry rice")
NC_("emoji name", "steaming bowl")
NC_("emoji name", "spaghetti")
NC_("emoji name", "roasted sweet potato")
NC_("emoji name", "oden")
NC_("emoji name", "sushi")
NC_("emoji name", "fried shrimp")
NC_("emoji name", "fish cake with swirl")
NC_("emoji name", "dango")
NC_("emoji name", "⊛ dumpling")
NC_("emoji name", "⊛ fortune cookie")
NC_("emoji name", "⊛ takeout box")
NC_("emoji name", "soft ice cream")
NC_("emoji name", "shaved ice")
NC_("emoji name", "ice cream")
NC_("emoji name", "doughnut")
NC_("emoji name", "cookie")
NC_("emoji name", "birthday cake")
NC_("emoji name", "shortcake")
NC_("emoji name", "⊛ pie")
NC_("emoji name", "chocolate bar")
NC_("emoji name", "candy")
NC_("emoji name", "lollipop")
NC_("emoji name", "custard")
NC_("emoji name", "honey pot")
NC_("emoji name", "baby bottle")
NC_("emoji name", "glass of milk")
NC_("emoji name", "hot beverage")
NC_("emoji name", "teacup without handle")
NC_("emoji name", "sake")
NC_("emoji name", "bottle with popping cork")
NC_("emoji name", "wine glass")
NC_("emoji name", "cocktail glass")
NC_("emoji name", "tropical drink")
NC_("emoji name", "beer mug")
NC_("emoji name", "clinking beer mugs")
NC_("emoji name", "clinking glasses")
NC_("emoji name", "tumbler glass")
NC_("emoji name", "⊛ cup with straw")
NC_("emoji name", "⊛ chopsticks")
NC_("emoji name", "fork and knife with plate")
NC_("emoji name", "fork and knife")
NC_("emoji name", "spoon")
NC_("emoji name", "kitchen knife")
NC_("emoji name", "amphora")
NC_("emoji name", "globe showing Europe-Africa")
NC_("emoji name", "globe showing Americas")
NC_("emoji name", "globe showing Asia-Australia")
NC_("emoji name", "globe with meridians")
NC_("emoji name", "map of Japan")
NC_("emoji name", "snow-capped mountain")
NC_("emoji name", "mountain")
NC_("emoji name", "volcano")
NC_("emoji name", "mount fuji")
NC_("emoji name", "camping")
NC_("emoji name", "beach with umbrella")
NC_("emoji name", "desert")
NC_("emoji name", "desert island")
NC_("emoji name", "national park")
NC_("emoji name", "stadium")
NC_("emoji name", "classical building")
NC_("emoji name", "building construction")
NC_("emoji name", "houses")
NC_("emoji name", "cityscape")
NC_("emoji name", "derelict house")
NC_("emoji name", "house")
NC_("emoji name", "house with garden")
NC_("emoji name", "office building")
NC_("emoji name", "Japanese post office")
NC_("emoji name", "post office")
NC_("emoji name", "hospital")
NC_("emoji name", "bank")
NC_("emoji name", "hotel")
NC_("emoji name", "love hotel")
NC_("emoji name", "convenience store")
NC_("emoji name", "school")
NC_("emoji name", "department store")
NC_("emoji name", "factory")
NC_("emoji name", "Japanese castle")
NC_("emoji name", "castle")
NC_("emoji name", "wedding")
NC_("emoji name", "Tokyo tower")
NC_("emoji name", "Statue of Liberty")
NC_("emoji name", "church")
NC_("emoji name", "mosque")
NC_("emoji name", "synagogue")
NC_("emoji name", "shinto shrine")
NC_("emoji name", "kaaba")
NC_("emoji name", "fountain")
NC_("emoji name", "tent")
NC_("emoji name", "foggy")
NC_("emoji name", "night with stars")
NC_("emoji name", "sunrise over mountains")
NC_("emoji name", "sunrise")
NC_("emoji name", "cityscape at dusk")
NC_("emoji name", "sunset")
NC_("emoji name", "bridge at night")
NC_("emoji name", "hot springs")
NC_("emoji name", "milky way")
NC_("emoji name", "carousel horse")
NC_("emoji name", "ferris wheel")
NC_("emoji name", "roller coaster")
NC_("emoji name", "barber pole")
NC_("emoji name", "circus tent")
NC_("emoji name", "performing arts")
NC_("emoji name", "framed picture")
NC_("emoji name", "artist palette")
NC_("emoji name", "slot machine")
NC_("emoji name", "locomotive")
NC_("emoji name", "railway car")
NC_("emoji name", "high-speed train")
NC_("emoji name", "bullet train")
NC_("emoji name", "train")
NC_("emoji name", "metro")
NC_("emoji name", "light rail")
NC_("emoji name", "station")
NC_("emoji name", "tram")
NC_("emoji name", "monorail")
NC_("emoji name", "mountain railway")
NC_("emoji name", "tram car")
NC_("emoji name", "bus")
NC_("emoji name", "oncoming bus")
NC_("emoji name", "trolleybus")
NC_("emoji name", "minibus")
NC_("emoji name", "ambulance")
NC_("emoji name", "fire engine")
NC_("emoji name", "police car")
NC_("emoji name", "oncoming police car")
NC_("emoji name", "taxi")
NC_("emoji name", "oncoming taxi")
NC_("emoji name", "automobile")
NC_("emoji name", "oncoming automobile")
NC_("emoji name", "sport utility vehicle")
NC_("emoji name", "delivery truck")
NC_("emoji name", "articulated lorry")
NC_("emoji name", "tractor")
NC_("emoji name", "bicycle")
NC_("emoji name", "kick scooter")
NC_("emoji name", "motor scooter")
NC_("emoji name", "bus stop")
NC_("emoji name", "motorway")
NC_("emoji name", "railway track")
NC_("emoji name", "fuel pump")
NC_("emoji name", "police car light")
NC_("emoji name", "horizontal traffic light")
NC_("emoji name", "vertical traffic light")
NC_("emoji name", "construction")
NC_("emoji name", "stop sign")
NC_("emoji name", "anchor")
NC_("emoji name", "sailboat")
NC_("emoji name", "canoe")
NC_("emoji name", "speedboat")
NC_("emoji name", "passenger ship")
NC_("emoji name", "ferry")
NC_("emoji name", "motor boat")
NC_("emoji name", "ship")
NC_("emoji name", "airplane")
NC_("emoji name", "small airplane")
NC_("emoji name", "airplane departure")
NC_("emoji name", "airplane arrival")
NC_("emoji name", "seat")
NC_("emoji name", "helicopter")
NC_("emoji name", "suspension railway")
NC_("emoji name", "mountain cableway")
NC_("emoji name", "aerial tramway")
NC_("emoji name", "satellite")
NC_("emoji name", "rocket")
NC_("emoji name", "⊛ flying saucer")
NC_("emoji name", "bellhop bell")
NC_("emoji name", "door")
NC_("emoji name", "bed")
NC_("emoji name", "couch and lamp")
NC_("emoji name", "toilet")
NC_("emoji name", "shower")
NC_("emoji name", "bathtub")
NC_("emoji name", "hourglass done")
NC_("emoji name", "hourglass not done")
NC_("emoji name", "watch")
NC_("emoji name", "alarm clock")
NC_("emoji name", "stopwatch")
NC_("emoji name", "timer clock")
NC_("emoji name", "mantelpiece clock")
NC_("emoji name", "twelve o’clock")
NC_("emoji name", "twelve-thirty")
NC_("emoji name", "one o’clock")
NC_("emoji name", "one-thirty")
NC_("emoji name", "two o’clock")
NC_("emoji name", "two-thirty")
NC_("emoji name", "three o’clock")
NC_("emoji name", "three-thirty")
NC_("emoji name", "four o’clock")
NC_("emoji name", "four-thirty")
NC_("emoji name", "five o’clock")
NC_("emoji name", "five-thirty")
NC_("emoji name", "six o’clock")
NC_("emoji name", "six-thirty")
NC_("emoji name", "seven o’clock")
NC_("emoji name", "seven-thirty")
NC_("emoji name", "eight o’clock")
NC_("emoji name", "eight-thirty")
NC_("emoji name", "nine o’clock")
NC_("emoji name", "nine-thirty")
NC_("emoji name", "ten o’clock")
NC_("emoji name", "ten-thirty")
NC_("emoji name", "eleven o’clock")
NC_("emoji name", "eleven-thirty")
NC_("emoji name", "new moon")
NC_("emoji name", "waxing crescent moon")
NC_("emoji name", "first quarter moon")
NC_("emoji name", "waxing gibbous moon")
NC_("emoji name", "full moon")
NC_("emoji name", "waning gibbous moon")
NC_("emoji name", "last quarter moon")
NC_("emoji name", "waning crescent moon")
NC_("emoji name", "crescent moon")
NC_("emoji name", "new moon face")
NC_("emoji name", "first quarter moon face")
NC_("emoji name", "last quarter moon face")
NC_("emoji name", "thermometer")
NC_("emoji name", "sun")
NC_("emoji name", "full moon face")
NC_("emoji name", "sun with face")
NC_("emoji name", "white medium star")
NC_("emoji name", "glowing star")
NC_("emoji name", "shooting star")
NC_("emoji name", "cloud")
NC_("emoji name", "sun behind cloud")
NC_("emoji name", "cloud with lightning and rain")
NC_("emoji name", "sun behind small cloud")
NC_("emoji name", "sun behind large cloud")
NC_("emoji name", "sun behind rain cloud")
NC_("emoji name", "cloud with rain")
NC_("emoji name", "cloud with snow")
NC_("emoji name", "cloud with lightning")
NC_("emoji name", "tornado")
NC_("emoji name", "fog")
NC_("emoji name", "wind face")
NC_("emoji name", "cyclone")
NC_("emoji name", "rainbow")
NC_("emoji name", "closed umbrella")
NC_("emoji name", "umbrella")
NC_("emoji name", "umbrella with rain drops")
NC_("emoji name", "umbrella on ground")
NC_("emoji name", "high voltage")
NC_("emoji name", "snowflake")
NC_("emoji name", "snowman")
NC_("emoji name", "snowman without snow")
NC_("emoji name", "comet")
NC_("emoji name", "fire")
NC_("emoji name", "droplet")
NC_("emoji name", "water wave")
NC_("emoji name", "jack-o-lantern")
NC_("emoji name", "Christmas tree")
NC_("emoji name", "fireworks")
NC_("emoji name", "sparkler")
NC_("emoji name", "sparkles")
NC_("emoji name", "balloon")
NC_("emoji name", "party popper")
NC_("emoji name", "confetti ball")
NC_("emoji name", "tanabata tree")
NC_("emoji name", "pine decoration")
NC_("emoji name", "Japanese dolls")
NC_("emoji name", "carp streamer")
NC_("emoji name", "wind chime")
NC_("emoji name", "moon viewing ceremony")
NC_("emoji name", "ribbon")
NC_("emoji name", "wrapped gift")
NC_("emoji name", "reminder ribbon")
NC_("emoji name", "admission tickets")
NC_("emoji name", "ticket")
NC_("emoji name", "military medal")
NC_("emoji name", "trophy")
NC_("emoji name", "sports medal")
NC_("emoji name", "1st place medal")
NC_("emoji name", "2nd place medal")
NC_("emoji name", "3rd place medal")
NC_("emoji name", "soccer ball")
NC_("emoji name", "baseball")
NC_("emoji name", "basketball")
NC_("emoji name", "volleyball")
NC_("emoji name", "american football")
NC_("emoji name", "rugby football")
NC_("emoji name", "tennis")
NC_("emoji name", "pool 8 ball")
NC_("emoji name", "bowling")
NC_("emoji name", "cricket game")
NC_("emoji name", "field hockey")
NC_("emoji name", "ice hockey")
NC_("emoji name", "ping pong")
NC_("emoji name", "badminton")
NC_("emoji name", "boxing glove")
NC_("emoji name", "martial arts uniform")
NC_("emoji name", "goal net")
NC_("emoji name", "direct hit")
NC_("emoji name", "flag in hole")
NC_("emoji name", "ice skate")
NC_("emoji name", "fishing pole")
NC_("emoji name", "running shirt")
NC_("emoji name", "skis")
NC_("emoji name", "⊛ sled")
NC_("emoji name", "⊛ curling stone")
NC_("emoji name", "video game")
NC_("emoji name", "joystick")
NC_("emoji name", "game die")
NC_("emoji name", "spade suit")
NC_("emoji name", "heart suit")
NC_("emoji name", "diamond suit")
NC_("emoji name", "club suit")
NC_("emoji name", "joker")
NC_("emoji name", "mahjong red dragon")
NC_("emoji name", "flower playing cards")
NC_("emoji name", "muted speaker")
NC_("emoji name", "speaker low volume")
NC_("emoji name", "speaker medium volume")
NC_("emoji name", "speaker high volume")
NC_("emoji name", "loudspeaker")
NC_("emoji name", "megaphone")
NC_("emoji name", "postal horn")
NC_("emoji name", "bell")
NC_("emoji name", "bell with slash")
NC_("emoji name", "musical score")
NC_("emoji name", "musical note")
NC_("emoji name", "musical notes")
NC_("emoji name", "studio microphone")
NC_("emoji name", "level slider")
NC_("emoji name", "control knobs")
NC_("emoji name", "microphone")
NC_("emoji name", "headphone")
NC_("emoji name", "radio")
NC_("emoji name", "saxophone")
NC_("emoji name", "guitar")
NC_("emoji name", "musical keyboard")
NC_("emoji name", "trumpet")
NC_("emoji name", "violin")
NC_("emoji name", "drum")
NC_("emoji name", "mobile phone")
NC_("emoji name", "mobile phone with arrow")
NC_("emoji name", "telephone")
NC_("emoji name", "telephone receiver")
NC_("emoji name", "pager")
NC_("emoji name", "fax machine")
NC_("emoji name", "battery")
NC_("emoji name", "electric plug")
NC_("emoji name", "laptop computer")
NC_("emoji name", "desktop computer")
NC_("emoji name", "printer")
NC_("emoji name", "keyboard")
NC_("emoji name", "computer mouse")
NC_("emoji name", "trackball")
NC_("emoji name", "computer disk")
NC_("emoji name", "floppy disk")
NC_("emoji name", "optical disk")
NC_("emoji name", "dvd")
NC_("emoji name", "movie camera")
NC_("emoji name", "film frames")
NC_("emoji name", "film projector")
NC_("emoji name", "clapper board")
NC_("emoji name", "television")
NC_("emoji name", "camera")
NC_("emoji name", "camera with flash")
NC_("emoji name", "video camera")
NC_("emoji name", "videocassette")
NC_("emoji name", "magnifying glass tilted left")
NC_("emoji name", "magnifying glass tilted right")
NC_("emoji name", "microscope")
NC_("emoji name", "telescope")
NC_("emoji name", "satellite antenna")
NC_("emoji name", "candle")
NC_("emoji name", "light bulb")
NC_("emoji name", "flashlight")
NC_("emoji name", "red paper lantern")
NC_("emoji name", "notebook with decorative cover")
NC_("emoji name", "closed book")
NC_("emoji name", "open book")
NC_("emoji name", "green book")
NC_("emoji name", "blue book")
NC_("emoji name", "orange book")
NC_("emoji name", "books")
NC_("emoji name", "notebook")
NC_("emoji name", "ledger")
NC_("emoji name", "page with curl")
NC_("emoji name", "scroll")
NC_("emoji name", "page facing up")
NC_("emoji name", "newspaper")
NC_("emoji name", "rolled-up newspaper")
NC_("emoji name", "bookmark tabs")
NC_("emoji name", "bookmark")
NC_("emoji name", "label")
NC_("emoji name", "money bag")
NC_("emoji name", "yen banknote")
NC_("emoji name", "dollar banknote")
NC_("emoji name", "euro banknote")
NC_("emoji name", "pound banknote")
NC_("emoji name", "money with wings")
NC_("emoji name", "credit card")
NC_("emoji name", "chart increasing with yen")
NC_("emoji name", "currency exchange")
NC_("emoji name", "heavy dollar sign")
NC_("emoji name", "envelope")
NC_("emoji name", "e-mail")
NC_("emoji name", "incoming envelope")
NC_("emoji name", "envelope with arrow")
NC_("emoji name", "outbox tray")
NC_("emoji name", "inbox tray")
NC_("emoji name", "package")
NC_("emoji name", "closed mailbox with raised flag")
NC_("emoji name", "closed mailbox with lowered flag")
NC_("emoji name", "open mailbox with raised flag")
NC_("emoji name", "open mailbox with lowered flag")
NC_("emoji name", "postbox")
NC_("emoji name", "ballot box with ballot")
NC_("emoji name", "pencil")
NC_("emoji name", "black nib")
NC_("emoji name", "fountain pen")
NC_("emoji name", "pen")
NC_("emoji name", "paintbrush")
NC_("emoji name", "crayon")
NC_("emoji name", "memo")
NC_("emoji name", "briefcase")
NC_("emoji name", "file folder")
NC_("emoji name", "open file folder")
NC_("emoji name", "card index dividers")
NC_("emoji name", "calendar")
NC_("emoji name", "tear-off calendar")
NC_("emoji name", "spiral notepad")
NC_("emoji name", "spiral calendar")
NC_("emoji name", "card index")
NC_("emoji name", "chart increasing")
NC_("emoji name", "chart decreasing")
NC_("emoji name", "bar chart")
NC_("emoji name", "clipboard")
NC_("emoji name", "pushpin")
NC_("emoji name", "round pushpin")
NC_("emoji name", "paperclip")
NC_("emoji name", "linked paperclips")
NC_("emoji name", "straight ruler")
NC_("emoji name", "triangular ruler")
NC_("emoji name", "scissors")
NC_("emoji name", "card file box")
NC_("emoji name", "file cabinet")
NC_("emoji name", "wastebasket")
NC_("emoji name", "locked")
NC_("emoji name", "unlocked")
NC_("emoji name", "locked with pen")
NC_("emoji name", "locked with key")
NC_("emoji name", "key")
NC_("emoji name", "old key")
NC_("emoji name", "hammer")
NC_("emoji name", "pick")
NC_("emoji name", "hammer and pick")
NC_("emoji name", "hammer and wrench")
NC_("emoji name", "dagger")
NC_("emoji name", "crossed swords")
NC_("emoji name", "pistol")
NC_("emoji name", "bow and arrow")
NC_("emoji name", "shield")
NC_("emoji name", "wrench")
NC_("emoji name", "nut and bolt")
NC_("emoji name", "gear")
NC_("emoji name", "clamp")
NC_("emoji name", "alembic")
NC_("emoji name", "balance scale")
NC_("emoji name", "link")
NC_("emoji name", "chains")
NC_("emoji name", "syringe")
NC_("emoji name", "pill")
NC_("emoji name", "cigarette")
NC_("emoji name", "coffin")
NC_("emoji name", "funeral urn")
NC_("emoji name", "moai")
NC_("emoji name", "oil drum")
NC_("emoji name", "crystal ball")
NC_("emoji name", "shopping cart")
NC_("emoji name", "ATM sign")
NC_("emoji name", "litter in bin sign")
NC_("emoji name", "potable water")
NC_("emoji name", "wheelchair symbol")
NC_("emoji name", "men’s room")
NC_("emoji name", "women’s room")
NC_("emoji name", "restroom")
NC_("emoji name", "baby symbol")
NC_("emoji name", "water closet")
NC_("emoji name", "passport control")
NC_("emoji name", "customs")
NC_("emoji name", "baggage claim")
NC_("emoji name", "left luggage")
NC_("emoji name", "warning")
NC_("emoji name", "no entry")
NC_("emoji name", "prohibited")
NC_("emoji name", "no bicycles")
NC_("emoji name", "no smoking")
NC_("emoji name", "no littering")
NC_("emoji name", "non-potable water")
NC_("emoji name", "no pedestrians")
NC_("emoji name", "no mobile phones")
NC_("emoji name", "no one under eighteen")
NC_("emoji name", "radioactive")
NC_("emoji name", "biohazard")
NC_("emoji name", "up arrow")
NC_("emoji name", "up-right arrow")
NC_("emoji name", "right arrow")
NC_("emoji name", "down-right arrow")
NC_("emoji name", "down arrow")
NC_("emoji name", "down-left arrow")
NC_("emoji name", "left arrow")
NC_("emoji name", "up-left arrow")
NC_("emoji name", "up-down arrow")
NC_("emoji name", "left-right arrow")
NC_("emoji name", "right arrow curving left")
NC_("emoji name", "left arrow curving right")
NC_("emoji name", "right arrow curving up")
NC_("emoji name", "right arrow curving down")
NC_("emoji name", "clockwise vertical arrows")
NC_("emoji name", "counterclockwise arrows button")
NC_("emoji name", "BACK arrow")
NC_("emoji name", "END arrow")
NC_("emoji name", "ON! arrow")
NC_("emoji name", "SOON arrow")
NC_("emoji name", "TOP arrow")
NC_("emoji name", "place of worship")
NC_("emoji name", "atom symbol")
NC_("emoji name", "om")
NC_("emoji name", "star of David")
NC_("emoji name", "wheel of dharma")
NC_("emoji name", "yin yang")
NC_("emoji name", "latin cross")
NC_("emoji name", "orthodox cross")
NC_("emoji name", "star and crescent")
NC_("emoji name", "peace symbol")
NC_("emoji name", "menorah")
NC_("emoji name", "dotted six-pointed star")
NC_("emoji name", "Aries")
NC_("emoji name", "Taurus")
NC_("emoji name", "Gemini")
NC_("emoji name", "Cancer")
NC_("emoji name", "Leo")
NC_("emoji name", "Virgo")
NC_("emoji name", "Libra")
NC_("emoji name", "Scorpius")
NC_("emoji name", "Sagittarius")
NC_("emoji name", "Capricorn")
NC_("emoji name", "Aquarius")
NC_("emoji name", "Pisces")
NC_("emoji name", "Ophiuchus")
NC_("emoji name", "shuffle tracks button")
NC_("emoji name", "repeat button")
NC_("emoji name", "repeat single button")
NC_("emoji name", "play button")
NC_("emoji name", "fast-forward button")
NC_("emoji name", "next track button")
NC_("emoji name", "play or pause button")
NC_("emoji name", "reverse button")
NC_("emoji name", "fast reverse button")
NC_("emoji name", "last track button")
NC_("emoji name", "up button")
NC_("emoji name", "fast up button")
NC_("emoji name", "down button")
NC_("emoji name", "fast down button")
NC_("emoji name", "pause button")
NC_("emoji name", "stop button")
NC_("emoji name", "record button")
NC_("emoji name", "eject button")
NC_("emoji name", "cinema")
NC_("emoji name", "dim button")
NC_("emoji name", "bright button")
NC_("emoji name", "antenna bars")
NC_("emoji name", "vibration mode")
NC_("emoji name", "mobile phone off")
NC_("emoji name", "female sign")
NC_("emoji name", "male sign")
NC_("emoji name", "medical symbol")
NC_("emoji name", "recycling symbol")
NC_("emoji name", "fleur-de-lis")
NC_("emoji name", "trident emblem")
NC_("emoji name", "name badge")
NC_("emoji name", "Japanese symbol for beginner")
NC_("emoji name", "heavy large circle")
NC_("emoji name", "white heavy check mark")
NC_("emoji name", "ballot box with check")
NC_("emoji name", "heavy check mark")
NC_("emoji name", "heavy multiplication x")
NC_("emoji name", "cross mark")
NC_("emoji name", "cross mark button")
NC_("emoji name", "heavy plus sign")
NC_("emoji name", "heavy minus sign")
NC_("emoji name", "heavy division sign")
NC_("emoji name", "curly loop")
NC_("emoji name", "double curly loop")
NC_("emoji name", "part alternation mark")
NC_("emoji name", "eight-spoked asterisk")
NC_("emoji name", "eight-pointed star")
NC_("emoji name", "sparkle")
NC_("emoji name", "double exclamation mark")
NC_("emoji name", "exclamation question mark")
NC_("emoji name", "question mark")
NC_("emoji name", "white question mark")
NC_("emoji name", "white exclamation mark")
NC_("emoji name", "exclamation mark")
NC_("emoji name", "wavy dash")
NC_("emoji name", "copyright")
NC_("emoji name", "registered")
NC_("emoji name", "trade mark")
NC_("emoji name", "keycap: #")
NC_("emoji name", "keycap: *")
NC_("emoji name", "keycap: 0")
NC_("emoji name", "keycap: 1")
NC_("emoji name", "keycap: 2")
NC_("emoji name", "keycap: 3")
NC_("emoji name", "keycap: 4")
NC_("emoji name", "keycap: 5")
NC_("emoji name", "keycap: 6")
NC_("emoji name", "keycap: 7")
NC_("emoji name", "keycap: 8")
NC_("emoji name", "keycap: 9")
NC_("emoji name", "keycap 10")
NC_("emoji name", "hundred points")
NC_("emoji name", "input latin uppercase")
NC_("emoji name", "input latin lowercase")
NC_("emoji name", "input numbers")
NC_("emoji name", "input symbols")
NC_("emoji name", "input latin letters")
NC_("emoji name", "A button (blood type)")
NC_("emoji name", "AB button (blood type)")
NC_("emoji name", "B button (blood type)")
NC_("emoji name", "CL button")
NC_("emoji name", "COOL button")
NC_("emoji name", "FREE button")
NC_("emoji name", "information")
NC_("emoji name", "ID button")
NC_("emoji name", "circled M")
NC_("emoji name", "NEW button")
NC_("emoji name", "NG button")
NC_("emoji name", "O button (blood type)")
NC_("emoji name", "OK button")
NC_("emoji name", "P button")
NC_("emoji name", "SOS button")
NC_("emoji name", "UP! button")
NC_("emoji name", "VS button")
NC_("emoji name", "Japanese “here” button")
NC_("emoji name", "Japanese “service charge” button")
NC_("emoji name", "Japanese “monthly amount” button")
NC_("emoji name", "Japanese “not free of charge” button")
NC_("emoji name", "Japanese “reserved” button")
NC_("emoji name", "Japanese “bargain” button")
NC_("emoji name", "Japanese “discount” button")
NC_("emoji name", "Japanese “free of charge” button")
NC_("emoji name", "Japanese “prohibited” button")
NC_("emoji name", "Japanese “acceptable” button")
NC_("emoji name", "Japanese “application” button")
NC_("emoji name", "Japanese “passing grade” button")
NC_("emoji name", "Japanese “vacancy” button")
NC_("emoji name", "Japanese “congratulations” button")
NC_("emoji name", "Japanese “secret” button")
NC_("emoji name", "Japanese “open for business” button")
NC_("emoji name", "Japanese “no vacancy” button")
NC_("emoji name", "black small square")
NC_("emoji name", "white small square")
NC_("emoji name", "white medium square")
NC_("emoji name", "black medium square")
NC_("emoji name", "white medium-small square")
NC_("emoji name", "black medium-small square")
NC_("emoji name", "black large square")
NC_("emoji name", "white large square")
NC_("emoji name", "large orange diamond")
NC_("emoji name", "large blue diamond")
NC_("emoji name", "small orange diamond")
NC_("emoji name", "small blue diamond")
NC_("emoji name", "red triangle pointed up")
NC_("emoji name", "red triangle pointed down")
NC_("emoji name", "diamond with a dot")
NC_("emoji name", "radio button")
NC_("emoji name", "black square button")
NC_("emoji name", "white square button")
NC_("emoji name", "white circle")
NC_("emoji name", "black circle")
NC_("emoji name", "red circle")
NC_("emoji name", "blue circle")
NC_("emoji name", "chequered flag")
NC_("emoji name", "triangular flag")
NC_("emoji name", "crossed flags")
NC_("emoji name", "black flag")
NC_("emoji name", "white flag")
NC_("emoji name", "rainbow flag")
NC_("emoji name", "Ascension Island")
NC_("emoji name", "Andorra")
NC_("emoji name", "United Arab Emirates")
NC_("emoji name", "Afghanistan")
NC_("emoji name", "Antigua & Barbuda")
NC_("emoji name", "Anguilla")
NC_("emoji name", "Albania")
NC_("emoji name", "Armenia")
NC_("emoji name", "Angola")
NC_("emoji name", "Antarctica")
NC_("emoji name", "Argentina")
NC_("emoji name", "American Samoa")
NC_("emoji name", "Austria")
NC_("emoji name", "Australia")
NC_("emoji name", "Aruba")
NC_("emoji name", "Åland Islands")
NC_("emoji name", "Azerbaijan")
NC_("emoji name", "Bosnia & Herzegovina")
NC_("emoji name", "Barbados")
NC_("emoji name", "Bangladesh")
NC_("emoji name", "Belgium")
NC_("emoji name", "Burkina Faso")
NC_("emoji name", "Bulgaria")
NC_("emoji name", "Bahrain")
NC_("emoji name", "Burundi")
NC_("emoji name", "Benin")
NC_("emoji name", "St. Barthélemy")
NC_("emoji name", "Bermuda")
NC_("emoji name", "Brunei")
NC_("emoji name", "Bolivia")
NC_("emoji name", "Caribbean Netherlands")
NC_("emoji name", "Brazil")
NC_("emoji name", "Bahamas")
NC_("emoji name", "Bhutan")
NC_("emoji name", "Bouvet Island")
NC_("emoji name", "Botswana")
NC_("emoji name", "Belarus")
NC_("emoji name", "Belize")
NC_("emoji name", "Canada")
NC_("emoji name", "Cocos (Keeling) Islands")
NC_("emoji name", "Congo - Kinshasa")
NC_("emoji name", "Central African Republic")
NC_("emoji name", "Congo - Brazzaville")
NC_("emoji name", "Switzerland")
NC_("emoji name", "Côte d’Ivoire")
NC_("emoji name", "Cook Islands")
NC_("emoji name", "Chile")
NC_("emoji name", "Cameroon")
NC_("emoji name", "China")
NC_("emoji name", "Colombia")
NC_("emoji name", "Clipperton Island")
NC_("emoji name", "Costa Rica")
NC_("emoji name", "Cuba")
NC_("emoji name", "Cape Verde")
NC_("emoji name", "Curaçao")
NC_("emoji name", "Christmas Island")
NC_("emoji name", "Cyprus")
NC_("emoji name", "Czechia")
NC_("emoji name", "Germany")
NC_("emoji name", "Diego Garcia")
NC_("emoji name", "Djibouti")
NC_("emoji name", "Denmark")
NC_("emoji name", "Dominica")
NC_("emoji name", "Dominican Republic")
NC_("emoji name", "Algeria")
NC_("emoji name", "Ceuta & Melilla")
NC_("emoji name", "Ecuador")
NC_("emoji name", "Estonia")
NC_("emoji name", "Egypt")
NC_("emoji name", "Western Sahara")
NC_("emoji name", "Eritrea")
NC_("emoji name", "Spain")
NC_("emoji name", "Ethiopia")
NC_("emoji name", "European Union")
NC_("emoji name", "Finland")
NC_("emoji name", "Fiji")
NC_("emoji name", "Falkland Islands")
NC_("emoji name", "Micronesia")
NC_("emoji name", "Faroe Islands")
NC_("emoji name", "France")
NC_("emoji name", "Gabon")
NC_("emoji name", "United Kingdom")
NC_("emoji name", "Grenada")
NC_("emoji name", "Georgia")
NC_("emoji name", "French Guiana")
NC_("emoji name", "Guernsey")
NC_("emoji name", "Ghana")
NC_("emoji name", "Gibraltar")
NC_("emoji name", "Greenland")
NC_("emoji name", "Gambia")
NC_("emoji name", "Guinea")
NC_("emoji name", "Guadeloupe")
NC_("emoji name", "Equatorial Guinea")
NC_("emoji name", "Greece")
NC_("emoji name", "South Georgia & South Sandwich Islands")
NC_("emoji name", "Guatemala")
NC_("emoji name", "Guam")
NC_("emoji name", "Guinea-Bissau")
NC_("emoji name", "Guyana")
NC_("emoji name", "Hong Kong SAR China")
NC_("emoji name", "Heard & McDonald Islands")
NC_("emoji name", "Honduras")
NC_("emoji name", "Croatia")
NC_("emoji name", "Haiti")
NC_("emoji name", "Hungary")
NC_("emoji name", "Canary Islands")
NC_("emoji name", "Indonesia")
NC_("emoji name", "Ireland")
NC_("emoji name", "Israel")
NC_("emoji name", "Isle of Man")
NC_("emoji name", "India")
NC_("emoji name", "British Indian Ocean Territory")
NC_("emoji name", "Iraq")
NC_("emoji name", "Iran")
NC_("emoji name", "Iceland")
NC_("emoji name", "Italy")
NC_("emoji name", "Jersey")
NC_("emoji name", "Jamaica")
NC_("emoji name", "Jordan")
NC_("emoji name", "Japan")
NC_("emoji name", "Kenya")
NC_("emoji name", "Kyrgyzstan")
NC_("emoji name", "Cambodia")
NC_("emoji name", "Kiribati")
NC_("emoji name", "Comoros")
NC_("emoji name", "St. Kitts & Nevis")
NC_("emoji name", "North Korea")
NC_("emoji name", "South Korea")
NC_("emoji name", "Kuwait")
NC_("emoji name", "Cayman Islands")
NC_("emoji name", "Kazakhstan")
NC_("emoji name", "Laos")
NC_("emoji name", "Lebanon")
NC_("emoji name", "St. Lucia")
NC_("emoji name", "Liechtenstein")
NC_("emoji name", "Sri Lanka")
NC_("emoji name", "Liberia")
NC_("emoji name", "Lesotho")
NC_("emoji name", "Lithuania")
NC_("emoji name", "Luxembourg")
NC_("emoji name", "Latvia")
NC_("emoji name", "Libya")
NC_("emoji name", "Morocco")
NC_("emoji name", "Monaco")
NC_("emoji name", "Moldova")
NC_("emoji name", "Montenegro")
NC_("emoji name", "St. Martin")
NC_("emoji name", "Madagascar")
NC_("emoji name", "Marshall Islands")
NC_("emoji name", "Macedonia")
NC_("emoji name", "Mali")
NC_("emoji name", "Myanmar (Burma)")
NC_("emoji name", "Mongolia")
NC_("emoji name", "Macau SAR China")
NC_("emoji name", "Northern Mariana Islands")
NC_("emoji name", "Martinique")
NC_("emoji name", "Mauritania")
NC_("emoji name", "Montserrat")
NC_("emoji name", "Malta")
NC_("emoji name", "Mauritius")
NC_("emoji name", "Maldives")
NC_("emoji name", "Malawi")
NC_("emoji name", "Mexico")
NC_("emoji name", "Malaysia")
NC_("emoji name", "Mozambique")
NC_("emoji name", "Namibia")
NC_("emoji name", "New Caledonia")
NC_("emoji name", "Niger")
NC_("emoji name", "Norfolk Island")
NC_("emoji name", "Nigeria")
NC_("emoji name", "Nicaragua")
NC_("emoji name", "Netherlands")
NC_("emoji name", "Norway")
NC_("emoji name", "Nepal")
NC_("emoji name", "Nauru")
NC_("emoji name", "Niue")
NC_("emoji name", "New Zealand")
NC_("emoji name", "Oman")
NC_("emoji name", "Panama")
NC_("emoji name", "Peru")
NC_("emoji name", "French Polynesia")
NC_("emoji name", "Papua New Guinea")
NC_("emoji name", "Philippines")
NC_("emoji name", "Pakistan")
NC_("emoji name", "Poland")
NC_("emoji name", "St. Pierre & Miquelon")
NC_("emoji name", "Pitcairn Islands")
NC_("emoji name", "Puerto Rico")
NC_("emoji name", "Palestinian Territories")
NC_("emoji name", "Portugal")
NC_("emoji name", "Palau")
NC_("emoji name", "Paraguay")
NC_("emoji name", "Qatar")
NC_("emoji name", "Réunion")
NC_("emoji name", "Romania")
NC_("emoji name", "Serbia")
NC_("emoji name", "Russia")
NC_("emoji name", "Rwanda")
NC_("emoji name", "Saudi Arabia")
NC_("emoji name", "Solomon Islands")
NC_("emoji name", "Seychelles")
NC_("emoji name", "Sudan")
NC_("emoji name", "Sweden")
NC_("emoji name", "Singapore")
NC_("emoji name", "St. Helena")
NC_("emoji name", "Slovenia")
NC_("emoji name", "Svalbard & Jan Mayen")
NC_("emoji name", "Slovakia")
NC_("emoji name", "Sierra Leone")
NC_("emoji name", "San Marino")
NC_("emoji name", "Senegal")
NC_("emoji name", "Somalia")
NC_("emoji name", "Suriname")
NC_("emoji name", "South Sudan")
NC_("emoji name", "São Tomé & Príncipe")
NC_("emoji name", "El Salvador")
NC_("emoji name", "Sint Maarten")
NC_("emoji name", "Syria")
NC_("emoji name", "Swaziland")
NC_("emoji name", "Tristan da Cunha")
NC_("emoji name", "Turks & Caicos Islands")
NC_("emoji name", "Chad")
NC_("emoji name", "French Southern Territories")
NC_("emoji name", "Togo")
NC_("emoji name", "Thailand")
NC_("emoji name", "Tajikistan")
NC_("emoji name", "Tokelau")
NC_("emoji name", "Timor-Leste")
NC_("emoji name", "Turkmenistan")
NC_("emoji name", "Tunisia")
NC_("emoji name", "Tonga")
NC_("emoji name", "Turkey")
NC_("emoji name", "Trinidad & Tobago")
NC_("emoji name", "Tuvalu")
NC_("emoji name", "Taiwan")
NC_("emoji name", "Tanzania")
NC_("emoji name", "Ukraine")
NC_("emoji name", "Uganda")
NC_("emoji name", "U.S. Outlying Islands")
NC_("emoji name", "United Nations")
NC_("emoji name", "United States")
NC_("emoji name", "Uruguay")
NC_("emoji name", "Uzbekistan")
NC_("emoji name", "Vatican City")
NC_("emoji name", "St. Vincent & Grenadines")
NC_("emoji name", "Venezuela")
NC_("emoji name", "British Virgin Islands")
NC_("emoji name", "U.S. Virgin Islands")
NC_("emoji name", "Vietnam")
NC_("emoji name", "Vanuatu")
NC_("emoji name", "Wallis & Futuna")
NC_("emoji name", "Samoa")
NC_("emoji name", "Kosovo")
NC_("emoji name", "Yemen")
NC_("emoji name", "Mayotte")
NC_("emoji name", "South Africa")
NC_("emoji name", "Zambia")
NC_("emoji name", "Zimbabwe")
NC_("emoji name", "⊛ England")
NC_("emoji name", "⊛ Scotland")
NC_("emoji name", "⊛ Wales")


#endif
