inspector_c_sources = 			\
	inspector/action-editor.c	\
	inspector/actions.c		\
	inspector/cellrenderergraph.c	\
	inspector/classes-list.c	\
	inspector/css-editor.c		\
	inspector/css-node-tree.c	\
	inspector/data-list.c		\
	inspector/general.c		\
	inspector/gestures.c		\
	inspector/graphdata.c		\
	inspector/gtktreemodelcssnode.c	\
	inspector/init.c		\
	inspector/inspect-button.c	\
	inspector/magnifier.c		\
	inspector/menu.c		\
	inspector/misc-info.c		\
	inspector/object-hierarchy.c	\
	inspector/object-tree.c		\
	inspector/prop-editor.c		\
	inspector/prop-list.c		\
	inspector/resource-list.c	\
	inspector/selector.c		\
	inspector/signals-list.c	\
	inspector/size-groups.c		\
	inspector/statistics.c		\
	inspector/style-prop-list.c	\
	inspector/treewalk.c		\
	inspector/visual.c		\
	inspector/window.c

inspector_h_sources = 			\
	inspector/action-editor.h	\
	inspector/actions.h		\
	inspector/cellrenderergraph.h	\
	inspector/classes-list.h	\
	inspector/css-editor.h		\
	inspector/css-node-tree.h	\
	inspector/data-list.h		\
	inspector/general.h		\
	inspector/gestures.h		\
	inspector/graphdata.h		\
	inspector/gtktreemodelcssnode.h	\
	inspector/init.h		\
	inspector/magnifier.h		\
	inspector/menu.h		\
	inspector/misc-info.h		\
	inspector/object-hierarchy.h	\
	inspector/object-tree.h		\
	inspector/prop-editor.h		\
	inspector/prop-list.h		\
	inspector/resource-list.h	\
	inspector/selector.h		\
	inspector/signals-list.h	\
	inspector/size-groups.h		\
	inspector/statistics.h		\
	inspector/style-prop-list.h	\
	inspector/treewalk.h		\
	inspector/visual.h		\
	inspector/window.h

inspector_templates =			\
	inspector/actions.ui 		\
	inspector/classes-list.ui 	\
	inspector/css-editor.ui 	\
	inspector/css-node-tree.ui	\
	inspector/data-list.ui 		\
	inspector/general.ui 		\
	inspector/magnifier.ui		\
	inspector/menu.ui		\
	inspector/misc-info.ui		\
	inspector/object-hierarchy.ui 	\
	inspector/object-tree.ui 	\
	inspector/prop-list.ui 		\
	inspector/resource-list.ui	\
	inspector/selector.ui		\
	inspector/signals-list.ui	\
	inspector/statistics.ui		\
	inspector/style-prop-list.ui	\
	inspector/visual.ui		\
	inspector/window.ui
