N_("Select an Object");
N_("Show all Objects");
N_("Show all Resources");
N_("Miscellaneous");
N_("Properties");
N_("Signals");
N_("Hierarchy");
N_("Child Properties");
N_("CSS Classes");
N_("Style Properties");
N_("Custom CSS");
N_("Size Groups");
N_("Data");
N_("Actions");
N_("Menu");
N_("Gestures");
N_("Objects");
N_("Resources");
N_("Custom CSS");
N_("Visual");
N_("General");
