#
# To use this makefile, do:
# make -f Makefile.gtkfaq
#
# This is not done by default because you might
# not have sgml2html installed... Perhaps we could
# detect that in the future and combine it in with
# the automake stuff...
#

all: html ps

html: faq tut italian_tut
	perl gtkdocs_fix gtkfaq*.html gtk_tut*.html

txt:
	sgml2txt gtkfaq.sgml
	sgml2txt gtk_tut.sgml
	sgml2txt gtk_tut_it.sgml

ps: dvi
	dvips -o gtkfaq.ps gtkfaq.dvi
	dvips -o gtk_tut.ps gtk_tut.dvi
	dvips -o gtk_tut_it.ps gtk_tut_it.dvi

dvi: 
	sgml2latex gtkfaq.sgml
	sgml2latex gtk_tut.sgml
	sgml2latex gtk_tut_it.sgml

faq:
	sgml2html gtkfaq.sgml

tut:
	sgml2html gtk_tut.sgml

italian_tut:
	sgml2html gtk_tut_it.sgml


