#
# To use this makefile, do:
# make -f Makefile.gtkfaq
#
# This is not done by default because you might
# not have sgml2html installed... Perhaps we could
# detect that in the future and combine it in with
# the automake stuff...
#

all: html

html: faq tut italian_tut
	perl gtkdocs_fix gtkfaq*.html gtk_tut*.html

faq:
	sgml2html gtkfaq.sgml

tut:
	sgml2html gtk_tut.sgml

italian_tut:
	sgml2html gtk_tut_it.sgml
